name: 'setup-cache'

inputs:
  docker_hub_pat:
    description: 'Auth token for Docker Hub, required for BuildJet jobs'
    required: false
    default: ''
  sleep_time:
    description: 'Time to sleep between retries'
    required: false
    default: 30

outputs:
  duration:
    description: 'Duration of the setup process in seconds'
    value: ${{ steps.get_duration.outputs.duration }}

runs:
  using: "composite"
  steps:
    # build cache
    - uses: ./.github/workflows/setup-with-retry
    # try to save rootfs image cache
    - name: Save rootfs cache
      uses: actions/cache/save@v4
      #if: github.ref == 'refs/heads/master'
      with:
        path: /tmp/rootfs_cache.tar
        key: rootfs-${{ runner.arch }}-${{ env.CACHE_FILE_HASHES }}
