name: 'setup-cache'

runs:
  using: "composite"
  steps:
    # build cache
    - uses: ./.github/workflows/setup-with-retry
    # try to save rootfs image cache
    - name: Save rootfs cache
      uses: actions/cache/save@v4
      #if: github.ref == 'refs/heads/master'
      with:
        path: /tmp/rootfs_cache.tar
        key: rootfs-${{ runner.arch }}-${{ env.CACHE_FILE_HASHES }}
