// THIS IS AN AUTOGENERATED FILE, PLEASE EDIT alerts_offroad.json
QT_TRANSLATE_NOOP("OffroadAlert", R"(Device temperature too high. System cooling down before starting. Current internal component temperature: %1)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(Immediately connect to the internet to check for updates. If you do not connect to the internet, openpilot won't engage in %1)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(Connect to internet to check for updates. openpilot won't automatically start until it connects to internet to check for updates.)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(Unable to download updates
%1)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(Taking camera snapshots. System won't start until finished.)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(An update to your device's operating system is downloading in the background. You will be prompted to update when it's ready to install.)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(Device failed to register. It will not connect to or upload to comma.ai servers, and receives no support from comma.ai. If this is an official device, visit https://comma.ai/support.)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(NVMe drive not mounted.)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(Unsupported NVMe drive detected. Device may draw significantly more power and overheat due to the unsupported NVMe.)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(openpilot was unable to identify your car. Your car is either unsupported or its ECUs are not recognized. Please submit a pull request to add the firmware versions to the proper vehicle. Need help? Join discord.comma.ai.)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(openpilot was unable to identify your car. Check integrity of cables and ensure all connections are secure, particularly that the comma power is fully inserted in the OBD-II port of the vehicle. Need help? Join discord.comma.ai.)");
QT_TRANSLATE_NOOP("OffroadAlert", R"(openpilot detected a change in the device's mounting position. Ensure the device is fully seated in the mount and the mount is firmly secured to the windshield.)");
