CI / testing:
  - all:
    - changed-files: ['.github/**', '**/test_*', 'Jenkinsfile']

car: 
  - all:
    - changed-files: ['selfdrive/car/**']

body:
  - all:
    - changed-files: ['selfdrive/car/body/*']
chrysler:
  - all:
    - changed-files: ['selfdrive/car/chrysler/*']
ford: 
  - all:
    - changed-files: ['selfdrive/car/ford/*']
gm: 
  - all:
    - changed-files: ['selfdrive/car/gm/*']
honda: 
  - all:
    - changed-files: ['selfdrive/car/honda/*']
hyundai: 
  - all:
    - changed-files: ['selfdrive/car/hyundai/*']
mazda: 
  - all:
    - changed-files: ['selfdrive/car/mazda/*']
nissan: 
  - all:
    - changed-files: ['selfdrive/car/nissan/*']
subaru: 
  - all:
    - changed-files: ['selfdrive/car/subaru/*']
tesla: 
  - all:
    - changed-files: ['selfdrive/car/tesla/*']
toyota: 
  - all:
    - changed-files: ['selfdrive/car/toyota/*']
volkswagen: 
  - all:
    - changed-files: ['selfdrive/car/volkswagen/*']

fingerprint:
  - all:
    - changed-files: ['selfdrive/car/*/fingerprints.py']

simulation:
  - all:
    - changed-files: ['tools/sim/**']
ui:
  - all:
    - changed-files: ['selfdrive/ui/**']
tools: 
  - all:
    - changed-files: ['tools/**']

multilanguage:
  - all:
    - changed-files: ['selfdrive/ui/translations/**']

research:
  - all:
    - changed-files: [
        'selfdrive/modeld/models/**',
        'selfdrive/test/process_replay/model_replay_ref_commit',
      ]
