CI / testing:
  - changed-files:
    - any-glob-to-all-files: "{.github/**,**/test_*,**/test/**,Jenkinsfile}"

car:
  - changed-files:
    - any-glob-to-all-files: '{openpilot/selfdrive/car/**,opendbc_repo}'

simulation:
  - changed-files:
    - any-glob-to-all-files: 'openpilot/tools/sim/**'

ui:
  - changed-files:
    - any-glob-to-all-files: '{openpilot/selfdrive/assets/**,openpilot/selfdrive/ui/**,openpilot/system/ui/**}'

tools:
  - changed-files:
    - any-glob-to-all-files: 'openpilot/tools/**'

multilanguage:
  - changed-files:
    - any-glob-to-all-files: 'openpilot/selfdrive/ui/translations/**'

autonomy:
  - changed-files:
    - any-glob-to-all-files: "{openpilot/selfdrive/modeld/models/**,openpilot/selfdrive/test/process_replay/model_replay_ref_commit}"
