#!/bin/sh

if [ $# -gt 0 ]; then
    if [ "$2" = use_api ]; then
        python get_files_comma_api.py $1 && ./_nui use_api
    else
        ./_nui "$1"
    fi
else
    echo "Please Enter a Route"
fi
 