Import('qt_env', 'common', 'messaging', 'gpucommon', 'visionipc', 'cereal')

qt_env['CPPPATH'] += ["#tools/clib"]
qt_env['CXXFLAGS'] += ["-Wno-deprecated-declarations"]

libs = qt_env['LIBS'] + ['pthread', 'capnp', 'kj', 'zmq', messaging, 'avutil', 'avcodec', 'avformat', 'swscale', 'bz2']

qt_modules = ["Widgets", "Gui", "Core", "DBus", "Multimedia", "Network"]
qt_libs = [f"Qt5{m}" for m in qt_modules]

qt_env.Program("_nui",
               ['main.cpp', 'Unlogger.cpp', 'FileReader.cpp', '../clib/FrameReader.cpp'],
               LIBS=libs)
