Import('qt_env', 'messaging')

qt_env['CPPPATH'] += ["#tools/clib"]
qt_env['CXXFLAGS'] += ["-Wno-deprecated-declarations"]

libs = [messaging, 'avutil', 'avcodec', 'avformat', 'bz2', 'capnp', 'kj',
        'pthread', 'swscale', 'zmq']

qt_env.Program("_nui",
               ['main.cpp', 'Unlogger.cpp', 'FileReader.cpp', '../clib/FrameReader.cpp'],
               LIBS=qt_env['LIBS'] + libs)
