/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lat_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[3] = {0, 0, 0};

/* lat_expl_vde_forw:(i0[6],i1[6x6],i2[6],i3,i4[])->(o0[6],o1[6x6],o2[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][4] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=(a0*a2);
  a4=arg[0]? arg[0][5] : 0;
  a5=sin(a1);
  a6=(a4*a5);
  a7=arg[0]? arg[0][3] : 0;
  a8=(a0*a7);
  a9=(a6*a8);
  a3=(a3-a9);
  if (res[0]!=0) res[0][0]=a3;
  a3=sin(a1);
  a9=(a0*a3);
  a10=cos(a1);
  a11=(a4*a10);
  a12=(a0*a7);
  a13=(a11*a12);
  a9=(a9+a13);
  if (res[0]!=0) res[0][1]=a9;
  a9=(a0*a7);
  if (res[0]!=0) res[0][2]=a9;
  a9=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][3]=a9;
  a9=0.;
  if (res[0]!=0) res[0][4]=a9;
  if (res[0]!=0) res[0][5]=a9;
  a13=arg[1]? arg[1][4] : 0;
  a14=(a2*a13);
  a15=sin(a1);
  a16=arg[1]? arg[1][2] : 0;
  a17=(a15*a16);
  a17=(a0*a17);
  a14=(a14-a17);
  a17=arg[1]? arg[1][5] : 0;
  a18=(a5*a17);
  a19=cos(a1);
  a20=(a19*a16);
  a20=(a4*a20);
  a18=(a18+a20);
  a18=(a8*a18);
  a20=(a7*a13);
  a21=arg[1]? arg[1][3] : 0;
  a22=(a0*a21);
  a20=(a20+a22);
  a20=(a6*a20);
  a18=(a18+a20);
  a14=(a14-a18);
  if (res[1]!=0) res[1][0]=a14;
  a14=(a3*a13);
  a18=cos(a1);
  a20=(a18*a16);
  a20=(a0*a20);
  a14=(a14+a20);
  a17=(a10*a17);
  a20=sin(a1);
  a16=(a20*a16);
  a16=(a4*a16);
  a17=(a17-a16);
  a17=(a12*a17);
  a16=(a7*a13);
  a22=(a0*a21);
  a16=(a16+a22);
  a16=(a11*a16);
  a17=(a17+a16);
  a14=(a14+a17);
  if (res[1]!=0) res[1][1]=a14;
  a13=(a7*a13);
  a21=(a0*a21);
  a13=(a13+a21);
  if (res[1]!=0) res[1][2]=a13;
  if (res[1]!=0) res[1][3]=a9;
  if (res[1]!=0) res[1][4]=a9;
  if (res[1]!=0) res[1][5]=a9;
  a13=arg[1]? arg[1][10] : 0;
  a21=(a2*a13);
  a14=arg[1]? arg[1][8] : 0;
  a17=(a15*a14);
  a17=(a0*a17);
  a21=(a21-a17);
  a17=arg[1]? arg[1][11] : 0;
  a16=(a5*a17);
  a22=(a19*a14);
  a22=(a4*a22);
  a16=(a16+a22);
  a16=(a8*a16);
  a22=(a7*a13);
  a23=arg[1]? arg[1][9] : 0;
  a24=(a0*a23);
  a22=(a22+a24);
  a22=(a6*a22);
  a16=(a16+a22);
  a21=(a21-a16);
  if (res[1]!=0) res[1][6]=a21;
  a21=(a3*a13);
  a16=(a18*a14);
  a16=(a0*a16);
  a21=(a21+a16);
  a17=(a10*a17);
  a14=(a20*a14);
  a14=(a4*a14);
  a17=(a17-a14);
  a17=(a12*a17);
  a14=(a7*a13);
  a16=(a0*a23);
  a14=(a14+a16);
  a14=(a11*a14);
  a17=(a17+a14);
  a21=(a21+a17);
  if (res[1]!=0) res[1][7]=a21;
  a13=(a7*a13);
  a23=(a0*a23);
  a13=(a13+a23);
  if (res[1]!=0) res[1][8]=a13;
  if (res[1]!=0) res[1][9]=a9;
  if (res[1]!=0) res[1][10]=a9;
  if (res[1]!=0) res[1][11]=a9;
  a13=arg[1]? arg[1][16] : 0;
  a23=(a2*a13);
  a21=arg[1]? arg[1][14] : 0;
  a17=(a15*a21);
  a17=(a0*a17);
  a23=(a23-a17);
  a17=arg[1]? arg[1][17] : 0;
  a14=(a5*a17);
  a16=(a19*a21);
  a16=(a4*a16);
  a14=(a14+a16);
  a14=(a8*a14);
  a16=(a7*a13);
  a22=arg[1]? arg[1][15] : 0;
  a24=(a0*a22);
  a16=(a16+a24);
  a16=(a6*a16);
  a14=(a14+a16);
  a23=(a23-a14);
  if (res[1]!=0) res[1][12]=a23;
  a23=(a3*a13);
  a14=(a18*a21);
  a14=(a0*a14);
  a23=(a23+a14);
  a17=(a10*a17);
  a21=(a20*a21);
  a21=(a4*a21);
  a17=(a17-a21);
  a17=(a12*a17);
  a21=(a7*a13);
  a14=(a0*a22);
  a21=(a21+a14);
  a21=(a11*a21);
  a17=(a17+a21);
  a23=(a23+a17);
  if (res[1]!=0) res[1][13]=a23;
  a13=(a7*a13);
  a22=(a0*a22);
  a13=(a13+a22);
  if (res[1]!=0) res[1][14]=a13;
  if (res[1]!=0) res[1][15]=a9;
  if (res[1]!=0) res[1][16]=a9;
  if (res[1]!=0) res[1][17]=a9;
  a13=arg[1]? arg[1][22] : 0;
  a22=(a2*a13);
  a23=arg[1]? arg[1][20] : 0;
  a17=(a15*a23);
  a17=(a0*a17);
  a22=(a22-a17);
  a17=arg[1]? arg[1][23] : 0;
  a21=(a5*a17);
  a14=(a19*a23);
  a14=(a4*a14);
  a21=(a21+a14);
  a21=(a8*a21);
  a14=(a7*a13);
  a16=arg[1]? arg[1][21] : 0;
  a24=(a0*a16);
  a14=(a14+a24);
  a14=(a6*a14);
  a21=(a21+a14);
  a22=(a22-a21);
  if (res[1]!=0) res[1][18]=a22;
  a22=(a3*a13);
  a21=(a18*a23);
  a21=(a0*a21);
  a22=(a22+a21);
  a17=(a10*a17);
  a23=(a20*a23);
  a23=(a4*a23);
  a17=(a17-a23);
  a17=(a12*a17);
  a23=(a7*a13);
  a21=(a0*a16);
  a23=(a23+a21);
  a23=(a11*a23);
  a17=(a17+a23);
  a22=(a22+a17);
  if (res[1]!=0) res[1][19]=a22;
  a13=(a7*a13);
  a16=(a0*a16);
  a13=(a13+a16);
  if (res[1]!=0) res[1][20]=a13;
  if (res[1]!=0) res[1][21]=a9;
  if (res[1]!=0) res[1][22]=a9;
  if (res[1]!=0) res[1][23]=a9;
  a13=arg[1]? arg[1][28] : 0;
  a16=(a2*a13);
  a22=arg[1]? arg[1][26] : 0;
  a17=(a15*a22);
  a17=(a0*a17);
  a16=(a16-a17);
  a17=arg[1]? arg[1][29] : 0;
  a23=(a5*a17);
  a21=(a19*a22);
  a21=(a4*a21);
  a23=(a23+a21);
  a23=(a8*a23);
  a21=(a7*a13);
  a14=arg[1]? arg[1][27] : 0;
  a24=(a0*a14);
  a21=(a21+a24);
  a21=(a6*a21);
  a23=(a23+a21);
  a16=(a16-a23);
  if (res[1]!=0) res[1][24]=a16;
  a16=(a3*a13);
  a23=(a18*a22);
  a23=(a0*a23);
  a16=(a16+a23);
  a17=(a10*a17);
  a22=(a20*a22);
  a22=(a4*a22);
  a17=(a17-a22);
  a17=(a12*a17);
  a22=(a7*a13);
  a23=(a0*a14);
  a22=(a22+a23);
  a22=(a11*a22);
  a17=(a17+a22);
  a16=(a16+a17);
  if (res[1]!=0) res[1][25]=a16;
  a13=(a7*a13);
  a14=(a0*a14);
  a13=(a13+a14);
  if (res[1]!=0) res[1][26]=a13;
  if (res[1]!=0) res[1][27]=a9;
  if (res[1]!=0) res[1][28]=a9;
  if (res[1]!=0) res[1][29]=a9;
  a13=arg[1]? arg[1][34] : 0;
  a14=(a2*a13);
  a16=arg[1]? arg[1][32] : 0;
  a15=(a15*a16);
  a15=(a0*a15);
  a14=(a14-a15);
  a15=arg[1]? arg[1][35] : 0;
  a17=(a5*a15);
  a19=(a19*a16);
  a19=(a4*a19);
  a17=(a17+a19);
  a17=(a8*a17);
  a19=(a7*a13);
  a22=arg[1]? arg[1][33] : 0;
  a23=(a0*a22);
  a19=(a19+a23);
  a19=(a6*a19);
  a17=(a17+a19);
  a14=(a14-a17);
  if (res[1]!=0) res[1][30]=a14;
  a14=(a3*a13);
  a18=(a18*a16);
  a18=(a0*a18);
  a14=(a14+a18);
  a15=(a10*a15);
  a20=(a20*a16);
  a20=(a4*a20);
  a15=(a15-a20);
  a15=(a12*a15);
  a20=(a7*a13);
  a16=(a0*a22);
  a20=(a20+a16);
  a20=(a11*a20);
  a15=(a15+a20);
  a14=(a14+a15);
  if (res[1]!=0) res[1][31]=a14;
  a13=(a7*a13);
  a22=(a0*a22);
  a13=(a13+a22);
  if (res[1]!=0) res[1][32]=a13;
  if (res[1]!=0) res[1][33]=a9;
  if (res[1]!=0) res[1][34]=a9;
  if (res[1]!=0) res[1][35]=a9;
  a13=arg[2]? arg[2][4] : 0;
  a2=(a2*a13);
  a22=sin(a1);
  a14=arg[2]? arg[2][2] : 0;
  a22=(a22*a14);
  a22=(a0*a22);
  a2=(a2-a22);
  a22=arg[2]? arg[2][5] : 0;
  a5=(a5*a22);
  a15=cos(a1);
  a15=(a15*a14);
  a15=(a4*a15);
  a5=(a5+a15);
  a8=(a8*a5);
  a5=(a7*a13);
  a15=arg[2]? arg[2][3] : 0;
  a20=(a0*a15);
  a5=(a5+a20);
  a6=(a6*a5);
  a8=(a8+a6);
  a2=(a2-a8);
  if (res[2]!=0) res[2][0]=a2;
  a3=(a3*a13);
  a2=cos(a1);
  a2=(a2*a14);
  a2=(a0*a2);
  a3=(a3+a2);
  a10=(a10*a22);
  a1=sin(a1);
  a1=(a1*a14);
  a4=(a4*a1);
  a10=(a10-a4);
  a12=(a12*a10);
  a10=(a7*a13);
  a4=(a0*a15);
  a10=(a10+a4);
  a11=(a11*a10);
  a12=(a12+a11);
  a3=(a3+a12);
  if (res[2]!=0) res[2][1]=a3;
  a7=(a7*a13);
  a0=(a0*a15);
  a7=(a7+a0);
  if (res[2]!=0) res[2][2]=a7;
  a7=1.;
  if (res[2]!=0) res[2][3]=a7;
  if (res[2]!=0) res[2][4]=a9;
  if (res[2]!=0) res[2][5]=a9;
  return 0;
}

CASADI_SYMBOL_EXPORT int lat_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lat_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lat_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lat_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lat_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lat_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lat_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void lat_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lat_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int lat_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real lat_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lat_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lat_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lat_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lat_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lat_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
