/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lat_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};

/* lat_expl_vde_forw:(i0[4],i1[4x4],i2[4],i3,i4[2])->(o0[4],o1[4x4],o2[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[4]? arg[4][0] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a2=(a0*a2);
  a3=arg[4]? arg[4][1] : 0;
  a4=sin(a1);
  a4=(a3*a4);
  a5=arg[0]? arg[0][3] : 0;
  a6=(a0*a5);
  a7=(a4*a6);
  a2=(a2-a7);
  if (res[0]!=0) res[0][0]=a2;
  a2=sin(a1);
  a2=(a0*a2);
  a7=cos(a1);
  a7=(a3*a7);
  a8=(a0*a5);
  a9=(a7*a8);
  a2=(a2+a9);
  if (res[0]!=0) res[0][1]=a2;
  a5=(a0*a5);
  if (res[0]!=0) res[0][2]=a5;
  a5=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][3]=a5;
  a5=sin(a1);
  a2=arg[1]? arg[1][2] : 0;
  a9=(a5*a2);
  a9=(a0*a9);
  a10=cos(a1);
  a11=(a10*a2);
  a11=(a3*a11);
  a11=(a6*a11);
  a12=arg[1]? arg[1][3] : 0;
  a13=(a0*a12);
  a13=(a4*a13);
  a11=(a11+a13);
  a9=(a9+a11);
  a9=(-a9);
  if (res[1]!=0) res[1][0]=a9;
  a9=cos(a1);
  a11=(a9*a2);
  a11=(a0*a11);
  a13=(a0*a12);
  a13=(a7*a13);
  a14=sin(a1);
  a2=(a14*a2);
  a2=(a3*a2);
  a2=(a8*a2);
  a13=(a13-a2);
  a11=(a11+a13);
  if (res[1]!=0) res[1][1]=a11;
  a12=(a0*a12);
  if (res[1]!=0) res[1][2]=a12;
  a12=0.;
  if (res[1]!=0) res[1][3]=a12;
  a11=arg[1]? arg[1][6] : 0;
  a13=(a5*a11);
  a13=(a0*a13);
  a2=(a10*a11);
  a2=(a3*a2);
  a2=(a6*a2);
  a15=arg[1]? arg[1][7] : 0;
  a16=(a0*a15);
  a16=(a4*a16);
  a2=(a2+a16);
  a13=(a13+a2);
  a13=(-a13);
  if (res[1]!=0) res[1][4]=a13;
  a13=(a9*a11);
  a13=(a0*a13);
  a2=(a0*a15);
  a2=(a7*a2);
  a11=(a14*a11);
  a11=(a3*a11);
  a11=(a8*a11);
  a2=(a2-a11);
  a13=(a13+a2);
  if (res[1]!=0) res[1][5]=a13;
  a15=(a0*a15);
  if (res[1]!=0) res[1][6]=a15;
  if (res[1]!=0) res[1][7]=a12;
  a15=arg[1]? arg[1][10] : 0;
  a13=(a5*a15);
  a13=(a0*a13);
  a2=(a10*a15);
  a2=(a3*a2);
  a2=(a6*a2);
  a11=arg[1]? arg[1][11] : 0;
  a16=(a0*a11);
  a16=(a4*a16);
  a2=(a2+a16);
  a13=(a13+a2);
  a13=(-a13);
  if (res[1]!=0) res[1][8]=a13;
  a13=(a9*a15);
  a13=(a0*a13);
  a2=(a0*a11);
  a2=(a7*a2);
  a15=(a14*a15);
  a15=(a3*a15);
  a15=(a8*a15);
  a2=(a2-a15);
  a13=(a13+a2);
  if (res[1]!=0) res[1][9]=a13;
  a11=(a0*a11);
  if (res[1]!=0) res[1][10]=a11;
  if (res[1]!=0) res[1][11]=a12;
  a11=arg[1]? arg[1][14] : 0;
  a5=(a5*a11);
  a5=(a0*a5);
  a10=(a10*a11);
  a10=(a3*a10);
  a10=(a6*a10);
  a13=arg[1]? arg[1][15] : 0;
  a2=(a0*a13);
  a2=(a4*a2);
  a10=(a10+a2);
  a5=(a5+a10);
  a5=(-a5);
  if (res[1]!=0) res[1][12]=a5;
  a9=(a9*a11);
  a9=(a0*a9);
  a5=(a0*a13);
  a5=(a7*a5);
  a14=(a14*a11);
  a14=(a3*a14);
  a14=(a8*a14);
  a5=(a5-a14);
  a9=(a9+a5);
  if (res[1]!=0) res[1][13]=a9;
  a13=(a0*a13);
  if (res[1]!=0) res[1][14]=a13;
  if (res[1]!=0) res[1][15]=a12;
  a12=sin(a1);
  a13=arg[2]? arg[2][2] : 0;
  a12=(a12*a13);
  a12=(a0*a12);
  a9=cos(a1);
  a9=(a9*a13);
  a9=(a3*a9);
  a6=(a6*a9);
  a9=arg[2]? arg[2][3] : 0;
  a5=(a0*a9);
  a4=(a4*a5);
  a6=(a6+a4);
  a12=(a12+a6);
  a12=(-a12);
  if (res[2]!=0) res[2][0]=a12;
  a12=cos(a1);
  a12=(a12*a13);
  a12=(a0*a12);
  a6=(a0*a9);
  a7=(a7*a6);
  a1=sin(a1);
  a1=(a1*a13);
  a3=(a3*a1);
  a8=(a8*a3);
  a7=(a7-a8);
  a12=(a12+a7);
  if (res[2]!=0) res[2][1]=a12;
  a0=(a0*a9);
  if (res[2]!=0) res[2][2]=a0;
  a0=1.;
  if (res[2]!=0) res[2][3]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lat_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lat_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lat_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lat_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lat_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lat_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lat_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void lat_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lat_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int lat_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real lat_expl_vde_forw_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lat_expl_vde_forw_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lat_expl_vde_forw_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lat_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lat_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lat_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
