diff --git a/makefile b/makefile
index 51bfabf..d0ea1eb 100644
--- a/makefile
+++ b/makefile
@@ -1,5 +1,4 @@
 CC=gcc -O2 -Wall
 
 all: limegps.c gpssim.c
-	$(CC) -o LimeGPS limegps.c gpssim.c -lm -lpthread -lLimeSuite
-	
+	$(CC) -o LimeGPS limegps.c gpssim.c -lm -lpthread -lLimeSuite -I../LimeSuite/src -L../LimeSuite/builddir/src -Wl,-rpath="$(PWD)/../LimeSuite/builddir/src"
