name: 'openpilot env setup'

outputs:
  duration:
    description: 'Duration of the setup process in seconds'
    value: ${{ steps.get_duration.outputs.duration }}

runs:
  using: "composite"
  steps:
    - shell: bash
      name: No retries!
      run: |
        if [ "${{ github.run_attempt }}" -gt 1 ]; then
          echo -e "\033[0;31m##################################################"
          echo -e "\033[0;31m    Retries not allowed! Fix the flaky test!      "
          echo -e "\033[0;31m##################################################\033[0m"
          exit 1
        fi

    - id: start_time
      shell: bash
      run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
    - shell: bash
      name: Run setup
      run: ./tools/op.sh setup
    - shell: bash
      name: Add venv to PATH
      run: |
        echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
    - id: get_duration
      shell: bash
      run: |
        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))
        echo "Total duration: $DURATION seconds"
        echo "duration=$DURATION" >> $GITHUB_OUTPUT
