import os
import shutil

Import('env', 'arch', 'messaging', 'common', 'visionipc', 'ffmpeg_libs')

libs = [common, messaging, visionipc] + ffmpeg_libs + ['pthread', 'm']
frameworks = []

src = ['encoder/encoder.cc', 'encoder/jpeg_encoder.cc']
if arch == "larch64":
  src += ['encoder/v4l_encoder.cc']
else:
  src += ['encoder/ffmpeg_encoder.cc']
  if arch == "Darwin":
    frameworks += ['VideoToolbox', 'CoreMedia', 'CoreFoundation', 'CoreVideo']

encoder_lib = env.Library('encoder', src)
libs.insert(0, encoder_lib)

env.Program('encoderd', ['encoderd.cc'], LIBS=libs, FRAMEWORKS=frameworks)

def copy_python_entrypoint(target, source, env):
  del env
  shutil.copyfile(str(source[0]), str(target[0]))
  os.chmod(str(target[0]), 0o755)

env.Command('bootlog', 'bootlog.py', copy_python_entrypoint)
