/*
 * event.h
 *
 */

#ifndef EVENT_H_
#define EVENT_H_

#define EVENT_GROUP_START_FLEXRAY_STATE_MACHINE_BIT ( 1UL << 0UL )
#define EVENT_GROUP_STOP_FLEXRAY_STATE_MACHINE_BIT ( 1UL << 1UL )

#define EVENT_GROUP_FLEXRAY_STATE_MACHINE_STARTED_BIT ( 1UL << 0UL )
#define EVENT_GROUP_FLEXRAY_STATE_MACHINE_STOPPED_BIT ( 1UL << 1UL )

#endif /* EVENT_H_ */
