#ifndef FLEXRAY_REGISTERS_H_
#define FLEXRAY_REGISTERS_H_

#ifdef __cplusplus
extern "C"{
#endif

#define FR_MCR_OFFSET		((uint16_t)0x0001U)
#define FR_SYMBADHR_OFFSET	((uint16_t)0x0002U)
#define FR_SYMBADLR_OFFSET	((uint16_t)0x0003U)
#define FR_MVR_OFFSET		((uint16_t)0x0000U)
#define FR_MBDSR_OFFSET                                                   ((uint16_t)0x0006U)
#define FR_MBSSUTR_OFFSET                                                 ((uint16_t)0x0007U)
#define FR_POCR_OFFSET                                                    ((uint16_t)0x000AU)
#define FR_GIFER_OFFSET                                                   ((uint16_t)0x000BU)
#define FR_PIFR0_OFFSET                                                   ((uint16_t)0x000CU)
#define FR_PIFR1_OFFSET                                                   ((uint16_t)0x000DU)
#define FR_PIER0_OFFSET                                                   ((uint16_t)0x000EU)
#define FR_PIER1_OFFSET                                                   ((uint16_t)0x000FU)
#define FR_CHIERFR_OFFSET                                                 ((uint16_t)0x0010U)
#define FR_MBIVEC_OFFSET                                                  ((uint16_t)0x0011U)
#define FR_PSR0_OFFSET                                                    ((uint16_t)0x0014U)
#define FR_PSR1_OFFSET                                                    ((uint16_t)0x0015U)
#define FR_PSR2_OFFSET                                                    ((uint16_t)0x0016U)
#define FR_PSR3_OFFSET                                                    ((uint16_t)0x0017U)
#define FR_MTCTR_OFFSET                                                   ((uint16_t)0x0018U)
#define FR_CYCTR_OFFSET                                                   ((uint16_t)0x0019U)
#define FR_RTCORVR_OFFSET                                                 ((uint16_t)0x001CU)
#define FR_OFCORVR_OFFSET                                                 ((uint16_t)0x001DU)
#define FR_SYMATOR_OFFSET                                                 ((uint16_t)0x001FU)
#define FR_SFCNTR_OFFSET                                                  ((uint16_t)0x0020U)
#define FR_SFTOR_OFFSET                                                   ((uint16_t)0x0021U)
#define FR_SFTCCSR_OFFSET                                                 ((uint16_t)0x0022U)
#define FR_NMVLR_OFFSET                                                   ((uint16_t)0x002CU)
#define FR_TICCR_OFFSET                                                   ((uint16_t)0x002DU)
#define FR_TI1CYSR_OFFSET                                                 ((uint16_t)0x002EU)
#define FR_TI1MTOR_OFFSET                                                 ((uint16_t)0x002FU)
#define FR_TI2CR0_OFFSET                                                  ((uint16_t)0x0030U)
#define FR_TI2CR1_OFFSET                                                  ((uint16_t)0x0031U)
#define FR_MTSACFR_OFFSET                                                 ((uint16_t)0x0040U)
#define FR_MTSBCFR_OFFSET                                                 ((uint16_t)0x0041U)
#define FR_RSBIR_OFFSET                                                   ((uint16_t)0x0042U)
#define FR_RFWMSR_OFFSET                                                  ((uint16_t)0x0043U)
#define FR_RFSIR_OFFSET                                                   ((uint16_t)0x0044U)
#define FR_RFDSR_OFFSET                                                   ((uint16_t)0x0045U)
#define FR_RFARIR_OFFSET                                                  ((uint16_t)0x0046U)
#define FR_RFBRIR_OFFSET                                                  ((uint16_t)0x0047U)
#define FR_RFMIDAFVR_OFFSET                                               ((uint16_t)0x0048U)
#define FR_RFMIDAFMR_OFFSET                                               ((uint16_t)0x0049U)
#define FR_RFFIDRFVR_OFFSET                                               ((uint16_t)0x004AU)
#define FR_RFFIDRFMR_OFFSET                                               ((uint16_t)0x004BU)
#define FR_RFRFCFR_OFFSET                                                 ((uint16_t)0x004CU)
#define FR_RFRFCTR_OFFSET                                                 ((uint16_t)0x004DU)
#define FR_PCR0_OFFSET                                                    ((uint16_t)0x0050U)
#define FR_PCR1_OFFSET                                                    ((uint16_t)0x0051U)
#define FR_PCR2_OFFSET                                                    ((uint16_t)0x0052U)
#define FR_PCR3_OFFSET                                                    ((uint16_t)0x0053U)
#define FR_PCR4_OFFSET                                                    ((uint16_t)0x0054U)
#define FR_PCR5_OFFSET                                                    ((uint16_t)0x0055U)
#define FR_PCR6_OFFSET                                                    ((uint16_t)0x0056U)
#define FR_PCR7_OFFSET                                                    ((uint16_t)0x0057U)
#define FR_PCR8_OFFSET                                                    ((uint16_t)0x0058U)
#define FR_PCR9_OFFSET                                                    ((uint16_t)0x0059U)
#define FR_PCR10_OFFSET                                                   ((uint16_t)0x005AU)
#define FR_PCR11_OFFSET                                                   ((uint16_t)0x005BU)
#define FR_PCR12_OFFSET                                                   ((uint16_t)0x005CU)
#define FR_PCR13_OFFSET                                                   ((uint16_t)0x005DU)
#define FR_PCR14_OFFSET                                                   ((uint16_t)0x005EU)
#define FR_PCR15_OFFSET                                                   ((uint16_t)0x005FU)
#define FR_PCR16_OFFSET                                                   ((uint16_t)0x0060U)
#define FR_PCR17_OFFSET                                                   ((uint16_t)0x0061U)
#define FR_PCR18_OFFSET                                                   ((uint16_t)0x0062U)
#define FR_PCR19_OFFSET                                                   ((uint16_t)0x0063U)
#define FR_PCR20_OFFSET                                                   ((uint16_t)0x0064U)
#define FR_PCR21_OFFSET                                                   ((uint16_t)0x0065U)
#define FR_PCR22_OFFSET                                                   ((uint16_t)0x0066U)
#define FR_PCR23_OFFSET                                                   ((uint16_t)0x0067U)
#define FR_PCR24_OFFSET                                                   ((uint16_t)0x0068U)
#define FR_PCR25_OFFSET                                                   ((uint16_t)0x0069U)
#define FR_PCR26_OFFSET                                                   ((uint16_t)0x006AU)
#define FR_PCR27_OFFSET                                                   ((uint16_t)0x006BU)
#define FR_PCR28_OFFSET                                                   ((uint16_t)0x006CU)
#define FR_PCR29_OFFSET                                                   ((uint16_t)0x006DU)
#define FR_PCR30_OFFSET                                                   ((uint16_t)0x006EU)
#define FR_RFSDOR_OFFSET                                                  ((uint16_t)0x0073U)
#define FR_MBCCSR0_OFFSET                                                 ((uint16_t)0x0400U)
#define FR_MBCCFR0_OFFSET                                                 ((uint16_t)0x0401U)
#define FR_MBFIDR0_OFFSET                                                 ((uint16_t)0x0402U)
#define FR_MBIDXR0_OFFSET                                                 ((uint16_t)0x0403U)
#define FR_MBDOR0_OFFSET                                                  ((uint16_t)0x0800U)
#define FR_STBSCR_OFFSET                                                   ((uint16_t)0x0004U)
#define FR_PEDRDR_OFFSET                                                   ((uint16_t)0x0009U)
#define FR_SFIDAFVR_OFFSET                                                 ((uint16_t)0x0024U)
#define FR_SFIDAFMR_OFFSET                                                 ((uint16_t)0x0025U)
#define FR_SSSR_OFFSET                                                     ((uint16_t)0x0032U)
#define FR_SSCCR_OFFSET                                                    ((uint16_t)0x0033U)
#define FR_RFPTR_OFFSET                                                    ((uint16_t)0x0076U)
#define FR_RFFLPCR_OFFSET                                                  ((uint16_t)0x0077U)
#define FR_EERICR_OFFSET                                                   ((uint16_t)0x0079U)
#define FR_EEIAR_OFFSET                                                    ((uint16_t)0x007DU)
#define FR_EEIDR_OFFSET                                                    ((uint16_t)0x007EU)
#define FR_EEICR_OFFSET                                                    ((uint16_t)0x007FU)
#define FR_EEIFER_OFFSET                                                   ((uint16_t)0x0078U)
#define FR_RFSYMBADHR_OFFSET                                               ((uint16_t)0x0074U)
#define FR_RFSYMBADLR_OFFSET                                               ((uint16_t)0x0075U)
#define FR_NMVR0_8BIT                                              ((uint16_t)0x004CU)

#define FR_MCR_MEN_U16                                             ((uint16_t)0x8000U)
#define FR_MCR_SCM_U16                                             ((uint16_t)0x2000U)
#define FR_MCR_CHB_U16                                             ((uint16_t)0x1000U)
#define FR_MCR_CHA_U16                                             ((uint16_t)0x0800U)
#define FR_MCR_SFFE_U16                                            ((uint16_t)0x0400U)
#define FR_MCR_CLKSEL_U16                                          ((uint16_t)0x0010U)
#define FR_MCR_BITRATE_MASK_U16                                    ((uint16_t)0x000EU)
#define FR_SYMBADLR_SMBA_MASK_U16                                  ((uint16_t)0xFFF0U)
#define FR_MBDSR_MBSEG1DS_MASK_U16                                 ((uint16_t)0x007FU)
#define FR_MBDSR_MBSEG2DS_MASK_U16                                 ((uint16_t)0x7F00U)
#define FR_MBSSUTR_LAST_MB_UTIL_MASK_U16                           ((uint16_t)0x007FU)
#define FR_MBSSUTR_LAST_MB_SEG1_MASK_U16                           ((uint16_t)0x7F00U)
#define FR_POCR_WME_U16                                            ((uint16_t)0x8000U)
#define FR_POCR_BSY_U16                                            ((uint16_t)0x0080U)
#define FR_POCR_WMC_U16                                            ((uint16_t)0x0080U)
#define FR_POCR_EOC_ADD_U16                                            ((uint16_t)0x0C00U)
#define FR_POCR_EOC_SUB_U16                                            ((uint16_t)0x0800U)
#define FR_POCR_EOC_DONT_U16                                           ((uint16_t)0x0000U)
#define FR_POCR_ERC_ADD_U16                                            ((uint16_t)0x0300U)
#define FR_POCR_ERC_SUB_U16                                            ((uint16_t)0x0200U)
#define FR_POCR_ERC_DONT_U16                                           ((uint16_t)0x0000U)
#define FR_POCR_CMDALLOWCOLDSTART_U16                                  ((uint16_t)0x0000U)
#define FR_POCR_CMD_ALL_SLOTS_U16                                      ((uint16_t)0x0001U)
#define FR_POCR_CMD_CONFIG_U16                                         ((uint16_t)0x0002U)
#define FR_POCR_CMD_FREEZE_U16                                         ((uint16_t)0x0003U)
#define FR_POCR_CMDCONFIGCOMPLETE_U16                                  ((uint16_t)0x0004U)
#define FR_POCR_CMD_RUN_U16                                            ((uint16_t)0x0005U)
#define FR_POCR_CMD_DEFAULTCONFIG_U16                                  ((uint16_t)0x0006U)
#define FR_POCR_CMD_HALT_U16                                           ((uint16_t)0x0007U)
#define FR_POCR_CMD_WAKEUP_U16                                         ((uint16_t)0x0008U)
#define FR_GIFER_PRIE_U16                                          ((uint16_t)0x0040U)
#define FR_GIFER_TBIF_U16                                          ((uint16_t)0x0100U)
#define FR_GIFER_RBIF_U16                                          ((uint16_t)0x0200U)
#define FR_GIFER_FAFAIF_U16                                        ((uint16_t)0x0400U)
#define FR_GIFER_FAFBIF_U16                                        ((uint16_t)0x0800U)
#define FR_GIFER_WUPIF_U16                                         ((uint16_t)0x1000U)
#define FR_GIFER_INT_FLAGS_MASK_U16                                ((uint16_t)0xFF00U)
#define FR_GIFER_CTRL_FLAGS_MASK_U16                               ((uint16_t)0x00FFU)

#define FR_PIFR0_TI1_IF_U16 ((uint16_t)0x0002U)
#define FR_PIFR0_TI2_IF_U16 ((uint16_t)0x0004U)
#define FR_PIFR0_TBVA_IF_U16 ((uint16_t)0x0008U)
#define FR_PIFR0_TBVB_IF_U16 ((uint16_t)0x0010U)
#define FR_PIFR0_LTXA_IF_U16 ((uint16_t)0x0020U)
#define FR_PIFR0_LTXB_IF_U16 ((uint16_t)0x0040U)
#define FR_PIER0_CCL_IF_U16	((uint16_t)0x0200U)
#define FR_PIFR0_MOC_IF_U16 ((uint16_t)0x0400U)
#define FR_PIFR0_MRC_IF_U16 ((uint16_t)0x0800U)
#define FR_PIFR0_INTL_IF_U16 ((uint16_t)0x4000U)

#define FR_PIER0_TI2_IE_U16                                        ((uint16_t)0x0004U)
#define FR_PIER0_TI1_IE_U16                                        ((uint16_t)0x0002U)
#define FR_PSR0_ERRMODE_MASK_U16                                   ((uint16_t)0xC000U)
#define FR_PSR0_SLOTMODE_MASK_U16                                  ((uint16_t)0x3000U)
#define FR_PSR0_PROTSTATE_MASK_U16                                 ((uint16_t)0x0700U)
#define FR_PSR0_STARTUP_MASK_U16                                   ((uint16_t)0x00F0U)
#define FR_PSR0_WUP_MASK_U16                                       ((uint16_t)0x0007U)
#define FR_PSR0_SLOTMODE_SINGLE_U16                                    ((uint16_t)0x0000U)
#define FR_PSR0_SLOTMODE_ALL_PENDING_U16                               ((uint16_t)0x1000U)
#define FR_PSR0_SLOTMODE_ALL_U16                                       ((uint16_t)0x2000U)
#define FR_PSR0_ERRMODE_ACTIVE_U16                                     ((uint16_t)0x0000U)
#define FR_PSR0_ERRMODE_PASSIVE_U16                                    ((uint16_t)0x4000U)
#define FR_PSR0_ERRMODE_COMM_HALT_U16                                  ((uint16_t)0x8000U)
#define FR_PSR0_PROTSTATE_DEFAULT_CONFIG_U16                           ((uint16_t)0x0000U)
#define FR_PSR0_PROTSTATE_CONFIG_U16                                   ((uint16_t)0x0100U)
#define FR_PSR0_PROTSTATE_WAKEUP_U16                                   ((uint16_t)0x0200U)
#define FR_PSR0_PROTSTATE_READY_U16                                    ((uint16_t)0x0300U)
#define FR_PSR0_PROTSTATE_NORMAL_PASSIVE_U16                           ((uint16_t)0x0400U)
#define FR_PSR0_PROTSTATE_NORMAL_ACTIVE_U16                            ((uint16_t)0x0500U)
#define FR_PSR0_PROTSTATE_HALT_U16                                     ((uint16_t)0x0600U)
#define FR_PSR0_PROTSTATE_STARTUP_U16                                  ((uint16_t)0x0700U)
#define FR_PSR0_STARTUP_CCR_U16                                        ((uint16_t)0x0020U)
#define FR_PSR0_STARTUP_CL_U16                                         ((uint16_t)0x0030U)
#define FR_PSR0_STARTUP_ICOC_U16                                       ((uint16_t)0x0040U)
#define FR_PSR0_STARTUP_IL_U16                                         ((uint16_t)0x0050U)
#define FR_PSR0_STARTUP_IS_U16                                         ((uint16_t)0x0070U)
#define FR_PSR0_STARTUP_CCC_U16                                        ((uint16_t)0x00A0U)
#define FR_PSR0_STARTUP_ICLC_U16                                       ((uint16_t)0x00D0U)
#define FR_PSR0_STARTUP_CG_U16                                         ((uint16_t)0x00E0U)
#define FR_PSR0_STARTUP_CJ_U16                                         ((uint16_t)0x00F0U)

#define FR_PSR0_WUP_UD_U16                                             ((uint16_t)0x0000U)
#define FR_PSR0_WUP_RH_U16                                             ((uint16_t)0x0001U)
#define FR_PSR0_WUP_RW_U16                                             ((uint16_t)0x0002U)
#define FR_PSR0_WUP_HC_U16                                             ((uint16_t)0x0003U)
#define FR_PSR0_WUP_WC_U16                                             ((uint16_t)0x0004U)
#define FR_PSR0_WUP_UC_U16                                             ((uint16_t)0x0005U)
#define FR_PSR0_WUP_T_U16                                              ((uint16_t)0x0006U)
#define FR_PSR0_WUP_RESERVED_U16                                       ((uint16_t)0x0007U)

#define FR_PSR1_CPN_U16                                            ((uint16_t)0x0080U)
#define FR_PSR1_HHR_U16                                            ((uint16_t)0x0040U)
#define FR_PSR1_FRZ_U16                                            ((uint16_t)0x0020U)
/* FR_PSR3 bitfields */
#define FR_PSR3_CHB_MASK_U16                                       ((uint16_t)0x1F00U)
#define FR_PSR3_CHA_MASK_U16                                       ((uint16_t)0x001FU)
#define FR_PSR3_WUB_U16                                            ((uint16_t)0x2000U)
#define FR_PSR3_WUA_U16                                            ((uint16_t)0x0020U)
/* FR_SFTCCSR bitfields */                                              
#define FR_SFTCCSR_SIDEN_U16                                       ((uint16_t)0x0001U)
#define FR_SFTCCSR_SDVEN_U16                                       ((uint16_t)0x0002U)
#define FR_SFTCCSR_ELKT_U16                                        ((uint16_t)0x8000U)
#define FR_SFTCCSR_OLKT_U16                                        ((uint16_t)0x4000U)
#define FR_SFTCCSR_ELKS_U16                                        ((uint16_t)0x0080U)
#define FR_SFTCCSR_OLKS_U16                                        ((uint16_t)0x0040U)
#define FR_SFTCCSR_EVAL_U16                                        ((uint16_t)0x0020U)
#define FR_SFTCCSR_OVAL_U16                                        ((uint16_t)0x0010U)

#define FR_NMVLR_MASK_U16                                          ((uint16_t)0x000FU)

#define FR_TICCR_T2SP_U16                                          ((uint16_t)0x0400U)
#define FR_TICCR_T2TR_U16                                          ((uint16_t)0x0200U)
#define FR_TICCR_T1SP_U16                                          ((uint16_t)0x0004U)
#define FR_TICCR_T1TR_U16                                          ((uint16_t)0x0002U)
#define FR_TICCR_CONFIG_MASK_U16                                   ((uint16_t)0x3010U)

#define FR_TI1CYSR_T1_CYC_MSK_U16                                  ((uint16_t)0x003FU)

#define FR_RSBIR_SEL_RSBIR_A1_U16                                  0x0000U
#define FR_RSBIR_SEL_RSBIR_A2_U16                                  ((uint16_t)0x1000U)
#define FR_RSBIR_SEL_RSBIR_B1_U16                                  ((uint16_t)0x2000U)
#define FR_RSBIR_SEL_RSBIR_B2_U16                                  ((uint16_t)0x3000U)

#define FR_RFWMSR_SEL_U16                                          ((uint16_t)0x0001U)

#define FR_RFSIR_SIDX_MASK_U16                                     ((uint16_t)0x03FFU)

#define FR_RFDSR_ENTRY_SIZE_MASK_U16                               ((uint16_t)0x007FU)

#define FR_RFDSR_FIFO_DEPTH_MASK_U16                               ((uint16_t)0xFF00U)

#define FR_RFRFCFR_IBD_LOWINT_U16                                  0x0000U
#define FR_RFRFCFR_IBD_UPPINT_U16                                  ((uint16_t)0x4000U)
#define FR_RFRFCFR_SEL_F0_U16                                      ((uint16_t)0x0000U)/* range filter 0 */
#define FR_RFRFCFR_SEL_F1_U16                                      ((uint16_t)0x1000U)/* range filter 1 */
#define FR_RFRFCFR_SEL_F2_U16                                      ((uint16_t)0x2000U)/* range filter 2 */
#define FR_RFRFCFR_SEL_F3_U16                                      ((uint16_t)0x3000U)/* range filter 3 */

#define FR_RFRFCFR_SID_MASK_U16                                    ((uint16_t)0x07FFU)

#define FR_RFRFCTR_F3MD_U16                                        ((uint16_t)0x0800U)
#define FR_RFRFCTR_F2MD_U16                                        ((uint16_t)0x0400U)
#define FR_RFRFCTR_F1MD_U16                                        ((uint16_t)0x0200U)
#define FR_RFRFCTR_F0MD_U16                                        ((uint16_t)0x0100U)
#define FR_RFRFCTR_F3EN_U16                                        ((uint16_t)0x0008U)
#define FR_RFRFCTR_F2EN_U16                                        ((uint16_t)0x0004U)
#define FR_RFRFCTR_F1EN_U16                                        ((uint16_t)0x0002U)
#define FR_RFRFCTR_F0EN_U16                                        ((uint16_t)0x0001U)
#define FR_PCR10_WUP_CH_U16                                        ((uint16_t)0x4000U)

#define FR_MBCCSR0_CONFIG_MASK_U16                                 ((uint16_t)0x7900U)
#define FR_MBCCSR_MTD_U16                                          ((uint16_t)0x1000U)
#define FR_MBCCSR_CMT_U16                                          ((uint16_t)0x0800U)
#define FR_MBCCSR_EDT_U16                                          ((uint16_t)0x0400U)
#define FR_MBCCSR_LCKT_U16                                         ((uint16_t)0x0200U)
#define FR_MBCCSR_MBIE_U16                                         ((uint16_t)0x0100U)
#define FR_MBCCSR_DUP_U16                                          ((uint16_t)0x0010U)
#define FR_MBCCSR_EDS_U16                                          ((uint16_t)0x0004U)
#define FR_MBCCSR_LCKS_U16                                         ((uint16_t)0x0002U)
#define FR_MBCCSR_MBIF_U16                                         ((uint16_t)0x0001U)

#define FR_MBCCFR_CHA_U16                                          ((uint16_t)0x4000U)
#define FR_MBCCFR_CHB_U16                                          ((uint16_t)0x2000U)
#define FR_MBCCFR_CCFE_U16                                         ((uint16_t)0x1000U)
#define FR_MBCCFR_CCFVAL_MASK_U16                                  ((uint16_t)0x003FU)
#define FR_MBCCFR_CCFMSK_MASK_U16                                  ((uint16_t)0x0FC0U)
#define FR_MBFIDR_FID_MASK_U16                                     ((uint16_t)0x07FFU)

#define FR_FRAMEHEADER0_PPI_U16                                    ((uint16_t)0x4000U)
#define FR_FRAMEHEADER1_PLDLENMASK_U16                             ((uint16_t)0x007FU)
#define FR_FRAMEHEADER0_FRAME_ID_MASK						((uint16_t)0x07FFU)
#define FR_FRAMEHEADER1_PAYLOAD_LEN_MASK						((uint16_t)0x007FU)

#define FR_PROTECT_SIZE_U32                                            ((uint32_t)0x0008U)
#define FR_RESET_VAL_U16                                                ((uint16_t)0x0000U)
#define FR_RESET_VAL_1_U16                                              ((uint16_t)0x0001U)
#define FR_EERICR_BSY_U16                                               ((uint16_t)0x8000U)
#define FR_MBSSUTR_RESET_VAL_U16                                        ((uint16_t)0xFFFFU)
#define FR_GIFER_RESET_VAL_U16                                          ((uint16_t)0x1C00U)
#define FR_PIFR0_RESET_VAL_U16                                          ((uint16_t)0xFFFFU)
#define FR_PIFR1_RESET_VAL_U16                                          ((uint16_t)0xFF30U)
#define FR_PSR1_RESET_VAL_U16                                           ((uint16_t)0x8000U)
#define FR_PSR3_RESET_VAL_U16                                           ((uint16_t)0x3F3FU)
#define FR_EEIFER_RESET_VAL_U16                                         ((uint16_t)0xFF00U)
#define FR_CHIERFR_RESET_VAL_U16                                        ((uint16_t)0xFFFFU)
#define FR_SYMATOR_RESET_VAL_U16                                        ((uint16_t)0x0006U)
#define FR_NUMBER_PCR_U8                                                ((uint8_t)0x0001FU)

#ifdef __cplusplus
}
#endif

#endif /* FLEXRAY_REGISTERS_H_ */
