#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
ROOT="$(cd "$DIR/../../../" && pwd)"

# Build _cabana
cd "$ROOT"
scons openpilot/tools/cabana/imgui/_cabana openpilot/cereal/messaging/bridge

exec "$DIR/imgui/_cabana" "$@"
