widgets_src = [
  "sunnypilot/qt/widgets/toggle.cc",
  "sunnypilot/qt/widgets/controls.cc",
  "sunnypilot/qt/widgets/scrollview.cc",
]

qt_src = [
  "sunnypilot/ui.cc",
  "sunnypilot/qt/sidebar.cc",
  "sunnypilot/qt/window.cc",
  "sunnypilot/qt/home.cc",
  "sunnypilot/qt/offroad/settings/settings.cc",
  "sunnypilot/qt/offroad/settings/software_panel.cc",
  "sunnypilot/qt/offroad/settings/sunnypilot_panel.cc",
  "sunnypilot/qt/onroad/onroad_home.cc",
]

sunnypilot_panel_qt_src = [
  "sunnypilot/qt/offroad/settings/sunnypilot/mads_settings.cc",
]

sp_widgets_src = widgets_src
sp_qt_src = qt_src + sunnypilot_panel_qt_src

Export('sp_widgets_src', 'sp_qt_src')
