Import('env', 'arch', 'messaging', 'common', 'visionipc')

libs = [common, messaging, visionipc,
        'avformat', 'avcodec', 'swresample', 'avutil', 'x264',
        'pthread', 'z', 'm', 'zstd']
frameworks = []

src = ['logger.cc', 'zstd_writer.cc', 'video_writer.cc', 'encoder/encoder.cc', 'encoder/v4l_encoder.cc', 'encoder/jpeg_encoder.cc']
if arch != "larch64":
  src += ['encoder/ffmpeg_encoder.cc']
  libs += ['yuv']
  if arch == "Darwin":
    frameworks += ['VideoToolbox', 'CoreMedia', 'CoreFoundation', 'CoreVideo']

if arch != "Darwin":
  libs += ['va', 'va-drm', 'drm']

if arch == "Darwin":
  # exclude v4l
  del src[src.index('encoder/v4l_encoder.cc')]

logger_lib = env.Library('logger', src)
libs.insert(0, logger_lib)

bootlog_logger = env.Object('bootlog_logger.o', 'logger.cc')
bootlog_zstd_writer = env.Object('bootlog_zstd_writer.o', 'zstd_writer.cc')
loggerd_main = env.Object('loggerd_main.o', 'loggerd.cc')
encoderd_main = env.Object('encoderd_main.o', 'encoderd.cc')

env.Program('loggerd', [loggerd_main], LIBS=libs, FRAMEWORKS=frameworks)
env.Program('encoderd', [encoderd_main], LIBS=libs + ["jpeg"], FRAMEWORKS=frameworks)
env.Program('bootlog', ['bootlog.cc', bootlog_logger, bootlog_zstd_writer], LIBS=libs[1:], FRAMEWORKS=frameworks)

if GetOption('extras'):
  env.Program('tests/test_logger', ['tests/test_runner.cc', 'tests/test_logger.cc', 'tests/test_zstd_writer.cc'], LIBS=libs)
