Import('env', 'arch', 'messaging', 'common', 'visionipc')

libs = [common, messaging, visionipc,
        'avformat', 'avcodec', 'avutil',
        'yuv', 'OpenCL', 'pthread', 'zstd']

src = ['logger.cc', 'zstd_writer.cc', 'video_writer.cc']

if arch == "Darwin":
  # fix OpenCL
  del libs[libs.index('OpenCL')]
  env['FRAMEWORKS'] = ['OpenCL']

logger_lib = env.Library('logger', src)
libs.insert(0, logger_lib)

env.Program('loggerd', ['loggerd.cc'], LIBS=libs)
env.Program('bootlog.cc', LIBS=libs)

if GetOption('extras'):
  env.Program('tests/test_logger', ['tests/test_runner.cc', 'tests/test_logger.cc', 'tests/test_zstd_writer.cc'], LIBS=libs + ['curl', 'crypto'])
