import os

import bootstrap_icons
import imgui
import libusb
from openpilot.common.basedir import BASEDIR

Import('env', 'arch', 'common', 'messaging', 'visionipc', 'cereal', 'replay_lib')

cabana_imgui_env = env.Clone()
cabana_imgui_env["LIBPATH"] += [imgui.MESA_DIR, libusb.LIB_DIR]
cabana_imgui_env["CPPPATH"] += [imgui.INCLUDE_DIR, libusb.INCLUDE_DIR]
cabana_imgui_env["CXXFLAGS"] += [
  "-DGLFW_INCLUDE_NONE",
  '-DCABANA_REPO_ROOT=\'"%s"\'' % os.path.realpath(BASEDIR),
  '-DBOOTSTRAP_ICONS_TTF=\'"%s"\'' % bootstrap_icons.TTF_PATH,
]

# Qt-free core (DBC + streams), shared by the imgui UI and its Catch2 tests.
cabana_core_srcs = [
  "../dbc/dbc.cc",
  "../dbc/dbcfile.cc",
  "../dbc/dbcmanager.cc",
  "../utils/util_core.cc",
  "../settings.cc",
  "../commands.cc",
  "../panda.cc",
  "../streams/abstractstream.cc",
  "../streams/replaystream.cc",
  "../streams/livestream.cc",
  "../streams/pandastream.cc",
  "../streams/devicestream.cc",
]
if arch != "Darwin":
  cabana_core_srcs += ["../streams/socketcanstream.cc"]
cabana_core = cabana_imgui_env.Library("cabana_core", cabana_core_srcs, LIBS=[common])

libs = [cabana_core, replay_lib, common, messaging, visionipc, cereal,
        File(f"{imgui.LIB_DIR}/libimgui.a"), File(f"{imgui.LIB_DIR}/libglfw3.a"),
        "avformat", "avcodec", "swresample", "avutil", "x264", "yuv",
        "z", "bz2", "zstd", "zmq", "usb-1.0", "m", "pthread"]
if arch == "Darwin":
  cabana_imgui_env["FRAMEWORKS"] = ["OpenGL", "Cocoa", "IOKit", "CoreFoundation", "CoreVideo"]
else:
  libs += ["GL", "dl", "va", "va-drm", "drm"]

cabana_imgui_env.Program('_cabana_imgui', cabana_imgui_env.Glob('*.cc'), LIBS=libs)

if GetOption('extras'):
  test_env = cabana_imgui_env.Clone()
  opendbc_path = '-DOPENDBC_FILE_PATH=\'"%s"\'' % test_env.Dir('#opendbc/dbc').abspath
  test_env['CXXFLAGS'] += [opendbc_path]
  test_env.Program('test_cabana_core', [
    '../tests/test_runner.cc',
    '../tests/test_cabana.cc',
  ], LIBS=libs)
