Import('env', 'arch')

gen = "c_generated_code"

generated_files = [
  f'{gen}/Makefile',

  f'{gen}/main_lat.c',
  f'{gen}/main_sim_lat.c',
  f'{gen}/acados_solver_lat.c',
  f'{gen}/acados_solver_lat.h',
  f'{gen}/acados_sim_solver_lat.c',
  f'{gen}/acados_sim_solver_lat.h',

  f'{gen}/lat_cost/lat_cost_y_0_fun.h',
  f'{gen}/lat_cost/lat_cost_y_0_fun.c',
  f'{gen}/lat_cost/lat_cost_y_0_fun_jac_ut_xt.c',
  f'{gen}/lat_cost/lat_cost_y_e_fun.c',
  f'{gen}/lat_cost/lat_cost_y_e_fun.h',
  f'{gen}/lat_cost/lat_cost_y_e_fun_jac_ut_xt.c',
  f'{gen}/lat_cost/lat_cost_y_fun.c',
  f'{gen}/lat_cost/lat_cost_y_fun.h',
  f'{gen}/lat_cost/lat_cost_y_fun_jac_ut_xt.c',
  f'{gen}/lat_cost/lat_cost_y_0_hess.c',
  f'{gen}/lat_cost/lat_cost_y_e_hess.c',
  f'{gen}/lat_cost/lat_cost_y_y_hess.c',

  f'{gen}/lat_model/lat_model.h',
  f'{gen}/lat_model/lat_expl_ode_fun.c',
  f'{gen}/lat_model/lat_expl_vde_adj.c',
  f'{gen}/lat_model/lat_expl_vde_forw.c',
]

lenv = env.Clone()
lenv["ENV"]["ACADOS_SOURCE_DIR"] = Dir("#phonelibs/acados/acados").abspath

lenv.Clean(generated_files, Dir(gen))

import os
libpath = Dir(f"#phonelibs/acados/{arch}/lib").abspath
lenv["ENV"]["LD_LIBRARY_PATH"] = os.getenv("LD_LIBRARY_PATH", "") + libpath
lenv.Command(generated_files,
             ["lat_mpc.py"],
             f"cd {Dir('.').abspath} && python lat_mpc.py")

lenv.Command(File(f"{gen}/libacados_ocp_solver_lat.so"),
             generated_files,
             f"cd {Dir(gen).abspath} && make ocp_shared_lib")
