blank_issues_enabled: false
contact_links:
  - name: Car bug report
    url: https://github.com/commaai/opendbc/issues/new
    about: For issues with a particular car make or model
  - name: Join the Discord
    url: https://discord.comma.ai
    about: The community Discord is for both openpilot development and experience discussion
  - name: Report driving behavior feedback
    url: https://discord.com/channels/469524606043160576/1254834193066623017
    about: Feedback for the driving and driver monitoring models goes in the #driving-feedback in Discord
  - name: Community Wiki
    url: https://github.com/commaai/openpilot/wiki
    about: Check out our community wiki
