name: Bug Report
description: For issues with running openpilot on your comma device
labels: ["bug"]
body:

  - type: markdown
    attributes:
      value: >
        Before creating a **bug report**, please check the following:
          * Ensure you're running the latest openpilot release.
          * Ensure you're using officially supported hardware. Issues running on PCs have a different issue template.
          * Ensure there isn't an existing issue for your bug. If there is, leave a comment on the existing issue.
          * Ensure you're running stock openpilot. We cannot look into bug reports from forks.

        If you're unsure whether, you've hit a bug, check out the [community Discord server](https://discord.comma.ai).

  - type: textarea
    attributes:
      label: Describe the bug
    validations:
      required: true

  - type: dropdown
    id: hw
    attributes:
      label: What hardware does this issue affect?
      multiple: false
      options:
        - comma three
        - comma two
        - EON Gold

  - type: input
    id: route
    attributes:
      label: Provide a route where the issue occurs
      description: Ensure the route is fully uploaded
      placeholder: 77611a1fac303767|2020-05-11--16-37-07
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: openpilot version
      description: If you're not on the release, provide the commit hash.
      placeholder: 0.8.10
    validations:
      required: true
