name: PC bug report
description: For issues with running openpilot on PC
labels: ["PC"]
body:

  - type: markdown
    attributes:
      value: >
        Before creating a **bug report**, please check the following:
          * Ensure you're running the latest openpilot release.
          * Ensure there isn't an existing issue for your bug. If there is, leave a comment on the existing issue.
          * Ensure you're running stock openpilot. We cannot look into bug reports from forks.

        If you're unsure whether you've hit a bug, check out the #installation-help channel in the [community Discord server](https://discord.comma.ai).

  - type: textarea
    attributes:
      label: Describe the bug
      description: Also include a description of how to reproduce the bug
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      placeholder: Ubuntu 20.04
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: openpilot version or commit
      placeholder: bd36f2ec8d3559909678eff2690c10a520938367
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional info

