Import('env')
lenv = env.Clone()
lenv['CPPPATH'] += ['include']
lenv['LIBPATH'] += ['/system/vendor/lib64']
lenv['CFLAGS'] += ' -DQCOM'
lenv['CXXFLAGS'] += ' -DQCOM -U __ANDROID__'
lenv.Program(['visiond.cc', 'model.c', 'transform.c', 'loadyuv.c', 'buffering.c', 'efd.c',
             'yuvmodel.c', 'temporalmodel.c', 'monitoring.c', 'monitoringmodel.c', 'clutil.c',
             'camera_qcom.c', 'visionbuf_ion.c'],
             LIBS=['zmq', 'czmq', 'capnp', 'capnp_c', 'kj', 'yaml-cpp', 'z', 'curl',
                   'gsl', 'CB', 'OpenCL',
                   'opencv_video', 'opencv_imgproc', 'opencv_core',
                   'gnustl_shared', 'log', 'cutils',
                   'yuv',
                   'common', 'cereal',
                  ])

