[package]
name = "remu"
version = "0.1.0"
edition = "2021"
rust-version = "1.80.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
half = { version = "2.3.1", features = ["num-traits"] }
num-traits = "0.2.17"

[dev-dependencies]
float-cmp = "0.9.0"
