Import('env', 'cereal', 'messaging', 'common', 'socketmaster')

env.Program('logcatd', 'logcatd_systemd.cc', LIBS=[cereal, socketmaster, messaging, common, 'zmq', 'capnp', 'kj', 'systemd', 'json11'])
