Import('env', 'arch', 'cereal', 'messaging', 'common', 'visionipc')

src = ['loggerd.cc', 'logger.cc']
libs = ['zmq', 'capnp', 'kj', 'z',
  'avformat', 'avcodec', 'swscale', 'avutil',
  'yuv', 'bz2', common, cereal, messaging, visionipc]

if arch in ["aarch64", "larch64"]:
  src += ['encoder.c']
  libs += ['OmxVenc', 'OmxCore']
  if arch == "aarch64":
    libs += ['cutils']
  else:
    libs += ['pthread']
else:
  libs += ['pthread']

env.Program(src, LIBS=libs)
