# TODO: these are also defined in a header
# GPIO pin definitions
# both GPIO_STM_RST_N and GPIO_LTE_RST_N are misnamed, they are high to reset
GPIO_HUB_RST_N = 30
GPIO_UBLOX_RST_N = 32
GPIO_UBLOX_SAFEBOOT_N = 33
GPIO_UBLOX_PWR_EN = 34
GPIO_STM_RST_N = 124
GPIO_STM_BOOT0 = 134

GPIO_LTE_RST_N = 50
GPIO_LTE_PWRKEY = 116
GPIO_LTE_BOOT = 52

GPIO_CAM0_DVDD_EN = 12
GPIO_CAM0_AVDD_EN = 8

