Import('env', 'cereal', 'messaging', 'common')
libs = [cereal, messaging, 'pthread', 'zmq', 'capnp', 'kj', 'common']
env.Program('proclogd', ['proclogd.cc', 'parser.cc'], LIBS=libs)

if GetOption('test'):
  env.Program('tests/test_parser', ['tests/test_parser.cc', 'parser.cc'], LIBS=libs)