#include "common_dbc.h"

namespace {

const Signal sigs_768[] = {
    {
      .name = "SET_ME_XF9",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VEHICLE_SPEED",
      .b1 = 8,
      .b2 = 8,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_769[] = {
    {
      .name = "SET_ME_0F18510",
      .b1 = 0,
      .b2 = 28,
      .bo = 36,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_25A0000",
      .b1 = 28,
      .b2 = 28,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1024[] = {
    {
      .name = "RADAR_STATE",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1072[] = {
    {
      .name = "LONG_DIST",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 14,
      .b2 = 10,
      .bo = 40,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 24,
      .b2 = 12,
      .bo = 28,
      .is_signed = true,
      .factor = 0.03125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1073[] = {
    {
      .name = "LONG_DIST",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 14,
      .b2 = 10,
      .bo = 40,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 24,
      .b2 = 12,
      .bo = 28,
      .is_signed = true,
      .factor = 0.03125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1074[] = {
    {
      .name = "LONG_DIST",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 14,
      .b2 = 10,
      .bo = 40,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 24,
      .b2 = 12,
      .bo = 28,
      .is_signed = true,
      .factor = 0.03125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1075[] = {
    {
      .name = "LONG_DIST",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 14,
      .b2 = 10,
      .bo = 40,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 24,
      .b2 = 12,
      .bo = 28,
      .is_signed = true,
      .factor = 0.03125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1076[] = {
    {
      .name = "LONG_DIST",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 14,
      .b2 = 10,
      .bo = 40,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 24,
      .b2 = 12,
      .bo = 28,
      .is_signed = true,
      .factor = 0.03125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1077[] = {
    {
      .name = "LONG_DIST",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 14,
      .b2 = 10,
      .bo = 40,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 24,
      .b2 = 12,
      .bo = 28,
      .is_signed = true,
      .factor = 0.03125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1078[] = {
    {
      .name = "LONG_DIST",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 14,
      .b2 = 10,
      .bo = 40,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 24,
      .b2 = 12,
      .bo = 28,
      .is_signed = true,
      .factor = 0.03125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1079[] = {
    {
      .name = "LONG_DIST",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 14,
      .b2 = 10,
      .bo = 40,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 24,
      .b2 = 12,
      .bo = 28,
      .is_signed = true,
      .factor = 0.03125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1080[] = {
    {
      .name = "LONG_DIST",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 14,
      .b2 = 10,
      .bo = 40,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 24,
      .b2 = 12,
      .bo = 28,
      .is_signed = true,
      .factor = 0.03125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1081[] = {
    {
      .name = "LONG_DIST",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 14,
      .b2 = 10,
      .bo = 40,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 24,
      .b2 = 12,
      .bo = 28,
      .is_signed = true,
      .factor = 0.03125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1088[] = {
    {
      .name = "LONG_DIST",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 14,
      .b2 = 10,
      .bo = 40,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 24,
      .b2 = 12,
      .bo = 28,
      .is_signed = true,
      .factor = 0.03125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1089[] = {
    {
      .name = "LONG_DIST",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 14,
      .b2 = 10,
      .bo = 40,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 24,
      .b2 = 12,
      .bo = 28,
      .is_signed = true,
      .factor = 0.03125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1090[] = {
    {
      .name = "LONG_DIST",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 14,
      .b2 = 10,
      .bo = 40,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 24,
      .b2 = 12,
      .bo = 28,
      .is_signed = true,
      .factor = 0.03125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1091[] = {
    {
      .name = "LONG_DIST",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 14,
      .b2 = 10,
      .bo = 40,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 24,
      .b2 = 12,
      .bo = 28,
      .is_signed = true,
      .factor = 0.03125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1092[] = {
    {
      .name = "LONG_DIST",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 14,
      .b2 = 10,
      .bo = 40,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 24,
      .b2 = 12,
      .bo = 28,
      .is_signed = true,
      .factor = 0.03125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1093[] = {
    {
      .name = "LONG_DIST",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 14,
      .b2 = 10,
      .bo = 40,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 24,
      .b2 = 12,
      .bo = 28,
      .is_signed = true,
      .factor = 0.03125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "VEHICLE_STATE",
    .address = 0x300,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_768),
    .sigs = sigs_768,
  },
  {
    .name = "VEHICLE_STATE2",
    .address = 0x301,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_769),
    .sigs = sigs_769,
  },
  {
    .name = "RADAR_DIAGNOSTIC",
    .address = 0x400,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1024),
    .sigs = sigs_1024,
  },
  {
    .name = "TRACK_0",
    .address = 0x430,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1072),
    .sigs = sigs_1072,
  },
  {
    .name = "TRACK_1",
    .address = 0x431,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1073),
    .sigs = sigs_1073,
  },
  {
    .name = "TRACK_2",
    .address = 0x432,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1074),
    .sigs = sigs_1074,
  },
  {
    .name = "TRACK_3",
    .address = 0x433,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1075),
    .sigs = sigs_1075,
  },
  {
    .name = "TRACK_4",
    .address = 0x434,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1076),
    .sigs = sigs_1076,
  },
  {
    .name = "TRACK_5",
    .address = 0x435,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1077),
    .sigs = sigs_1077,
  },
  {
    .name = "TRACK_6",
    .address = 0x436,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1078),
    .sigs = sigs_1078,
  },
  {
    .name = "TRACK_7",
    .address = 0x437,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1079),
    .sigs = sigs_1079,
  },
  {
    .name = "TRACK_8",
    .address = 0x438,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1080),
    .sigs = sigs_1080,
  },
  {
    .name = "TRACK_9",
    .address = 0x439,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1081),
    .sigs = sigs_1081,
  },
  {
    .name = "TRACK_10",
    .address = 0x440,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1088),
    .sigs = sigs_1088,
  },
  {
    .name = "TRACK_11",
    .address = 0x441,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1089),
    .sigs = sigs_1089,
  },
  {
    .name = "TRACK_12",
    .address = 0x442,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1090),
    .sigs = sigs_1090,
  },
  {
    .name = "TRACK_13",
    .address = 0x443,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1091),
    .sigs = sigs_1091,
  },
  {
    .name = "TRACK_14",
    .address = 0x444,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1092),
    .sigs = sigs_1092,
  },
  {
    .name = "TRACK_15",
    .address = 0x445,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1093),
    .sigs = sigs_1093,
  },
};

const Val vals[] = {
    {
      .name = "RADAR_STATE",
      .address = 0x400,
      .def_val = "121 OK 110 FAULTED 105 WRONG_CONFIG",
      .sigs = sigs_1024,
    },
};

}

const DBC acura_ilx_2016_nidec = {
  .name = "acura_ilx_2016_nidec",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(acura_ilx_2016_nidec)