#include "common_dbc.h"

namespace {

const Signal sigs_1280[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1281[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1282[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1283[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1284[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1285[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1286[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1287[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1288[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1289[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1290[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1291[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1292[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1293[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1294[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1295[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1296[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1297[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1298[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1299[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1300[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1301[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1302[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1303[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1304[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1305[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1306[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1307[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1308[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1309[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1310[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1311[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1312[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1313[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1314[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1315[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1316[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1317[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1318[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1319[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1320[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1321[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1322[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1323[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1324[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1325[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1326[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1327[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1328[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1329[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1330[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1331[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1332[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1333[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1334[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1335[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1336[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1337[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1338[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1339[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1340[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1341[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1342[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1343[] = {
    {
      .name = "Angle",
      .b1 = 11,
      .b2 = 10,
      .bo = 43,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "X_Rel",
      .b1 = 21,
      .b2 = 11,
      .bo = 32,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_Rel",
      .b1 = 38,
      .b2 = 10,
      .bo = 16,
      .is_signed = true,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "V_Rel",
      .b1 = 51,
      .b2 = 13,
      .bo = 0,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "Object_00",
    .address = 0x500,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1280),
    .sigs = sigs_1280,
  },
  {
    .name = "Object_01",
    .address = 0x501,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1281),
    .sigs = sigs_1281,
  },
  {
    .name = "Object_02",
    .address = 0x502,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1282),
    .sigs = sigs_1282,
  },
  {
    .name = "Object_03",
    .address = 0x503,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1283),
    .sigs = sigs_1283,
  },
  {
    .name = "Object_04",
    .address = 0x504,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1284),
    .sigs = sigs_1284,
  },
  {
    .name = "Object_05",
    .address = 0x505,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1285),
    .sigs = sigs_1285,
  },
  {
    .name = "Object_06",
    .address = 0x506,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1286),
    .sigs = sigs_1286,
  },
  {
    .name = "Object_07",
    .address = 0x507,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1287),
    .sigs = sigs_1287,
  },
  {
    .name = "Object_08",
    .address = 0x508,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1288),
    .sigs = sigs_1288,
  },
  {
    .name = "Object_09",
    .address = 0x509,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1289),
    .sigs = sigs_1289,
  },
  {
    .name = "Object_10",
    .address = 0x50A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1290),
    .sigs = sigs_1290,
  },
  {
    .name = "Object_11",
    .address = 0x50B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1291),
    .sigs = sigs_1291,
  },
  {
    .name = "Object_12",
    .address = 0x50C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1292),
    .sigs = sigs_1292,
  },
  {
    .name = "Object_13",
    .address = 0x50D,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1293),
    .sigs = sigs_1293,
  },
  {
    .name = "Object_14",
    .address = 0x50E,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1294),
    .sigs = sigs_1294,
  },
  {
    .name = "Object_15",
    .address = 0x50F,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1295),
    .sigs = sigs_1295,
  },
  {
    .name = "Object_16",
    .address = 0x510,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1296),
    .sigs = sigs_1296,
  },
  {
    .name = "Object_17",
    .address = 0x511,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1297),
    .sigs = sigs_1297,
  },
  {
    .name = "Object_18",
    .address = 0x512,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1298),
    .sigs = sigs_1298,
  },
  {
    .name = "Object_19",
    .address = 0x513,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1299),
    .sigs = sigs_1299,
  },
  {
    .name = "Object_20",
    .address = 0x514,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1300),
    .sigs = sigs_1300,
  },
  {
    .name = "Object_21",
    .address = 0x515,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1301),
    .sigs = sigs_1301,
  },
  {
    .name = "Object_22",
    .address = 0x516,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1302),
    .sigs = sigs_1302,
  },
  {
    .name = "Object_23",
    .address = 0x517,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1303),
    .sigs = sigs_1303,
  },
  {
    .name = "Object_24",
    .address = 0x518,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1304),
    .sigs = sigs_1304,
  },
  {
    .name = "Object_25",
    .address = 0x519,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1305),
    .sigs = sigs_1305,
  },
  {
    .name = "Object_26",
    .address = 0x51A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1306),
    .sigs = sigs_1306,
  },
  {
    .name = "Object_27",
    .address = 0x51B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1307),
    .sigs = sigs_1307,
  },
  {
    .name = "Object_28",
    .address = 0x51C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1308),
    .sigs = sigs_1308,
  },
  {
    .name = "Object_29",
    .address = 0x51D,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1309),
    .sigs = sigs_1309,
  },
  {
    .name = "Object_30",
    .address = 0x51E,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1310),
    .sigs = sigs_1310,
  },
  {
    .name = "Object_31",
    .address = 0x51F,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1311),
    .sigs = sigs_1311,
  },
  {
    .name = "Object_32",
    .address = 0x520,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1312),
    .sigs = sigs_1312,
  },
  {
    .name = "Object_33",
    .address = 0x521,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1313),
    .sigs = sigs_1313,
  },
  {
    .name = "Object_34",
    .address = 0x522,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1314),
    .sigs = sigs_1314,
  },
  {
    .name = "Object_35",
    .address = 0x523,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1315),
    .sigs = sigs_1315,
  },
  {
    .name = "Object_36",
    .address = 0x524,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1316),
    .sigs = sigs_1316,
  },
  {
    .name = "Object_37",
    .address = 0x525,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1317),
    .sigs = sigs_1317,
  },
  {
    .name = "Object_38",
    .address = 0x526,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1318),
    .sigs = sigs_1318,
  },
  {
    .name = "Object_39",
    .address = 0x527,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1319),
    .sigs = sigs_1319,
  },
  {
    .name = "Object_40",
    .address = 0x528,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1320),
    .sigs = sigs_1320,
  },
  {
    .name = "Object_41",
    .address = 0x529,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1321),
    .sigs = sigs_1321,
  },
  {
    .name = "Object_42",
    .address = 0x52A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1322),
    .sigs = sigs_1322,
  },
  {
    .name = "Object_43",
    .address = 0x52B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1323),
    .sigs = sigs_1323,
  },
  {
    .name = "Object_44",
    .address = 0x52C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1324),
    .sigs = sigs_1324,
  },
  {
    .name = "Object_45",
    .address = 0x52D,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1325),
    .sigs = sigs_1325,
  },
  {
    .name = "Object_46",
    .address = 0x52E,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1326),
    .sigs = sigs_1326,
  },
  {
    .name = "Object_47",
    .address = 0x52F,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1327),
    .sigs = sigs_1327,
  },
  {
    .name = "Object_48",
    .address = 0x530,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1328),
    .sigs = sigs_1328,
  },
  {
    .name = "Object_49",
    .address = 0x531,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1329),
    .sigs = sigs_1329,
  },
  {
    .name = "Object_50",
    .address = 0x532,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1330),
    .sigs = sigs_1330,
  },
  {
    .name = "Object_51",
    .address = 0x533,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1331),
    .sigs = sigs_1331,
  },
  {
    .name = "Object_52",
    .address = 0x534,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1332),
    .sigs = sigs_1332,
  },
  {
    .name = "Object_53",
    .address = 0x535,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1333),
    .sigs = sigs_1333,
  },
  {
    .name = "Object_54",
    .address = 0x536,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1334),
    .sigs = sigs_1334,
  },
  {
    .name = "Object_55",
    .address = 0x537,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1335),
    .sigs = sigs_1335,
  },
  {
    .name = "Object_56",
    .address = 0x538,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1336),
    .sigs = sigs_1336,
  },
  {
    .name = "Object_57",
    .address = 0x539,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1337),
    .sigs = sigs_1337,
  },
  {
    .name = "Object_58",
    .address = 0x53A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1338),
    .sigs = sigs_1338,
  },
  {
    .name = "Object_59",
    .address = 0x53B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1339),
    .sigs = sigs_1339,
  },
  {
    .name = "Object_60",
    .address = 0x53C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1340),
    .sigs = sigs_1340,
  },
  {
    .name = "Object_61",
    .address = 0x53D,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1341),
    .sigs = sigs_1341,
  },
  {
    .name = "Object_62",
    .address = 0x53E,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1342),
    .sigs = sigs_1342,
  },
  {
    .name = "Object_63",
    .address = 0x53F,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1343),
    .sigs = sigs_1343,
  },
};

const Val vals[] = {
};

}

const DBC ford_fusion_2018_adas = {
  .name = "ford_fusion_2018_adas",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(ford_fusion_2018_adas)