#include "common_dbc.h"

namespace {

const Signal sigs_270581760[] = {
    {
      .name = "RightBlinker",
      .b1 = 1,
      .b2 = 1,
      .bo = 62,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LeftBlinker",
      .b1 = 0,
      .b2 = 1,
      .bo = 63,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BlinkerLight",
      .b1 = 30,
      .b2 = 1,
      .bo = 33,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_270598144[] = {
    {
      .name = "VehicleSpeed1",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VehicleSpeed2",
      .b1 = 32,
      .b2 = 16,
      .bo = 16,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_270794752[] = {
    {
      .name = "SteeringWheelAngle",
      .b1 = 32,
      .b2 = 16,
      .bo = 16,
      .is_signed = true,
      .factor = 0.0625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_270860288[] = {
    {
      .name = "BrakeLevel",
      .b1 = 5,
      .b2 = 2,
      .bo = 57,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BrakeSensor",
      .b1 = 8,
      .b2 = 8,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_271360000[] = {
    {
      .name = "MaxRegen",
      .b1 = 11,
      .b2 = 1,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GasPedal",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GearShifter2NotUsed",
      .b1 = 48,
      .b2 = 8,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CruiseControlActive",
      .b1 = 63,
      .b2 = 1,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_271368192[] = {
    {
      .name = "GearShifter",
      .b1 = 22,
      .b2 = 2,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_272629760[] = {
    {
      .name = "ChimeType",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ChimeDuration",
      .b1 = 8,
      .b2 = 8,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ChimeRepeat",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ChimeByte4",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ChimeByte5",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_274923520[] = {
    {
      .name = "DriverDoorOpened",
      .b1 = 7,
      .b2 = 1,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_275480576[] = {
    {
      .name = "WheelSpeedFL",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WheelSpeedRL",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WheelSpeedFR",
      .b1 = 32,
      .b2 = 16,
      .bo = 16,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WheelSpeedRR",
      .b1 = 48,
      .b2 = 16,
      .bo = 0,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_276127744[] = {
    {
      .name = "LKAGapButton",
      .b1 = 6,
      .b2 = 2,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_276135936[] = {
    {
      .name = "CruiseButtons",
      .b1 = 4,
      .b2 = 3,
      .bo = 57,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "BlinkerStatus",
    .address = 0x1020C000,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_270581760),
    .sigs = sigs_270581760,
  },
  {
    .name = "VehicleSpeed",
    .address = 0x10210000,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_270598144),
    .sigs = sigs_270598144,
  },
  {
    .name = "SteeringWheelAngle",
    .address = 0x10240000,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_270794752),
    .sigs = sigs_270794752,
  },
  {
    .name = "BrakePedal",
    .address = 0x10250000,
    .size = 2,
    .num_sigs = ARRAYSIZE(sigs_270860288),
    .sigs = sigs_270860288,
  },
  {
    .name = "GasPedalRegenCruise",
    .address = 0x102CA000,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_271360000),
    .sigs = sigs_271360000,
  },
  {
    .name = "GearShifter",
    .address = 0x102CC000,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_271368192),
    .sigs = sigs_271368192,
  },
  {
    .name = "Chime",
    .address = 0x10400000,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_272629760),
    .sigs = sigs_272629760,
  },
  {
    .name = "DriverDoorStatus",
    .address = 0x10630000,
    .size = 1,
    .num_sigs = ARRAYSIZE(sigs_274923520),
    .sigs = sigs_274923520,
  },
  {
    .name = "WheelSpeed",
    .address = 0x106B8000,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_275480576),
    .sigs = sigs_275480576,
  },
  {
    .name = "CruiseButtons2",
    .address = 0x10756000,
    .size = 1,
    .num_sigs = ARRAYSIZE(sigs_276127744),
    .sigs = sigs_276127744,
  },
  {
    .name = "CruiseButtons",
    .address = 0x10758000,
    .size = 3,
    .num_sigs = ARRAYSIZE(sigs_276135936),
    .sigs = sigs_276135936,
  },
};

const Val vals[] = {
    {
      .name = "BlinkerLight",
      .address = 0x1020C000,
      .def_val = "1 ACTIVE 0 INACTIVE",
      .sigs = sigs_270581760,
    },
    {
      .name = "LeftBlinker",
      .address = 0x1020C000,
      .def_val = "1 ACTIVE 0 INACTIVE",
      .sigs = sigs_270581760,
    },
    {
      .name = "RightBlinker",
      .address = 0x1020C000,
      .def_val = "1 ACTIVE 0 INACTIVE",
      .sigs = sigs_270581760,
    },
    {
      .name = "CruiseControlActive",
      .address = 0x102CA000,
      .def_val = "1 ACTIVE 0 INACTIVE",
      .sigs = sigs_271360000,
    },
    {
      .name = "GearShifter",
      .address = 0x102CC000,
      .def_val = "3 PARK 0 DRIVE/LOW",
      .sigs = sigs_271368192,
    },
    {
      .name = "DriverDoorOpened",
      .address = 0x10630000,
      .def_val = "1 OPENED 0 CLOSED",
      .sigs = sigs_274923520,
    },
    {
      .name = "LKAGapButton",
      .address = 0x10756000,
      .def_val = "2 \?\?\? 1 \?\? 0 NONE",
      .sigs = sigs_276127744,
    },
    {
      .name = "CruiseButtons",
      .address = 0x10758000,
      .def_val = "6 CANCEL 5 MAIN 3 SET 2 RESUME 1 NONE",
      .sigs = sigs_276135936,
    },
};

}

const DBC gm_global_a_lowspeed = {
  .name = "gm_global_a_lowspeed",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(gm_global_a_lowspeed)