#include "common_dbc.h"

namespace {

const Signal sigs_148[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "LAT_ACCEL",
      .b1 = 0,
      .b2 = 10,
      .bo = 54,
      .is_signed = false,
      .factor = -0.035,
      .offset = 17.92,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_ACCEL",
      .b1 = 30,
      .b2 = 10,
      .bo = 24,
      .is_signed = false,
      .factor = -0.035,
      .offset = 17.92,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_228[] = {
    {
      .name = "CHECKSUM",
      .b1 = 36,
      .b2 = 4,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 34,
      .b2 = 2,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "STEER_TORQUE",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X00",
      .b1 = 17,
      .b2 = 7,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_TORQUE_REQUEST",
      .b1 = 16,
      .b2 = 1,
      .bo = 47,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X00_2",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_DOWN_TO_ZERO",
      .b1 = 33,
      .b2 = 1,
      .bo = 30,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_229[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "SET_ME_X04",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X00",
      .b1 = 8,
      .b2 = 8,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X80",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X10",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_232[] = {
    {
      .name = "CHECKSUM",
      .b1 = 52,
      .b2 = 4,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 50,
      .b2 = 2,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "XMISSION_SPEED",
      .b1 = 0,
      .b2 = 14,
      .bo = 50,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "COMPUTER_BRAKE_REQUEST",
      .b1 = 26,
      .b2 = 1,
      .bo = 37,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "COMPUTER_BRAKE",
      .b1 = 32,
      .b2 = 16,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_316[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "CAR_GAS",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_330[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "STEER_ANGLE",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_ANGLE_RATE",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = true,
      .factor = -1.0,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_SENSOR_STATUS_3",
      .b1 = 39,
      .b2 = 1,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_SENSOR_STATUS_2",
      .b1 = 38,
      .b2 = 1,
      .bo = 25,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_SENSOR_STATUS_1",
      .b1 = 37,
      .b2 = 1,
      .bo = 26,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_WHEEL_ANGLE",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_344[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "XMISSION_SPEED",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ENGINE_RPM",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "XMISSION_SPEED2",
      .b1 = 32,
      .b2 = 16,
      .bo = 16,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ODOMETER",
      .b1 = 48,
      .b2 = 8,
      .bo = 8,
      .is_signed = false,
      .factor = 10,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_380[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "PEDAL_GAS",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ENGINE_RPM",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_SWITCH",
      .b1 = 39,
      .b2 = 1,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH_17C",
      .b1 = 34,
      .b2 = 5,
      .bo = 25,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_STATUS",
      .b1 = 33,
      .b2 = 1,
      .bo = 30,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GAS_PRESSED",
      .b1 = 32,
      .b2 = 1,
      .bo = 31,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH2_17C",
      .b1 = 40,
      .b2 = 10,
      .bo = 14,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH3_17C",
      .b1 = 51,
      .b2 = 5,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_PRESSED",
      .b1 = 50,
      .b2 = 1,
      .bo = 13,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_399[] = {
    {
      .name = "CHECKSUM",
      .b1 = 52,
      .b2 = 4,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 50,
      .b2 = 2,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "STEER_TORQUE_SENSOR",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = true,
      .factor = -1.0,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_ANGLE_RATE",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_CONTROL_ACTIVE",
      .b1 = 36,
      .b2 = 1,
      .bo = 27,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_STATUS",
      .b1 = 32,
      .b2 = 4,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_CONFIG_INDEX",
      .b1 = 44,
      .b2 = 4,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_419[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "GEAR_SHIFTER",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GEAR",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_420[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "USER_BRAKE",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 0.015625,
      .offset = -1.609375,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_DISABLED",
      .b1 = 27,
      .b2 = 1,
      .bo = 36,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_HOLD_ENABLED",
      .b1 = 42,
      .b2 = 1,
      .bo = 21,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_HOLD_ACTIVE",
      .b1 = 41,
      .b2 = 1,
      .bo = 22,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_427[] = {
    {
      .name = "CHECKSUM",
      .b1 = 20,
      .b2 = 4,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 18,
      .b2 = 2,
      .bo = 44,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "MOTOR_TORQUE",
      .b1 = 6,
      .b2 = 10,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CONFIG_VALID",
      .b1 = 0,
      .b2 = 1,
      .bo = 63,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "OUTPUT_DISABLED",
      .b1 = 17,
      .b2 = 1,
      .bo = 46,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_432[] = {
    {
      .name = "CHECKSUM",
      .b1 = 52,
      .b2 = 4,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 50,
      .b2 = 2,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "BRAKE_ERROR_2",
      .b1 = 14,
      .b2 = 1,
      .bo = 49,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_ERROR_1",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEELS_MOVING",
      .b1 = 11,
      .b2 = 1,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_450[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "EPB_ACTIVE",
      .b1 = 4,
      .b2 = 1,
      .bo = 59,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "EPB_STATE",
      .b1 = 26,
      .b2 = 2,
      .bo = 36,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_464[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "WHEEL_SPEED_FL",
      .b1 = 0,
      .b2 = 15,
      .bo = 49,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_FR",
      .b1 = 15,
      .b2 = 15,
      .bo = 34,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_RL",
      .b1 = 30,
      .b2 = 15,
      .bo = 19,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_RR",
      .b1 = 45,
      .b2 = 15,
      .bo = 4,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_479[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "GAS_COMMAND",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_TO_0",
      .b1 = 19,
      .b2 = 5,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CONTROL_ON",
      .b1 = 16,
      .b2 = 3,
      .bo = 45,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACCEL_COMMAND",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AEB_STATUS",
      .b1 = 38,
      .b2 = 1,
      .bo = 25,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_REQUEST",
      .b1 = 37,
      .b2 = 1,
      .bo = 26,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STANDSTILL",
      .b1 = 36,
      .b2 = 1,
      .bo = 27,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STANDSTILL_RELEASE",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AEB_PREPARE",
      .b1 = 44,
      .b2 = 1,
      .bo = 19,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AEB_BRAKING",
      .b1 = 40,
      .b2 = 1,
      .bo = 23,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_LIGHTS",
      .b1 = 57,
      .b2 = 1,
      .bo = 6,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_490[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "LAT_ACCEL",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = true,
      .factor = 0.0015,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_ACCEL",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = true,
      .factor = 0.0015,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_495[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "SET_TO_3",
      .b1 = 1,
      .b2 = 7,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CONTROL_ON",
      .b1 = 0,
      .b2 = 1,
      .bo = 63,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_TO_FF",
      .b1 = 8,
      .b2 = 8,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS_BOH",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_TO_75",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_TO_30",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS_BOH2",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_506[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "CHIME",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_545[] = {
    {
      .name = "CHECKSUM",
      .b1 = 44,
      .b2 = 4,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 42,
      .b2 = 2,
      .bo = 20,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "ECON_ON",
      .b1 = 16,
      .b2 = 1,
      .bo = 47,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DRIVE_MODE",
      .b1 = 34,
      .b2 = 2,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_576[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "LINE_ANGLE",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0005,
      .offset = -1.024,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FRAME_INDEX",
      .b1 = 8,
      .b2 = 4,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_OFFSET",
      .b1 = 16,
      .b2 = 12,
      .bo = 36,
      .is_signed = false,
      .factor = 0.004,
      .offset = -8.192,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_DISTANCE_VISIBLE",
      .b1 = 32,
      .b2 = 9,
      .bo = 23,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_PROBABILITY",
      .b1 = 41,
      .b2 = 6,
      .bo = 17,
      .is_signed = false,
      .factor = 0.015625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_577[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "FRAME_INDEX",
      .b1 = 0,
      .b2 = 4,
      .bo = 60,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_SOLID",
      .b1 = 10,
      .b2 = 1,
      .bo = 53,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_DASHED",
      .b1 = 9,
      .b2 = 1,
      .bo = 54,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_CURVATURE",
      .b1 = 16,
      .b2 = 12,
      .bo = 36,
      .is_signed = false,
      .factor = 1e-05,
      .offset = -0.02048,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_PARAMETER",
      .b1 = 32,
      .b2 = 12,
      .bo = 20,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_FAR_EDGE_POSITION",
      .b1 = 48,
      .b2 = 8,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = -128.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_579[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "LINE_ANGLE",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0005,
      .offset = -1.024,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FRAME_INDEX",
      .b1 = 8,
      .b2 = 4,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_OFFSET",
      .b1 = 16,
      .b2 = 12,
      .bo = 36,
      .is_signed = false,
      .factor = 0.004,
      .offset = -8.192,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_DISTANCE_VISIBLE",
      .b1 = 32,
      .b2 = 9,
      .bo = 23,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_PROBABILITY",
      .b1 = 41,
      .b2 = 6,
      .bo = 17,
      .is_signed = false,
      .factor = 0.015625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_580[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "FRAME_INDEX",
      .b1 = 0,
      .b2 = 4,
      .bo = 60,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_SOLID",
      .b1 = 10,
      .b2 = 1,
      .bo = 53,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_DASHED",
      .b1 = 9,
      .b2 = 1,
      .bo = 54,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_CURVATURE",
      .b1 = 16,
      .b2 = 12,
      .bo = 36,
      .is_signed = false,
      .factor = 1e-05,
      .offset = -0.02048,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_PARAMETER",
      .b1 = 32,
      .b2 = 12,
      .bo = 20,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_FAR_EDGE_POSITION",
      .b1 = 48,
      .b2 = 8,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = -128.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_582[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "LINE_ANGLE",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0005,
      .offset = -1.024,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FRAME_INDEX",
      .b1 = 8,
      .b2 = 4,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_OFFSET",
      .b1 = 16,
      .b2 = 12,
      .bo = 36,
      .is_signed = false,
      .factor = 0.004,
      .offset = -8.192,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_DISTANCE_VISIBLE",
      .b1 = 32,
      .b2 = 9,
      .bo = 23,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_PROBABILITY",
      .b1 = 41,
      .b2 = 6,
      .bo = 17,
      .is_signed = false,
      .factor = 0.015625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_583[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "FRAME_INDEX",
      .b1 = 0,
      .b2 = 4,
      .bo = 60,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_SOLID",
      .b1 = 10,
      .b2 = 1,
      .bo = 53,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_DASHED",
      .b1 = 9,
      .b2 = 1,
      .bo = 54,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_CURVATURE",
      .b1 = 16,
      .b2 = 12,
      .bo = 36,
      .is_signed = false,
      .factor = 1e-05,
      .offset = -0.02048,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_PARAMETER",
      .b1 = 32,
      .b2 = 12,
      .bo = 20,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_FAR_EDGE_POSITION",
      .b1 = 48,
      .b2 = 8,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = -128.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_585[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "LINE_ANGLE",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = false,
      .factor = 0.0005,
      .offset = -1.024,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FRAME_INDEX",
      .b1 = 8,
      .b2 = 4,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_OFFSET",
      .b1 = 16,
      .b2 = 12,
      .bo = 36,
      .is_signed = false,
      .factor = 0.004,
      .offset = -8.192,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_DISTANCE_VISIBLE",
      .b1 = 32,
      .b2 = 9,
      .bo = 23,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_PROBABILITY",
      .b1 = 41,
      .b2 = 6,
      .bo = 17,
      .is_signed = false,
      .factor = 0.015625,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_586[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "FRAME_INDEX",
      .b1 = 0,
      .b2 = 4,
      .bo = 60,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_SOLID",
      .b1 = 10,
      .b2 = 1,
      .bo = 53,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_DASHED",
      .b1 = 9,
      .b2 = 1,
      .bo = 54,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_CURVATURE",
      .b1 = 16,
      .b2 = 12,
      .bo = 36,
      .is_signed = false,
      .factor = 1e-05,
      .offset = -0.02048,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_PARAMETER",
      .b1 = 32,
      .b2 = 12,
      .bo = 20,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LINE_FAR_EDGE_POSITION",
      .b1 = 48,
      .b2 = 8,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = -128.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_597[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "WHEEL_SPEED_FL",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_FR",
      .b1 = 8,
      .b2 = 8,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_RL",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_RR",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_TO_X55",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_TO_X55_2",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_COUNTER",
      .b1 = 48,
      .b2 = 8,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_662[] = {
    {
      .name = "CHECKSUM",
      .b1 = 28,
      .b2 = 4,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 26,
      .b2 = 2,
      .bo = 36,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "CRUISE_SETTING",
      .b1 = 4,
      .b2 = 2,
      .bo = 58,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_BUTTONS",
      .b1 = 0,
      .b2 = 3,
      .bo = 61,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_773[] = {
    {
      .name = "CHECKSUM",
      .b1 = 52,
      .b2 = 4,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 50,
      .b2 = 2,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "SEATBELT_DRIVER_LAMP",
      .b1 = 0,
      .b2 = 1,
      .bo = 63,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SEATBELT_PASS_UNLATCHED",
      .b1 = 13,
      .b2 = 1,
      .bo = 50,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SEATBELT_PASS_LATCHED",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SEATBELT_DRIVER_UNLATCHED",
      .b1 = 11,
      .b2 = 1,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SEATBELT_DRIVER_LATCHED",
      .b1 = 10,
      .b2 = 1,
      .bo = 53,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PASS_AIRBAG_OFF",
      .b1 = 9,
      .b2 = 1,
      .bo = 54,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PASS_AIRBAG_ON",
      .b1 = 8,
      .b2 = 1,
      .bo = 55,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_777[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "CAR_SPEED",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ROUGH_CAR_SPEED",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ROUGH_CAR_SPEED_2",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ROUGH_CAR_SPEED_3",
      .b1 = 32,
      .b2 = 16,
      .bo = 16,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LOCK_STATUS",
      .b1 = 48,
      .b2 = 2,
      .bo = 14,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_780[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "ZEROS_BOH",
      .b1 = 0,
      .b2 = 24,
      .bo = 40,
      .is_signed = false,
      .factor = 0.002759506,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_SPEED",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ENABLE_MINI_CAR",
      .b1 = 39,
      .b2 = 1,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RADAR_OBSTRUCTED",
      .b1 = 38,
      .b2 = 1,
      .bo = 25,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FCM_PROBLEM",
      .b1 = 37,
      .b2 = 1,
      .bo = 26,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FCM_OFF",
      .b1 = 36,
      .b2 = 1,
      .bo = 27,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_TO_1",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_PROBLEM",
      .b1 = 34,
      .b2 = 1,
      .bo = 29,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH",
      .b1 = 33,
      .b2 = 1,
      .bo = 30,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DTC_MODE",
      .b1 = 32,
      .b2 = 1,
      .bo = 31,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_CONTROL_LABEL",
      .b1 = 47,
      .b2 = 1,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH_5",
      .b1 = 46,
      .b2 = 1,
      .bo = 17,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH_4",
      .b1 = 45,
      .b2 = 1,
      .bo = 18,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH_3",
      .b1 = 44,
      .b2 = 1,
      .bo = 19,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HUD_LEAD",
      .b1 = 42,
      .b2 = 2,
      .bo = 20,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HUD_DISTANCE",
      .b1 = 40,
      .b2 = 2,
      .bo = 22,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH_6",
      .b1 = 52,
      .b2 = 4,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_ON",
      .b1 = 51,
      .b2 = 1,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "IMPERIAL_UNIT",
      .b1 = 49,
      .b2 = 1,
      .bo = 14,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_TO_X1",
      .b1 = 48,
      .b2 = 1,
      .bo = 15,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_804[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "TRIP_FUEL_CONSUMED",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_806[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "DRIVERS_DOOR_OPEN",
      .b1 = 22,
      .b2 = 1,
      .bo = 41,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CMBS_STATES",
      .b1 = 17,
      .b2 = 2,
      .bo = 45,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LEFT_BLINKER",
      .b1 = 29,
      .b2 = 1,
      .bo = 34,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RIGHT_BLINKER",
      .b1 = 28,
      .b2 = 1,
      .bo = 35,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MAIN_ON",
      .b1 = 27,
      .b2 = 1,
      .bo = 36,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_829[] = {
    {
      .name = "CHECKSUM",
      .b1 = 36,
      .b2 = 4,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 34,
      .b2 = 2,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "SET_ME_X41",
      .b1 = 1,
      .b2 = 7,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH",
      .b1 = 1,
      .b2 = 7,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CAM_TEMP_HIGH",
      .b1 = 0,
      .b2 = 1,
      .bo = 63,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEERING_REQUIRED",
      .b1 = 15,
      .b2 = 1,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_RIGHT",
      .b1 = 14,
      .b2 = 1,
      .bo = 49,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SOLID_LANES",
      .b1 = 13,
      .b2 = 1,
      .bo = 50,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_OFF",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_PROBLEM",
      .b1 = 11,
      .b2 = 1,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DTC",
      .b1 = 10,
      .b2 = 1,
      .bo = 53,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DASHED_LANES",
      .b1 = 9,
      .b2 = 1,
      .bo = 54,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BEEP",
      .b1 = 22,
      .b2 = 2,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_PROBLEM",
      .b1 = 18,
      .b2 = 1,
      .bo = 45,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH",
      .b1 = 16,
      .b2 = 2,
      .bo = 46,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CLEAN_WINDSHIELD",
      .b1 = 29,
      .b2 = 1,
      .bo = 34,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_OFF",
      .b1 = 28,
      .b2 = 1,
      .bo = 35,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_ON",
      .b1 = 27,
      .b2 = 1,
      .bo = 36,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X48",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_862[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "ZEROS_BOH",
      .b1 = 0,
      .b2 = 50,
      .bo = 14,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS_BOH_2",
      .b1 = 52,
      .b2 = 4,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HIGHBEAMS_ON",
      .b1 = 51,
      .b2 = 1,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AUTO_HIGHBEAMS_ACTIVE",
      .b1 = 50,
      .b2 = 1,
      .bo = 13,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_884[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "HIGH_BEAM_FLASH",
      .b1 = 42,
      .b2 = 1,
      .bo = 21,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AUTO_HEADLIGHTS",
      .b1 = 41,
      .b2 = 1,
      .bo = 22,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HIGH_BEAM_HOLD",
      .b1 = 40,
      .b2 = 1,
      .bo = 23,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WIPER_SWITCH",
      .b1 = 50,
      .b2 = 2,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HEADLIGHTS_ON",
      .b1 = 49,
      .b2 = 1,
      .bo = 14,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_891[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "WIPERS",
      .b1 = 22,
      .b2 = 2,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HIGH_BEAMS",
      .b1 = 37,
      .b2 = 1,
      .bo = 26,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LOW_BEAMS",
      .b1 = 36,
      .b2 = 1,
      .bo = 27,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PARK_LIGHTS",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_892[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "CRUISE_SPEED_OFFSET",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = true,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_927[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "ZEROS_BOH",
      .b1 = 0,
      .b2 = 10,
      .bo = 54,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS_BOH2",
      .b1 = 12,
      .b2 = 4,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CMBS_OFF",
      .b1 = 11,
      .b2 = 1,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_TO_1",
      .b1 = 10,
      .b2 = 1,
      .bo = 53,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_ALERTS",
      .b1 = 19,
      .b2 = 5,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RESUME_INSTRUCTION",
      .b1 = 18,
      .b2 = 1,
      .bo = 45,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_TO_0",
      .b1 = 17,
      .b2 = 1,
      .bo = 46,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "APPLY_BRAKES_FOR_CANC",
      .b1 = 16,
      .b2 = 1,
      .bo = 47,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS_BOH3",
      .b1 = 24,
      .b2 = 32,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1029[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "DOOR_OPEN_FL",
      .b1 = 34,
      .b2 = 1,
      .bo = 29,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_FR",
      .b1 = 33,
      .b2 = 1,
      .bo = 30,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_RL",
      .b1 = 32,
      .b2 = 1,
      .bo = 31,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_RR",
      .b1 = 47,
      .b2 = 1,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TRUNK_OPEN",
      .b1 = 46,
      .b2 = 1,
      .bo = 17,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_13274[] = {
    {
      .name = "CHECKSUM",
      .b1 = 36,
      .b2 = 4,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 34,
      .b2 = 2,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "SET_ME_X41",
      .b1 = 1,
      .b2 = 7,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH",
      .b1 = 1,
      .b2 = 7,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CAM_TEMP_HIGH",
      .b1 = 0,
      .b2 = 1,
      .bo = 63,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEERING_REQUIRED",
      .b1 = 15,
      .b2 = 1,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_RIGHT",
      .b1 = 14,
      .b2 = 1,
      .bo = 49,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SOLID_LANES",
      .b1 = 13,
      .b2 = 1,
      .bo = 50,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_OFF",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_PROBLEM",
      .b1 = 11,
      .b2 = 1,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DTC",
      .b1 = 10,
      .b2 = 1,
      .bo = 53,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DASHED_LANES",
      .b1 = 9,
      .b2 = 1,
      .bo = 54,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BEEP",
      .b1 = 22,
      .b2 = 2,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X01",
      .b1 = 19,
      .b2 = 1,
      .bo = 44,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_PROBLEM",
      .b1 = 18,
      .b2 = 1,
      .bo = 45,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH",
      .b1 = 16,
      .b2 = 2,
      .bo = 46,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CLEAN_WINDSHIELD",
      .b1 = 29,
      .b2 = 1,
      .bo = 34,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_OFF",
      .b1 = 28,
      .b2 = 1,
      .bo = 35,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_ON",
      .b1 = 27,
      .b2 = 1,
      .bo = 36,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_13275[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "SET_ME_X41",
      .b1 = 1,
      .b2 = 7,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH",
      .b1 = 1,
      .b2 = 7,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CAM_TEMP_HIGH",
      .b1 = 0,
      .b2 = 1,
      .bo = 63,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEERING_REQUIRED",
      .b1 = 15,
      .b2 = 1,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_RIGHT",
      .b1 = 14,
      .b2 = 1,
      .bo = 49,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SOLID_LANES",
      .b1 = 13,
      .b2 = 1,
      .bo = 50,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_OFF",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_PROBLEM",
      .b1 = 11,
      .b2 = 1,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DTC",
      .b1 = 10,
      .b2 = 1,
      .bo = 53,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DASHED_LANES",
      .b1 = 9,
      .b2 = 1,
      .bo = 54,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BEEP",
      .b1 = 22,
      .b2 = 2,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X01",
      .b1 = 19,
      .b2 = 1,
      .bo = 44,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_PROBLEM",
      .b1 = 18,
      .b2 = 1,
      .bo = 45,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH",
      .b1 = 16,
      .b2 = 2,
      .bo = 46,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CLEAN_WINDSHIELD",
      .b1 = 29,
      .b2 = 1,
      .bo = 34,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_OFF",
      .b1 = 28,
      .b2 = 1,
      .bo = 35,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_ON",
      .b1 = 27,
      .b2 = 1,
      .bo = 36,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "KINEMATICS",
    .address = 0x94,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_148),
    .sigs = sigs_148,
  },
  {
    .name = "STEERING_CONTROL",
    .address = 0xE4,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_228),
    .sigs = sigs_228,
  },
  {
    .name = "BOSCH_SUPPLEMENTAL_1",
    .address = 0xE5,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_229),
    .sigs = sigs_229,
  },
  {
    .name = "BRAKE_HOLD",
    .address = 0xE8,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_232),
    .sigs = sigs_232,
  },
  {
    .name = "GAS_PEDAL_2",
    .address = 0x13C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_316),
    .sigs = sigs_316,
  },
  {
    .name = "STEERING_SENSORS",
    .address = 0x14A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_330),
    .sigs = sigs_330,
  },
  {
    .name = "ENGINE_DATA",
    .address = 0x158,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_344),
    .sigs = sigs_344,
  },
  {
    .name = "POWERTRAIN_DATA",
    .address = 0x17C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_380),
    .sigs = sigs_380,
  },
  {
    .name = "STEER_STATUS",
    .address = 0x18F,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_399),
    .sigs = sigs_399,
  },
  {
    .name = "GEARBOX",
    .address = 0x1A3,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_419),
    .sigs = sigs_419,
  },
  {
    .name = "VSA_STATUS",
    .address = 0x1A4,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_420),
    .sigs = sigs_420,
  },
  {
    .name = "STEER_MOTOR_TORQUE",
    .address = 0x1AB,
    .size = 3,
    .num_sigs = ARRAYSIZE(sigs_427),
    .sigs = sigs_427,
  },
  {
    .name = "STANDSTILL",
    .address = 0x1B0,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_432),
    .sigs = sigs_432,
  },
  {
    .name = "EPB_STATUS",
    .address = 0x1C2,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_450),
    .sigs = sigs_450,
  },
  {
    .name = "WHEEL_SPEEDS",
    .address = 0x1D0,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_464),
    .sigs = sigs_464,
  },
  {
    .name = "ACC_CONTROL",
    .address = 0x1DF,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_479),
    .sigs = sigs_479,
  },
  {
    .name = "VEHICLE_DYNAMICS",
    .address = 0x1EA,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_490),
    .sigs = sigs_490,
  },
  {
    .name = "ACC_CONTROL_ON",
    .address = 0x1EF,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_495),
    .sigs = sigs_495,
  },
  {
    .name = "LEGACY_BRAKE_COMMAND",
    .address = 0x1FA,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_506),
    .sigs = sigs_506,
  },
  {
    .name = "XXX_16",
    .address = 0x221,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_545),
    .sigs = sigs_545,
  },
  {
    .name = "LEFT_LANE_LINE_1",
    .address = 0x240,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_576),
    .sigs = sigs_576,
  },
  {
    .name = "LEFT_LANE_LINE_2",
    .address = 0x241,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_577),
    .sigs = sigs_577,
  },
  {
    .name = "RIGHT_LANE_LINE_1",
    .address = 0x243,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_579),
    .sigs = sigs_579,
  },
  {
    .name = "RIGHT_LANE_LINE_2",
    .address = 0x244,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_580),
    .sigs = sigs_580,
  },
  {
    .name = "ADJACENT_LEFT_LANE_LINE_1",
    .address = 0x246,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_582),
    .sigs = sigs_582,
  },
  {
    .name = "ADJACENT_LEFT_LANE_LINE_2",
    .address = 0x247,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_583),
    .sigs = sigs_583,
  },
  {
    .name = "ADJACENT_RIGHT_LANE_LINE_1",
    .address = 0x249,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_585),
    .sigs = sigs_585,
  },
  {
    .name = "ADJACENT_RIGHT_LANE_LINE_2",
    .address = 0x24A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_586),
    .sigs = sigs_586,
  },
  {
    .name = "ROUGH_WHEEL_SPEED",
    .address = 0x255,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_597),
    .sigs = sigs_597,
  },
  {
    .name = "SCM_BUTTONS",
    .address = 0x296,
    .size = 4,
    .num_sigs = ARRAYSIZE(sigs_662),
    .sigs = sigs_662,
  },
  {
    .name = "SEATBELT_STATUS",
    .address = 0x305,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_773),
    .sigs = sigs_773,
  },
  {
    .name = "CAR_SPEED",
    .address = 0x309,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_777),
    .sigs = sigs_777,
  },
  {
    .name = "ACC_HUD",
    .address = 0x30C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_780),
    .sigs = sigs_780,
  },
  {
    .name = "CRUISE",
    .address = 0x324,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_804),
    .sigs = sigs_804,
  },
  {
    .name = "SCM_FEEDBACK",
    .address = 0x326,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_806),
    .sigs = sigs_806,
  },
  {
    .name = "LKAS_HUD",
    .address = 0x33D,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_829),
    .sigs = sigs_829,
  },
  {
    .name = "CAMERA_MESSAGES",
    .address = 0x35E,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_862),
    .sigs = sigs_862,
  },
  {
    .name = "STALK_STATUS",
    .address = 0x374,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_884),
    .sigs = sigs_884,
  },
  {
    .name = "STALK_STATUS_2",
    .address = 0x37B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_891),
    .sigs = sigs_891,
  },
  {
    .name = "CRUISE_PARAMS",
    .address = 0x37C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_892),
    .sigs = sigs_892,
  },
  {
    .name = "RADAR_HUD",
    .address = 0x39F,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_927),
    .sigs = sigs_927,
  },
  {
    .name = "DOORS_STATUS",
    .address = 0x405,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1029),
    .sigs = sigs_1029,
  },
  {
    .name = "LKAS_HUD_A",
    .address = 0x33DA,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_13274),
    .sigs = sigs_13274,
  },
  {
    .name = "LKAS_HUD_B",
    .address = 0x33DB,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_13275),
    .sigs = sigs_13275,
  },
};

const Val vals[] = {
    {
      .name = "STEER_STATUS",
      .address = 0x18F,
      .def_val = "6 TMP_FAULT 5 FAULT_1 4 NO_TORQUE_ALERT_2 3 LOW_SPEED_LOCKOUT 2 NO_TORQUE_ALERT_1 0 NORMAL",
      .sigs = sigs_399,
    },
    {
      .name = "GEAR",
      .address = 0x1A3,
      .def_val = "26 S 20 D 19 N 18 R 17 P",
      .sigs = sigs_419,
    },
    {
      .name = "GEAR_SHIFTER",
      .address = 0x1A3,
      .def_val = "2 S 32 D 16 N 8 R 4 P",
      .sigs = sigs_419,
    },
    {
      .name = "ECON_ON_2",
      .address = 0x221,
      .def_val = "0 OFF 3 ON",
      .sigs = sigs_545,
    },
    {
      .name = "CRUISE_BUTTONS",
      .address = 0x296,
      .def_val = "7 TBD 6 TBD 5 TBD 4 ACCEL_RES 3 DECEL_SET 2 CANCEL 1 MAIN 0 NONE",
      .sigs = sigs_662,
    },
    {
      .name = "CRUISE_SETTING",
      .address = 0x296,
      .def_val = "3 DISTANCE_ADJ 2 TBD 1 LKAS_BUTTON 0 NONE",
      .sigs = sigs_662,
    },
    {
      .name = "CMBS_BUTTON",
      .address = 0x326,
      .def_val = "3 PRESSED 0 RELEASED",
      .sigs = sigs_806,
    },
    {
      .name = "BEEP",
      .address = 0x33D,
      .def_val = "3 SINGLE_BEEP 2 TRIPLE_BEEP 1 REPEATED_BEEP 0 NO_BEEP",
      .sigs = sigs_829,
    },
    {
      .name = "WIPERS",
      .address = 0x37B,
      .def_val = "4 HIGH 2 LOW 0 OFF",
      .sigs = sigs_891,
    },
};

}

const DBC honda_civic_sedan_16_diesel_2019_can_generated = {
  .name = "honda_civic_sedan_16_diesel_2019_can_generated",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(honda_civic_sedan_16_diesel_2019_can_generated)