#include "common_dbc.h"

namespace {

const Signal sigs_57[] = {
    {
      .name = "CHECKSUM",
      .b1 = 20,
      .b2 = 4,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 18,
      .b2 = 2,
      .bo = 44,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
};
const Signal sigs_148[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "LAT_ACCEL",
      .b1 = 0,
      .b2 = 10,
      .bo = 54,
      .is_signed = false,
      .factor = 0.02,
      .offset = -512.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LONG_ACCEL",
      .b1 = 31,
      .b2 = 9,
      .bo = 24,
      .is_signed = true,
      .factor = -0.02,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_228[] = {
    {
      .name = "CHECKSUM",
      .b1 = 36,
      .b2 = 4,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 34,
      .b2 = 2,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "STEER_TORQUE",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X00",
      .b1 = 17,
      .b2 = 7,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_TORQUE_REQUEST",
      .b1 = 16,
      .b2 = 1,
      .bo = 47,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X00_2",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_304[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "ENGINE_TORQUE_ESTIMATE",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ENGINE_TORQUE_REQUEST",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CAR_GAS",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_330[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "STEER_ANGLE",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_ANGLE_RATE",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = true,
      .factor = -1.0,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_ANGLE_OFFSET",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_WHEEL_ANGLE",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_344[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "XMISSION_SPEED",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 0.002759506,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ENGINE_RPM",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "XMISSION_SPEED2",
      .b1 = 32,
      .b2 = 16,
      .bo = 16,
      .is_signed = false,
      .factor = 0.002759506,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TRIP_DISTANCE",
      .b1 = 48,
      .b2 = 8,
      .bo = 8,
      .is_signed = false,
      .factor = 0.010588,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_380[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "PEDAL_GAS",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ENGINE_RPM",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_SWITCH",
      .b1 = 39,
      .b2 = 1,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH_17C",
      .b1 = 34,
      .b2 = 5,
      .bo = 25,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_STATUS",
      .b1 = 33,
      .b2 = 1,
      .bo = 30,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GAS_PRESSED",
      .b1 = 32,
      .b2 = 1,
      .bo = 31,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH2_17C",
      .b1 = 40,
      .b2 = 10,
      .bo = 14,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH3_17C",
      .b1 = 51,
      .b2 = 5,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_PRESSED",
      .b1 = 50,
      .b2 = 1,
      .bo = 13,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_399[] = {
    {
      .name = "CHECKSUM",
      .b1 = 52,
      .b2 = 4,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 50,
      .b2 = 2,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "STEER_TORQUE_SENSOR",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = true,
      .factor = -1.0,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_TORQUE_MOTOR",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = true,
      .factor = -1.0,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_CONTROL_ACTIVE",
      .b1 = 36,
      .b2 = 1,
      .bo = 27,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_STATUS",
      .b1 = 32,
      .b2 = 4,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_401[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "GEAR_SHIFTER",
      .b1 = 2,
      .b2 = 6,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GEAR",
      .b1 = 44,
      .b2 = 4,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_419[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "GEAR",
      .b1 = 26,
      .b2 = 6,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GEAR_SHIFTER",
      .b1 = 37,
      .b2 = 3,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_420[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "USER_BRAKE",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 0.015625,
      .offset = -1.609375,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_DISABLED",
      .b1 = 27,
      .b2 = 1,
      .bo = 36,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_HOLD_ENABLED",
      .b1 = 42,
      .b2 = 1,
      .bo = 21,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_HOLD_ACTIVE",
      .b1 = 41,
      .b2 = 1,
      .bo = 22,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_427[] = {
    {
      .name = "CHECKSUM",
      .b1 = 20,
      .b2 = 4,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 18,
      .b2 = 2,
      .bo = 44,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
};
const Signal sigs_428[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
};
const Signal sigs_432[] = {
    {
      .name = "CHECKSUM",
      .b1 = 52,
      .b2 = 4,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 50,
      .b2 = 2,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "CONTROLLED_STANDSTILL",
      .b1 = 7,
      .b2 = 1,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_ERROR_2",
      .b1 = 14,
      .b2 = 1,
      .bo = 49,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_ERROR_1",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEELS_MOVING",
      .b1 = 11,
      .b2 = 1,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_450[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "EPB_ACTIVE",
      .b1 = 4,
      .b2 = 1,
      .bo = 59,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "EPB_STATE",
      .b1 = 26,
      .b2 = 2,
      .bo = 36,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_464[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "WHEEL_SPEED_FL",
      .b1 = 0,
      .b2 = 15,
      .bo = 49,
      .is_signed = false,
      .factor = 0.002759506,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_FR",
      .b1 = 15,
      .b2 = 15,
      .bo = 34,
      .is_signed = false,
      .factor = 0.002759506,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_RL",
      .b1 = 30,
      .b2 = 15,
      .bo = 19,
      .is_signed = false,
      .factor = 0.002759506,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_RR",
      .b1 = 45,
      .b2 = 15,
      .bo = 4,
      .is_signed = false,
      .factor = 0.002759506,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_476[] = {
    {
      .name = "CHECKSUM",
      .b1 = 52,
      .b2 = 4,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 50,
      .b2 = 2,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
};
const Signal sigs_487[] = {
    {
      .name = "CHECKSUM",
      .b1 = 28,
      .b2 = 4,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 26,
      .b2 = 2,
      .bo = 36,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "BRAKE_PRESSURE1",
      .b1 = 0,
      .b2 = 10,
      .bo = 54,
      .is_signed = false,
      .factor = 0.015625,
      .offset = -103.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_PRESSURE2",
      .b1 = 14,
      .b2 = 10,
      .bo = 40,
      .is_signed = false,
      .factor = 0.015625,
      .offset = -103.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_490[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "LONG_ACCEL",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = true,
      .factor = 0.0015384,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_493[] = {
    {
      .name = "CHECKSUM",
      .b1 = 36,
      .b2 = 4,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 34,
      .b2 = 2,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
};
const Signal sigs_506[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "COMPUTER_BRAKE_REQUEST",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_CANCEL_CMD",
      .b1 = 22,
      .b2 = 1,
      .bo = 41,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_FAULT_CMD",
      .b1 = 21,
      .b2 = 1,
      .bo = 42,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_BOH3",
      .b1 = 20,
      .b2 = 1,
      .bo = 43,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_OVERRIDE",
      .b1 = 19,
      .b2 = 1,
      .bo = 44,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_BOH2",
      .b1 = 16,
      .b2 = 3,
      .bo = 45,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_0X80",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_STATES",
      .b1 = 33,
      .b2 = 7,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BRAKE_LIGHTS",
      .b1 = 32,
      .b2 = 1,
      .bo = 31,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FCW2",
      .b1 = 47,
      .b2 = 1,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS_BOH3",
      .b1 = 45,
      .b2 = 2,
      .bo = 17,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FCW",
      .b1 = 44,
      .b2 = 1,
      .bo = 19,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS_BOH6",
      .b1 = 43,
      .b2 = 1,
      .bo = 20,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHIME",
      .b1 = 40,
      .b2 = 3,
      .bo = 21,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "COMPUTER_BRAKE",
      .b1 = 48,
      .b2 = 10,
      .bo = 6,
      .is_signed = false,
      .factor = 0.003906248,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_512[] = {
    {
      .name = "CHECKSUM",
      .b1 = 20,
      .b2 = 4,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 18,
      .b2 = 2,
      .bo = 44,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "GAS_COMMAND",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 0.253984064,
      .offset = -83.3,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_513[] = {
    {
      .name = "CHECKSUM",
      .b1 = 36,
      .b2 = 4,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 34,
      .b2 = 2,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "INTERCEPTOR_GAS",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 0.253984064,
      .offset = -83.3,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "INTERCEPTOR_GAS2",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = false,
      .factor = 0.126992032,
      .offset = -83.3,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_545[] = {
    {
      .name = "CHECKSUM",
      .b1 = 36,
      .b2 = 4,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 34,
      .b2 = 2,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "ECON_ON",
      .b1 = 16,
      .b2 = 1,
      .bo = 47,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_597[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "WHEEL_SPEED_FL",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_FR",
      .b1 = 8,
      .b2 = 8,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_RL",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WHEEL_SPEED_RR",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_TO_X55",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_662[] = {
    {
      .name = "CHECKSUM",
      .b1 = 28,
      .b2 = 4,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 26,
      .b2 = 2,
      .bo = 36,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "CRUISE_SETTING",
      .b1 = 4,
      .b2 = 2,
      .bo = 58,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_BUTTONS",
      .b1 = 0,
      .b2 = 3,
      .bo = 61,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_773[] = {
    {
      .name = "CHECKSUM",
      .b1 = 52,
      .b2 = 4,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 50,
      .b2 = 2,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "SEATBELT_DRIVER_LAMP",
      .b1 = 0,
      .b2 = 1,
      .bo = 63,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SEATBELT_PASS_UNLATCHED",
      .b1 = 13,
      .b2 = 1,
      .bo = 50,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SEATBELT_PASS_LATCHED",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SEATBELT_DRIVER_UNLATCHED",
      .b1 = 11,
      .b2 = 1,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SEATBELT_DRIVER_LATCHED",
      .b1 = 10,
      .b2 = 1,
      .bo = 53,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PASS_AIRBAG_OFF",
      .b1 = 9,
      .b2 = 1,
      .bo = 54,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PASS_AIRBAG_ON",
      .b1 = 8,
      .b2 = 1,
      .bo = 55,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_777[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "DOORS_UNLOCKED",
      .b1 = 49,
      .b2 = 1,
      .bo = 14,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOORS_LOCKED",
      .b1 = 48,
      .b2 = 1,
      .bo = 15,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_780[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "PCM_SPEED",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 0.002759506,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS_BOH",
      .b1 = 23,
      .b2 = 1,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PCM_GAS",
      .b1 = 16,
      .b2 = 7,
      .bo = 41,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_SPEED",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ENABLE_MINI_CAR",
      .b1 = 39,
      .b2 = 1,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RADAR_OBSTRUCTED",
      .b1 = 38,
      .b2 = 1,
      .bo = 25,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FCM_PROBLEM",
      .b1 = 37,
      .b2 = 1,
      .bo = 26,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH_2",
      .b1 = 36,
      .b2 = 1,
      .bo = 27,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FCM_OFF",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_PROBLEM",
      .b1 = 34,
      .b2 = 1,
      .bo = 29,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH",
      .b1 = 33,
      .b2 = 1,
      .bo = 30,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DTC_MODE",
      .b1 = 32,
      .b2 = 1,
      .bo = 31,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_CONTROL_LABEL",
      .b1 = 47,
      .b2 = 1,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH_5",
      .b1 = 46,
      .b2 = 1,
      .bo = 17,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH_4",
      .b1 = 45,
      .b2 = 1,
      .bo = 18,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH_3",
      .b1 = 44,
      .b2 = 1,
      .bo = 19,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HUD_LEAD",
      .b1 = 42,
      .b2 = 2,
      .bo = 20,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HUD_DISTANCE",
      .b1 = 40,
      .b2 = 2,
      .bo = 22,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_795[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
};
const Signal sigs_800[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
};
const Signal sigs_804[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "HUD_SPEED_KPH",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HUD_SPEED_MPH",
      .b1 = 8,
      .b2 = 8,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TRIP_FUEL_CONSUMED",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_SPEED_PCM",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH2",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH3",
      .b1 = 48,
      .b2 = 8,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_806[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "REVERSE_LIGHT",
      .b1 = 21,
      .b2 = 1,
      .bo = 42,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CMBS_BUTTON",
      .b1 = 17,
      .b2 = 2,
      .bo = 45,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LEFT_BLINKER",
      .b1 = 29,
      .b2 = 1,
      .bo = 34,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RIGHT_BLINKER",
      .b1 = 28,
      .b2 = 1,
      .bo = 35,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MAIN_ON",
      .b1 = 27,
      .b2 = 1,
      .bo = 36,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_808[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
};
const Signal sigs_829[] = {
    {
      .name = "CHECKSUM",
      .b1 = 36,
      .b2 = 4,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 34,
      .b2 = 2,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "CAM_TEMP_HIGH",
      .b1 = 0,
      .b2 = 1,
      .bo = 63,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEERING_REQUIRED",
      .b1 = 15,
      .b2 = 1,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_RIGHT",
      .b1 = 14,
      .b2 = 1,
      .bo = 49,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SOLID_LANES",
      .b1 = 13,
      .b2 = 1,
      .bo = 50,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_OFF",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKAS_PROBLEM",
      .b1 = 11,
      .b2 = 1,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DTC",
      .b1 = 10,
      .b2 = 1,
      .bo = 53,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DASHED_LANES",
      .b1 = 9,
      .b2 = 1,
      .bo = 54,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BEEP",
      .b1 = 22,
      .b2 = 2,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_PROBLEM",
      .b1 = 18,
      .b2 = 1,
      .bo = 45,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOH",
      .b1 = 16,
      .b2 = 2,
      .bo = 46,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CLEAN_WINDSHIELD",
      .b1 = 29,
      .b2 = 1,
      .bo = 34,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_OFF",
      .b1 = 28,
      .b2 = 1,
      .bo = 35,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LDW_ON",
      .b1 = 27,
      .b2 = 1,
      .bo = 36,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_ME_X48",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_862[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "UI_ALERTS",
      .b1 = 0,
      .b2 = 56,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_884[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "HIGH_BEAM_FLASH",
      .b1 = 42,
      .b2 = 1,
      .bo = 21,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AUTO_HEADLIGHTS",
      .b1 = 41,
      .b2 = 1,
      .bo = 22,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HIGH_BEAM_HOLD",
      .b1 = 40,
      .b2 = 1,
      .bo = 23,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HEADLIGHTS_ON",
      .b1 = 49,
      .b2 = 1,
      .bo = 14,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_891[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "WIPERS",
      .b1 = 22,
      .b2 = 2,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_892[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "CRUISE_SPEED_OFFSET",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = true,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_927[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "ZEROS_BOH",
      .b1 = 0,
      .b2 = 17,
      .bo = 47,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_ALERTS",
      .b1 = 19,
      .b2 = 5,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RESUME_INSTRUCTION",
      .b1 = 18,
      .b2 = 1,
      .bo = 45,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "APPLY_BRAKES_FOR_CANC",
      .b1 = 16,
      .b2 = 1,
      .bo = 47,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS_BOH2",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LEAD_SPEED",
      .b1 = 32,
      .b2 = 9,
      .bo = 23,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LEAD_DISTANCE",
      .b1 = 44,
      .b2 = 5,
      .bo = 15,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LEAD_STATE",
      .b1 = 41,
      .b2 = 3,
      .bo = 20,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ZEROS_BOH3",
      .b1 = 49,
      .b2 = 7,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_929[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
};
const Signal sigs_985[] = {
    {
      .name = "CHECKSUM",
      .b1 = 20,
      .b2 = 4,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 18,
      .b2 = 2,
      .bo = 44,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
};
const Signal sigs_1024[] = {
    {
      .name = "CHECKSUM",
      .b1 = 36,
      .b2 = 4,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 34,
      .b2 = 2,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
};
const Signal sigs_1027[] = {
    {
      .name = "CHECKSUM",
      .b1 = 36,
      .b2 = 4,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 34,
      .b2 = 2,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
};
const Signal sigs_1029[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "DOOR_OPEN_FL",
      .b1 = 34,
      .b2 = 1,
      .bo = 29,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_FR",
      .b1 = 33,
      .b2 = 1,
      .bo = 30,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_RL",
      .b1 = 32,
      .b2 = 1,
      .bo = 31,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_RR",
      .b1 = 47,
      .b2 = 1,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TRUNK_OPEN",
      .b1 = 46,
      .b2 = 1,
      .bo = 17,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1036[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
};
const Signal sigs_1039[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
};
const Signal sigs_1108[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
};
const Signal sigs_1302[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
    {
      .name = "ODOMETER",
      .b1 = 0,
      .b2 = 24,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1322[] = {
    {
      .name = "CHECKSUM",
      .b1 = 36,
      .b2 = 4,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 34,
      .b2 = 2,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
};
const Signal sigs_1633[] = {
    {
      .name = "CHECKSUM",
      .b1 = 60,
      .b2 = 4,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_CHECKSUM,
    },
    {
      .name = "COUNTER",
      .b1 = 58,
      .b2 = 2,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::HONDA_COUNTER,
    },
};

const Msg msgs[] = {
  {
    .name = "XXX_1",
    .address = 0x39,
    .size = 3,
    .num_sigs = ARRAYSIZE(sigs_57),
    .sigs = sigs_57,
  },
  {
    .name = "XXX_2",
    .address = 0x94,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_148),
    .sigs = sigs_148,
  },
  {
    .name = "STEERING_CONTROL",
    .address = 0xE4,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_228),
    .sigs = sigs_228,
  },
  {
    .name = "GAS_PEDAL2",
    .address = 0x130,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_304),
    .sigs = sigs_304,
  },
  {
    .name = "STEERING_SENSORS",
    .address = 0x14A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_330),
    .sigs = sigs_330,
  },
  {
    .name = "POWERTRAIN_DATA",
    .address = 0x158,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_344),
    .sigs = sigs_344,
  },
  {
    .name = "POWERTRAIN_DATA2",
    .address = 0x17C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_380),
    .sigs = sigs_380,
  },
  {
    .name = "STEER_STATUS",
    .address = 0x18F,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_399),
    .sigs = sigs_399,
  },
  {
    .name = "GEARBOX_1",
    .address = 0x191,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_401),
    .sigs = sigs_401,
  },
  {
    .name = "GEARBOX_2",
    .address = 0x1A3,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_419),
    .sigs = sigs_419,
  },
  {
    .name = "VSA_STATUS",
    .address = 0x1A4,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_420),
    .sigs = sigs_420,
  },
  {
    .name = "XXX_3",
    .address = 0x1AB,
    .size = 3,
    .num_sigs = ARRAYSIZE(sigs_427),
    .sigs = sigs_427,
  },
  {
    .name = "XXX_4",
    .address = 0x1AC,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_428),
    .sigs = sigs_428,
  },
  {
    .name = "STANDSTILL",
    .address = 0x1B0,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_432),
    .sigs = sigs_432,
  },
  {
    .name = "XXX_5",
    .address = 0x1C2,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_450),
    .sigs = sigs_450,
  },
  {
    .name = "WHEEL_SPEEDS",
    .address = 0x1D0,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_464),
    .sigs = sigs_464,
  },
  {
    .name = "XXX_7",
    .address = 0x1DC,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_476),
    .sigs = sigs_476,
  },
  {
    .name = "XXX_8",
    .address = 0x1E7,
    .size = 4,
    .num_sigs = ARRAYSIZE(sigs_487),
    .sigs = sigs_487,
  },
  {
    .name = "VEHICLE_DYNAMICS",
    .address = 0x1EA,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_490),
    .sigs = sigs_490,
  },
  {
    .name = "XXX_9",
    .address = 0x1ED,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_493),
    .sigs = sigs_493,
  },
  {
    .name = "BRAKE_COMMAND",
    .address = 0x1FA,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_506),
    .sigs = sigs_506,
  },
  {
    .name = "GAS_COMMAND",
    .address = 0x200,
    .size = 3,
    .num_sigs = ARRAYSIZE(sigs_512),
    .sigs = sigs_512,
  },
  {
    .name = "GAS_SENSOR",
    .address = 0x201,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_513),
    .sigs = sigs_513,
  },
  {
    .name = "XXX_10",
    .address = 0x221,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_545),
    .sigs = sigs_545,
  },
  {
    .name = "ROUGH_WHEEL_SPEED",
    .address = 0x255,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_597),
    .sigs = sigs_597,
  },
  {
    .name = "CRUISE_BUTTONS",
    .address = 0x296,
    .size = 4,
    .num_sigs = ARRAYSIZE(sigs_662),
    .sigs = sigs_662,
  },
  {
    .name = "SEATBELT_STATUS",
    .address = 0x305,
    .size = 7,
    .num_sigs = ARRAYSIZE(sigs_773),
    .sigs = sigs_773,
  },
  {
    .name = "XXX_11",
    .address = 0x309,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_777),
    .sigs = sigs_777,
  },
  {
    .name = "ACC_HUD",
    .address = 0x30C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_780),
    .sigs = sigs_780,
  },
  {
    .name = "XXX_12",
    .address = 0x31B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_795),
    .sigs = sigs_795,
  },
  {
    .name = "XXX_13",
    .address = 0x320,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_800),
    .sigs = sigs_800,
  },
  {
    .name = "CRUISE",
    .address = 0x324,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_804),
    .sigs = sigs_804,
  },
  {
    .name = "SCM_FEEDBACK",
    .address = 0x326,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_806),
    .sigs = sigs_806,
  },
  {
    .name = "XXX_14",
    .address = 0x328,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_808),
    .sigs = sigs_808,
  },
  {
    .name = "LKAS_HUD_2",
    .address = 0x33D,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_829),
    .sigs = sigs_829,
  },
  {
    .name = "XXX_15",
    .address = 0x35E,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_862),
    .sigs = sigs_862,
  },
  {
    .name = "STALK_STATUS",
    .address = 0x374,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_884),
    .sigs = sigs_884,
  },
  {
    .name = "XXX_17",
    .address = 0x37B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_891),
    .sigs = sigs_891,
  },
  {
    .name = "CRUISE_PARAMS",
    .address = 0x37C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_892),
    .sigs = sigs_892,
  },
  {
    .name = "XXX_19",
    .address = 0x39F,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_927),
    .sigs = sigs_927,
  },
  {
    .name = "XXX_20",
    .address = 0x3A1,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_929),
    .sigs = sigs_929,
  },
  {
    .name = "XXX_21",
    .address = 0x3D9,
    .size = 3,
    .num_sigs = ARRAYSIZE(sigs_985),
    .sigs = sigs_985,
  },
  {
    .name = "XXX_22",
    .address = 0x400,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_1024),
    .sigs = sigs_1024,
  },
  {
    .name = "XXX_23",
    .address = 0x403,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_1027),
    .sigs = sigs_1027,
  },
  {
    .name = "DOORS_STATUS",
    .address = 0x405,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1029),
    .sigs = sigs_1029,
  },
  {
    .name = "XXX_24",
    .address = 0x40C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1036),
    .sigs = sigs_1036,
  },
  {
    .name = "XXX_25",
    .address = 0x40F,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1039),
    .sigs = sigs_1039,
  },
  {
    .name = "XXX_26",
    .address = 0x454,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1108),
    .sigs = sigs_1108,
  },
  {
    .name = "XXX_27",
    .address = 0x516,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1302),
    .sigs = sigs_1302,
  },
  {
    .name = "XXX_28",
    .address = 0x52A,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_1322),
    .sigs = sigs_1322,
  },
  {
    .name = "XXX_34",
    .address = 0x661,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1633),
    .sigs = sigs_1633,
  },
};

const Val vals[] = {
    {
      .name = "STEER_STATUS",
      .address = 0x18F,
      .def_val = "5 FAULT 4 NO_TORQUE_ALERT_2 2 NO_TORQUE_ALERT_1 0 NORMAL",
      .sigs = sigs_399,
    },
    {
      .name = "GEAR",
      .address = 0x191,
      .def_val = "7 L 10 S 4 D 3 N 2 R 1 P",
      .sigs = sigs_401,
    },
    {
      .name = "GEAR_SHIFTER",
      .address = 0x191,
      .def_val = "32 L 16 S 8 D 4 N 2 R 1 P",
      .sigs = sigs_401,
    },
    {
      .name = "EPB_STATE",
      .address = 0x1C2,
      .def_val = "3 ENGAGED 2 DISENGAGING 1 ENGAGING 0 DISENGAGED",
      .sigs = sigs_450,
    },
    {
      .name = "CHIME",
      .address = 0x1FA,
      .def_val = "4 DOUBLE_CHIME 3 SINGLE_CHIME 2 CONTINUOUS_CHIME 1 REPEATING_CHIME 0 NO_CHIME",
      .sigs = sigs_506,
    },
    {
      .name = "CRUISE_BUTTONS",
      .address = 0x296,
      .def_val = "7 TBD 6 TBD 5 TBD 4 ACCEL_RES 3 DECEL_SET 2 CANCEL 1 MAIN 0 NONE",
      .sigs = sigs_662,
    },
    {
      .name = "CRUISE_SETTING",
      .address = 0x296,
      .def_val = "3 DISTANCE_ADJ 2 TBD 1 LKAS_BUTTON 0 NONE",
      .sigs = sigs_662,
    },
    {
      .name = "CRUISE_SPEED",
      .address = 0x30C,
      .def_val = "255 NO_SPEED 252 STOPPED",
      .sigs = sigs_780,
    },
    {
      .name = "HUD_LEAD",
      .address = 0x30C,
      .def_val = "3 ACC_OFF 2 SOLID_CAR 1 DASHED_CAR 0 NO_CAR",
      .sigs = sigs_780,
    },
    {
      .name = "CMBS_BUTTON",
      .address = 0x326,
      .def_val = "3 PRESSED 0 RELEASED",
      .sigs = sigs_806,
    },
    {
      .name = "BEEP",
      .address = 0x33D,
      .def_val = "3 SINGLE_BEEP 2 TRIPLE_BEEP 1 REPEATED_BEEP 0 NO_BEEP",
      .sigs = sigs_829,
    },
    {
      .name = "WIPERS",
      .address = 0x37B,
      .def_val = "4 HIGH 2 LOW 0 OFF",
      .sigs = sigs_891,
    },
    {
      .name = "ACC_ALERTS",
      .address = 0x39F,
      .def_val = "29 ESP_ACTIVE_ACC_CANCELED 10 B_PEDAL_APPLIED 9 SPEED_TOO_LOW 8 SPEED_TOO_HIGH 7 P_BRAKE_APPLIED 6 GEAR_NO_D 5 SEATBELT 4 TOO_STEEP_DOWNHILL 3 TOO_STEEP_UPHILL 2 TOO_CLOSE 1 NO_VEHICLE_AHEAD",
      .sigs = sigs_927,
    },
};

}

const DBC honda_clarity_hybrid_2018_can = {
  .name = "honda_clarity_hybrid_2018_can",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(honda_clarity_hybrid_2018_can)