#include "common_dbc.h"

namespace {

const Signal sigs_2[] = {
    {
      .name = "Steering_Angle",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = true,
      .factor = -0.1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Steering_RateChange",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Always_07",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_346[] = {
    {
      .name = "ANOTHERACCEL",
      .b1 = 16,
      .b2 = 10,
      .bo = 38,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Reverse_ACCEL",
      .b1 = 30,
      .b2 = 10,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_347[] = {
    {
      .name = "ACCELERATOR2",
      .b1 = 1,
      .b2 = 11,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = -800.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "PowerMaybe",
      .b1 = 14,
      .b2 = 10,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_348[] = {
    {
      .name = "NEW_SIGNAL_1",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Accel",
      .b1 = 29,
      .b2 = 11,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AccelFullRange",
      .b1 = 40,
      .b2 = 10,
      .bo = 14,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_361[] = {
    {
      .name = "Des_Angle",
      .b1 = 0,
      .b2 = 18,
      .bo = 46,
      .is_signed = false,
      .factor = -0.01,
      .offset = 1310,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_0x80_2",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_4",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_X80",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Counter",
      .b1 = 52,
      .b2 = 4,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LKA_Active",
      .b1 = 51,
      .b2 = 1,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRC",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_372[] = {
    {
      .name = "Counter",
      .b1 = 32,
      .b2 = 4,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_374[] = {
    {
      .name = "Counter",
      .b1 = 48,
      .b2 = 4,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_384[] = {
    {
      .name = "RequestedAccel",
      .b1 = 16,
      .b2 = 12,
      .bo = 36,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "EnginePower",
      .b1 = 28,
      .b2 = 12,
      .bo = 24,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Unknown_Timer_PowerInfo",
      .b1 = 48,
      .b2 = 4,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_386[] = {
    {
      .name = "Accelerator",
      .b1 = 33,
      .b2 = 7,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_389[] = {
    {
      .name = "COUNTER",
      .b1 = 48,
      .b2 = 4,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_1",
      .b1 = 8,
      .b2 = 8,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_2",
      .b1 = 17,
      .b2 = 6,
      .bo = 41,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_3",
      .b1 = 25,
      .b2 = 8,
      .bo = 31,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_4",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_5",
      .b1 = 48,
      .b2 = 4,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_6",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_397[] = {
    {
      .name = "NEW_SIGNAL_1",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_2",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_3",
      .b1 = 32,
      .b2 = 16,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_4",
      .b1 = 48,
      .b2 = 16,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_403[] = {
    {
      .name = "Steering_Torque",
      .b1 = 0,
      .b2 = 13,
      .bo = 51,
      .is_signed = false,
      .factor = -1.0,
      .offset = 4000,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Angle_1",
      .b1 = 13,
      .b2 = 13,
      .bo = 38,
      .is_signed = false,
      .factor = 0.12,
      .offset = -480.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Torque_Command",
      .b1 = 26,
      .b2 = 13,
      .bo = 25,
      .is_signed = false,
      .factor = 1,
      .offset = -4000.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Angle_2",
      .b1 = 39,
      .b2 = 13,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = -4000.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Counter",
      .b1 = 48,
      .b2 = 4,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Checksum",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_412[] = {
    {
      .name = "NEW_SIGNAL_1",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_3",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_2",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_4",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_438[] = {
    {
      .name = "NEW_SIGNAL_1",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_2",
      .b1 = 12,
      .b2 = 4,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_3",
      .b1 = 16,
      .b2 = 12,
      .bo = 36,
      .is_signed = true,
      .factor = -1.0,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_4",
      .b1 = 28,
      .b2 = 4,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SET_3",
      .b1 = 32,
      .b2 = 2,
      .bo = 30,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_ON",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRUISE_ACTIVATED",
      .b1 = 33,
      .b2 = 1,
      .bo = 30,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_6",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_STATUS",
      .b1 = 51,
      .b2 = 1,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Counter",
      .b1 = 48,
      .b2 = 4,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_8",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_523[] = {
    {
      .name = "yetyetanotheraccel",
      .b1 = 24,
      .b2 = 10,
      .bo = 30,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ANOTHERREVERSEACCEL",
      .b1 = 34,
      .b2 = 10,
      .bo = 20,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_566[] = {
    {
      .name = "RPMORTORQUE",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ANOTHERFULLRANGEACCEL",
      .b1 = 44,
      .b2 = 8,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_644[] = {
    {
      .name = "Speed_FR",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 0.0118,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Speed_FL",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = false,
      .factor = 0.0118,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Speed_Vehicle",
      .b1 = 32,
      .b2 = 16,
      .bo = 16,
      .is_signed = false,
      .factor = 0.0245,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_645[] = {
    {
      .name = "RR",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 0.00555,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RL",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = false,
      .factor = 0.00555,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_658[] = {
    {
      .name = "NEW_SIGNAL_1",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_666[] = {
    {
      .name = "FR",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 0.00555,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FL",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = false,
      .factor = 0.00555,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "_FL_WHEELSPEED",
      .b1 = 32,
      .b2 = 16,
      .bo = 16,
      .is_signed = false,
      .factor = 0.01014,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_768[] = {
    {
      .name = "STEERING_TOURQUE",
      .b1 = 0,
      .b2 = 7,
      .bo = 57,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_773[] = {
    {
      .name = "NEW_SIGNAL_1",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_2",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_779[] = {
    {
      .name = "ANOTHERRRFULLRANGEACCEL",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_851[] = {
    {
      .name = "SPEED_RELATED",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 0.01014,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_855[] = {
    {
      .name = "NEW_SIGNAL_1",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1107[] = {
    {
      .name = "_HEADLIGHTS",
      .b1 = 2,
      .b2 = 1,
      .bo = 61,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LEFT_BLINKER",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RIGHT_BLINKER",
      .b1 = 11,
      .b2 = 1,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1108[] = {
    {
      .name = "DOOR_CLOSED_RR",
      .b1 = 47,
      .b2 = 1,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_RR",
      .b1 = 46,
      .b2 = 1,
      .bo = 17,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_CLOSED_RL",
      .b1 = 45,
      .b2 = 1,
      .bo = 18,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_RL",
      .b1 = 44,
      .b2 = 1,
      .bo = 19,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_CLOSED_FL",
      .b1 = 43,
      .b2 = 1,
      .bo = 20,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_FL",
      .b1 = 42,
      .b2 = 1,
      .bo = 21,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_CLOSED_FR",
      .b1 = 41,
      .b2 = 1,
      .bo = 22,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_OPEN_FR",
      .b1 = 40,
      .b2 = 1,
      .bo = 23,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOOT_OPEN",
      .b1 = 48,
      .b2 = 1,
      .bo = 15,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "SteeringWheel",
    .address = 0x2,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_2),
    .sigs = sigs_2,
  },
  {
    .name = "ANOTHER_ACCEL",
    .address = 0x15A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_346),
    .sigs = sigs_346,
  },
  {
    .name = "ACCELSOMETHING",
    .address = 0x15B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_347),
    .sigs = sigs_347,
  },
  {
    .name = "FULLRANGEACCEL",
    .address = 0x15C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_348),
    .sigs = sigs_348,
  },
  {
    .name = "LKAS",
    .address = 0x169,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_361),
    .sigs = sigs_361,
  },
  {
    .name = "Maybe_Gear_Selector",
    .address = 0x174,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_372),
    .sigs = sigs_372,
  },
  {
    .name = "Maybe_Motor_RPM_or_Speed",
    .address = 0x176,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_374),
    .sigs = sigs_374,
  },
  {
    .name = "Maybe_PowerInfo",
    .address = 0x180,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_384),
    .sigs = sigs_384,
  },
  {
    .name = "Accelerator",
    .address = 0x182,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_386),
    .sigs = sigs_386,
  },
  {
    .name = "NEW_MSG_3",
    .address = 0x185,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_389),
    .sigs = sigs_389,
  },
  {
    .name = "NEW_MSG_4",
    .address = 0x18D,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_397),
    .sigs = sigs_397,
  },
  {
    .name = "LKAS_OLD",
    .address = 0x193,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_403),
    .sigs = sigs_403,
  },
  {
    .name = "NEW_MSG_9",
    .address = 0x19C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_412),
    .sigs = sigs_412,
  },
  {
    .name = "ProPilot",
    .address = 0x1B6,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_438),
    .sigs = sigs_438,
  },
  {
    .name = "Yetyetanotheraccel",
    .address = 0x20B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_523),
    .sigs = sigs_523,
  },
  {
    .name = "ANOTHERFULLRANGEACCEL",
    .address = 0x236,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_566),
    .sigs = sigs_566,
  },
  {
    .name = "Speed_1",
    .address = 0x284,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_644),
    .sigs = sigs_644,
  },
  {
    .name = "WheelspeedRear",
    .address = 0x285,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_645),
    .sigs = sigs_645,
  },
  {
    .name = "NEW_MSG_5",
    .address = 0x292,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_658),
    .sigs = sigs_658,
  },
  {
    .name = "WheelspeedFront",
    .address = 0x29A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_666),
    .sigs = sigs_666,
  },
  {
    .name = "STEER_TORQUE",
    .address = 0x300,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_768),
    .sigs = sigs_768,
  },
  {
    .name = "NEW_MSG_7",
    .address = 0x305,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_773),
    .sigs = sigs_773,
  },
  {
    .name = "ANOTHERRRFULLRANGEACCEL",
    .address = 0x30B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_779),
    .sigs = sigs_779,
  },
  {
    .name = "SPEED_RELATED",
    .address = 0x353,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_851),
    .sigs = sigs_851,
  },
  {
    .name = "NEW_MSG_6",
    .address = 0x357,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_855),
    .sigs = sigs_855,
  },
  {
    .name = "Lights",
    .address = 0x453,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1107),
    .sigs = sigs_1107,
  },
  {
    .name = "Doors",
    .address = 0x454,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1108),
    .sigs = sigs_1108,
  },
};

const Val vals[] = {
};

}

const DBC nissan_2017 = {
  .name = "nissan_2017",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(nissan_2017)