#include "common_dbc.h"

namespace {

const Signal sigs_3[] = {
    {
      .name = "StW_Angl",
      .b1 = 2,
      .b2 = 14,
      .bo = 48,
      .is_signed = false,
      .factor = 0.5,
      .offset = -2048.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_AnglSpd",
      .b1 = 18,
      .b2 = 14,
      .bo = 32,
      .is_signed = false,
      .factor = 0.5,
      .offset = -2048.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_AnglSens_Stat",
      .b1 = 38,
      .b2 = 2,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_AnglSens_Id",
      .b1 = 36,
      .b2 = 2,
      .bo = 26,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MC_STW_ANGL_STAT",
      .b1 = 48,
      .b2 = 4,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRC_STW_ANGL_STAT",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_14[] = {
    {
      .name = "StW_AnglHP",
      .b1 = 2,
      .b2 = 14,
      .bo = 48,
      .is_signed = false,
      .factor = 0.1,
      .offset = -819.2,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_AnglHP_Spd",
      .b1 = 18,
      .b2 = 14,
      .bo = 32,
      .is_signed = false,
      .factor = 0.5,
      .offset = -4096.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_AnglHP_Sens_Stat",
      .b1 = 38,
      .b2 = 2,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_AnglHP_Sens_Id",
      .b1 = 36,
      .b2 = 2,
      .bo = 26,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MC_STW_ANGLHP_STAT",
      .b1 = 48,
      .b2 = 4,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRC_STW_ANGLHP_STAT",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_69[] = {
    {
      .name = "SpdCtrlLvr_Stat",
      .b1 = 0,
      .b2 = 6,
      .bo = 58,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VSL_Enbl_Rq",
      .b1 = 6,
      .b2 = 1,
      .bo = 57,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SpdCtrlLvrStat_Inv",
      .b1 = 7,
      .b2 = 1,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DTR_Dist_Rq",
      .b1 = 8,
      .b2 = 8,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TurnIndLvr_Stat",
      .b1 = 16,
      .b2 = 2,
      .bo = 46,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HiBmLvr_Stat",
      .b1 = 18,
      .b2 = 2,
      .bo = 44,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WprWashSw_Psd",
      .b1 = 20,
      .b2 = 2,
      .bo = 42,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WprWash_R_Sw_Posn_V2",
      .b1 = 22,
      .b2 = 2,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Lvr_Stat",
      .b1 = 24,
      .b2 = 3,
      .bo = 37,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Cond_Flt",
      .b1 = 27,
      .b2 = 1,
      .bo = 36,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Cond_Psd",
      .b1 = 28,
      .b2 = 2,
      .bo = 34,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HrnSw_Psd",
      .b1 = 30,
      .b2 = 2,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw00_Psd",
      .b1 = 32,
      .b2 = 1,
      .bo = 31,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw01_Psd",
      .b1 = 33,
      .b2 = 1,
      .bo = 30,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw02_Psd",
      .b1 = 34,
      .b2 = 1,
      .bo = 29,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw03_Psd",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw04_Psd",
      .b1 = 36,
      .b2 = 1,
      .bo = 27,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw05_Psd",
      .b1 = 37,
      .b2 = 1,
      .bo = 26,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw06_Psd",
      .b1 = 38,
      .b2 = 1,
      .bo = 25,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw07_Psd",
      .b1 = 39,
      .b2 = 1,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw08_Psd",
      .b1 = 40,
      .b2 = 1,
      .bo = 23,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw09_Psd",
      .b1 = 41,
      .b2 = 1,
      .bo = 22,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw10_Psd",
      .b1 = 42,
      .b2 = 1,
      .bo = 21,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw11_Psd",
      .b1 = 43,
      .b2 = 1,
      .bo = 20,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw12_Psd",
      .b1 = 44,
      .b2 = 1,
      .bo = 19,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw13_Psd",
      .b1 = 45,
      .b2 = 1,
      .bo = 18,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw14_Psd",
      .b1 = 46,
      .b2 = 1,
      .bo = 17,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Sw15_Psd",
      .b1 = 47,
      .b2 = 1,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WprSw6Posn",
      .b1 = 48,
      .b2 = 3,
      .bo = 13,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MC_STW_ACTN_RQ",
      .b1 = 52,
      .b2 = 4,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRC_STW_ACTN_RQ",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_109[] = {
    {
      .name = "StW_Sw_Stat3",
      .b1 = 0,
      .b2 = 3,
      .bo = 61,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MsgTxmtId",
      .b1 = 6,
      .b2 = 2,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TSL_RND_Posn_StW",
      .b1 = 8,
      .b2 = 4,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TSL_P_Psd_StW",
      .b1 = 12,
      .b2 = 2,
      .bo = 50,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MC_SBW_RQ_SCCM",
      .b1 = 20,
      .b2 = 4,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CRC_SBW_RQ_SCCM",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_257[] = {
    {
      .name = "GTW_epasTuneRequest",
      .b1 = 5,
      .b2 = 3,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_epasPowerMode",
      .b1 = 1,
      .b2 = 4,
      .bo = 59,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_epasEmergencyOn",
      .b1 = 0,
      .b2 = 1,
      .bo = 63,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_epasControlCounter",
      .b1 = 12,
      .b2 = 4,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_epasLDWEnabled",
      .b1 = 11,
      .b2 = 1,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_epasControlType",
      .b1 = 8,
      .b2 = 2,
      .bo = 54,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_epasControlChecksum",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_264[] = {
    {
      .name = "DI_torqueDriver",
      .b1 = 0,
      .b2 = 13,
      .bo = 51,
      .is_signed = true,
      .factor = 0.25,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_torque1Counter",
      .b1 = 13,
      .b2 = 3,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_torqueMotor",
      .b1 = 16,
      .b2 = 13,
      .bo = 35,
      .is_signed = true,
      .factor = 0.25,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_soptState",
      .b1 = 29,
      .b2 = 3,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_motorRPM",
      .b1 = 32,
      .b2 = 16,
      .bo = 16,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_pedalPos",
      .b1 = 48,
      .b2 = 8,
      .bo = 8,
      .is_signed = false,
      .factor = 0.4,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_torque1Checksum",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_280[] = {
    {
      .name = "DI_torqueEstimate",
      .b1 = 0,
      .b2 = 12,
      .bo = 52,
      .is_signed = true,
      .factor = 0.5,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_gear",
      .b1 = 12,
      .b2 = 3,
      .bo = 49,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_brakePedal",
      .b1 = 15,
      .b2 = 1,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_vehicleSpeed",
      .b1 = 16,
      .b2 = 12,
      .bo = 36,
      .is_signed = false,
      .factor = 0.05,
      .offset = -25.0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_gearRequest",
      .b1 = 28,
      .b2 = 3,
      .bo = 33,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_torqueInterfaceFailure",
      .b1 = 31,
      .b2 = 1,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_torque2Counter",
      .b1 = 32,
      .b2 = 4,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_brakePedalState",
      .b1 = 36,
      .b2 = 2,
      .bo = 26,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_epbParkRequest",
      .b1 = 38,
      .b2 = 1,
      .bo = 25,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_epbInterfaceReady",
      .b1 = 39,
      .b2 = 1,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_torque2Checksum",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_309[] = {
    {
      .name = "ESP_hillStartAssistActive",
      .b1 = 6,
      .b2 = 2,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_absBrakeEvent",
      .b1 = 5,
      .b2 = 1,
      .bo = 58,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_brakeLamp",
      .b1 = 4,
      .b2 = 1,
      .bo = 59,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_brakeDiscWipingActive",
      .b1 = 3,
      .b2 = 1,
      .bo = 60,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_tcLampFlash",
      .b1 = 2,
      .b2 = 1,
      .bo = 61,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_espFaultLamp",
      .b1 = 1,
      .b2 = 1,
      .bo = 62,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_espLampFlash",
      .b1 = 0,
      .b2 = 1,
      .bo = 63,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_135hCounter",
      .b1 = 12,
      .b2 = 4,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_stabilityControlSts",
      .b1 = 9,
      .b2 = 3,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_tcOffLamp",
      .b1 = 8,
      .b2 = 1,
      .bo = 55,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_135hChecksum",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_messagePumpService",
      .b1 = 31,
      .b2 = 1,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_messagePumpFailure",
      .b1 = 30,
      .b2 = 1,
      .bo = 33,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_messageEBDFailure",
      .b1 = 29,
      .b2 = 1,
      .bo = 34,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_absFaultLamp",
      .b1 = 28,
      .b2 = 1,
      .bo = 35,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_tcDisabledByFault",
      .b1 = 27,
      .b2 = 1,
      .bo = 36,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_messageDynoModeActive",
      .b1 = 26,
      .b2 = 1,
      .bo = 37,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_hydraulicBoostEnabled",
      .b1 = 25,
      .b2 = 1,
      .bo = 38,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_espOffLamp",
      .b1 = 24,
      .b2 = 1,
      .bo = 39,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_341[] = {
    {
      .name = "ESP_wheelPulseCountFrL",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_wheelPulseCountFrR",
      .b1 = 8,
      .b2 = 8,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_wheelPulseCountReL",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_wheelPulseCountReR",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_BChecksum",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_vehicleSpeed",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 0.00999999978,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_vehicleSpeedQF",
      .b1 = 62,
      .b2 = 2,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ESP_BCounter",
      .b1 = 57,
      .b2 = 4,
      .bo = 3,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_532[] = {
    {
      .name = "EPB_epasEACAllow",
      .b1 = 5,
      .b2 = 3,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "EPB_epasControlCounter",
      .b1 = 12,
      .b2 = 4,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "EPB_epasControlChecksum",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_643[] = {
    {
      .name = "DrRLtch_FL_Stat",
      .b1 = 6,
      .b2 = 2,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DrRLtch_FR_Stat",
      .b1 = 4,
      .b2 = 2,
      .bo = 58,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DrRLtch_RL_Stat",
      .b1 = 2,
      .b2 = 2,
      .bo = 60,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DrRLtch_RR_Stat",
      .b1 = 0,
      .b2 = 2,
      .bo = 62,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DL_RLtch_Stat",
      .b1 = 14,
      .b2 = 2,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "EngHd_Stat",
      .b1 = 12,
      .b2 = 2,
      .bo = 50,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VTA_Alm_Actv",
      .b1 = 10,
      .b2 = 1,
      .bo = 53,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LgtSens_Twlgt",
      .b1 = 21,
      .b2 = 3,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LgtSens_SNA",
      .b1 = 20,
      .b2 = 1,
      .bo = 43,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LgtSens_Tunnel",
      .b1 = 19,
      .b2 = 1,
      .bo = 44,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LgtSens_Flt",
      .b1 = 18,
      .b2 = 1,
      .bo = 45,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LgtSens_Night",
      .b1 = 17,
      .b2 = 1,
      .bo = 46,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ADL_LoBm_On_Rq",
      .b1 = 16,
      .b2 = 1,
      .bo = 47,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Trlr_Stat",
      .b1 = 30,
      .b2 = 2,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Hrn_On",
      .b1 = 29,
      .b2 = 1,
      .bo = 34,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Term54_Actv",
      .b1 = 28,
      .b2 = 1,
      .bo = 35,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MPkBrk_Stat",
      .b1 = 27,
      .b2 = 1,
      .bo = 36,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "WprOutsdPkPosn",
      .b1 = 26,
      .b2 = 1,
      .bo = 37,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LoBm_On_Rq",
      .b1 = 39,
      .b2 = 1,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HiBm_On",
      .b1 = 38,
      .b2 = 1,
      .bo = 25,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "IrLmp_D_Lt_Flt",
      .b1 = 37,
      .b2 = 1,
      .bo = 26,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "IrLmp_P_Rt_Flt",
      .b1 = 36,
      .b2 = 1,
      .bo = 27,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LoBm_D_Lt_Flt",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LoBm_P_Rt_Flt",
      .b1 = 34,
      .b2 = 1,
      .bo = 29,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "RevGr_Engg",
      .b1 = 32,
      .b2 = 2,
      .bo = 30,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AirTemp_Insd",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 0.25,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Bckl_Sw_RL_Stat_SAM_R",
      .b1 = 54,
      .b2 = 2,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Bckl_Sw_RR_Stat_SAM_R",
      .b1 = 52,
      .b2 = 2,
      .bo = 10,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Bckl_Sw_RM_Stat_SAM_R",
      .b1 = 50,
      .b2 = 2,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "StW_Cond_Stat",
      .b1 = 48,
      .b2 = 2,
      .bo = 14,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "AirTemp_Outsd",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 0.5,
      .offset = -40.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_760[] = {
    {
      .name = "MCU_gpsHDOP",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MCU_gpsVehicleHeading",
      .b1 = 8,
      .b2 = 16,
      .bo = 40,
      .is_signed = false,
      .factor = 0.00781,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MCU_gpsVehicleSpeed",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 0.00391,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MCU_userSpeedOffsetUnits",
      .b1 = 40,
      .b2 = 1,
      .bo = 23,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MCU_speedLimitUnits",
      .b1 = 41,
      .b2 = 1,
      .bo = 22,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MCU_userSpeedOffset",
      .b1 = 42,
      .b2 = 6,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = -30.0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MCU_mppSpeedLimit",
      .b1 = 51,
      .b2 = 5,
      .bo = 8,
      .is_signed = false,
      .factor = 5,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_792[] = {
    {
      .name = "YEAR",
      .b1 = 1,
      .b2 = 7,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 2000,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CERRD",
      .b1 = 0,
      .b2 = 1,
      .bo = 63,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MONTH",
      .b1 = 12,
      .b2 = 4,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_STATE_FL",
      .b1 = 10,
      .b2 = 2,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_STATE_FR",
      .b1 = 8,
      .b2 = 2,
      .bo = 54,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SECOND",
      .b1 = 18,
      .b2 = 6,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_STATE_RL",
      .b1 = 16,
      .b2 = 2,
      .bo = 46,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "Hour",
      .b1 = 27,
      .b2 = 5,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_STATE_RR",
      .b1 = 25,
      .b2 = 2,
      .bo = 37,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DAY",
      .b1 = 35,
      .b2 = 5,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MINUTE",
      .b1 = 42,
      .b2 = 6,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "BOOT_STATE",
      .b1 = 40,
      .b2 = 2,
      .bo = 22,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_updateInProgress",
      .b1 = 54,
      .b2 = 2,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_STATE_FrontTrunk",
      .b1 = 52,
      .b2 = 2,
      .bo = 10,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MCU_factoryMode",
      .b1 = 51,
      .b2 = 1,
      .bo = 12,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MCU_transportModeOn",
      .b1 = 50,
      .b2 = 1,
      .bo = 13,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_840[] = {
    {
      .name = "GTW_driveRailReq",
      .b1 = 7,
      .b2 = 1,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_brakePressed",
      .b1 = 6,
      .b2 = 1,
      .bo = 57,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_driverPresent",
      .b1 = 5,
      .b2 = 1,
      .bo = 58,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_notEnough12VForDrive",
      .b1 = 4,
      .b2 = 1,
      .bo = 59,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_icPowerOff",
      .b1 = 3,
      .b2 = 1,
      .bo = 60,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_driverIsLeaving",
      .b1 = 2,
      .b2 = 1,
      .bo = 61,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_accGoingDown",
      .b1 = 1,
      .b2 = 1,
      .bo = 62,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_driveGoingDown",
      .b1 = 0,
      .b2 = 1,
      .bo = 63,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_accRailReq",
      .b1 = 15,
      .b2 = 1,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_hvacRailReq",
      .b1 = 14,
      .b2 = 1,
      .bo = 49,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_preconditionRequest",
      .b1 = 13,
      .b2 = 1,
      .bo = 50,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_hvacGoingDown",
      .b1 = 12,
      .b2 = 1,
      .bo = 51,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_statusCounter",
      .b1 = 52,
      .b2 = 4,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "GTW_statusChecksum",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_872[] = {
    {
      .name = "DI_systemState",
      .b1 = 0,
      .b2 = 3,
      .bo = 61,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_vehicleHoldState",
      .b1 = 3,
      .b2 = 3,
      .bo = 58,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_proximity",
      .b1 = 6,
      .b2 = 1,
      .bo = 57,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_driveReady",
      .b1 = 7,
      .b2 = 1,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_regenLight",
      .b1 = 8,
      .b2 = 1,
      .bo = 55,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_state",
      .b1 = 9,
      .b2 = 3,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_cruiseState",
      .b1 = 12,
      .b2 = 4,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_analogSpeed",
      .b1 = 16,
      .b2 = 12,
      .bo = 36,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_immobilizerState",
      .b1 = 28,
      .b2 = 3,
      .bo = 33,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_speedUnits",
      .b1 = 31,
      .b2 = 1,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_cruiseSet",
      .b1 = 32,
      .b2 = 9,
      .bo = 23,
      .is_signed = false,
      .factor = 0.5,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_aebState",
      .b1 = 41,
      .b2 = 3,
      .bo = 20,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_stateCounter",
      .b1 = 44,
      .b2 = 4,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_digitalSpeed",
      .b1 = 48,
      .b2 = 8,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DI_stateChecksum",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_880[] = {
    {
      .name = "EPAS_steeringRackForce",
      .b1 = 6,
      .b2 = 10,
      .bo = 48,
      .is_signed = false,
      .factor = 50,
      .offset = -25575.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "EPAS_steeringFault",
      .b1 = 5,
      .b2 = 1,
      .bo = 58,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "EPAS_steeringReduced",
      .b1 = 4,
      .b2 = 1,
      .bo = 59,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "EPAS_currentTuneMode",
      .b1 = 0,
      .b2 = 4,
      .bo = 60,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "EPAS_torsionBarTorque",
      .b1 = 20,
      .b2 = 12,
      .bo = 32,
      .is_signed = false,
      .factor = 0.01,
      .offset = -20.5,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "EPAS_eacErrorCode",
      .b1 = 16,
      .b2 = 4,
      .bo = 44,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "EPAS_internalSAS",
      .b1 = 34,
      .b2 = 14,
      .bo = 16,
      .is_signed = false,
      .factor = 0.1,
      .offset = -819.200012,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "EPAS_handsOnLevel",
      .b1 = 32,
      .b2 = 2,
      .bo = 30,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "EPAS_sysStatusCounter",
      .b1 = 52,
      .b2 = 4,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "EPAS_eacStatus",
      .b1 = 48,
      .b2 = 3,
      .bo = 13,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "EPAS_sysStatusChecksum",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_904[] = {
    {
      .name = "MCU_clusterReadyForPowerOff",
      .b1 = 5,
      .b2 = 1,
      .bo = 58,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MCU_clusterReadyForDrive",
      .b1 = 6,
      .b2 = 1,
      .bo = 57,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MCU_clusterBacklightOn",
      .b1 = 7,
      .b2 = 1,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MCU_clusterBrightnessLevel",
      .b1 = 8,
      .b2 = 8,
      .bo = 48,
      .is_signed = false,
      .factor = 0.5,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_984[] = {
    {
      .name = "MCU_latitude",
      .b1 = 0,
      .b2 = 28,
      .bo = 36,
      .is_signed = true,
      .factor = 1e-06,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MCU_longitude",
      .b1 = 28,
      .b2 = 28,
      .bo = 8,
      .is_signed = true,
      .factor = 1e-06,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MCU_gpsAccuracy",
      .b1 = 56,
      .b2 = 7,
      .bo = 1,
      .is_signed = false,
      .factor = 0.200000003,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1160[] = {
    {
      .name = "DAS_steeringAngleRequest",
      .b1 = 1,
      .b2 = 15,
      .bo = 48,
      .is_signed = false,
      .factor = 0.1,
      .offset = -1638.35,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DAS_steeringHapticRequest",
      .b1 = 0,
      .b2 = 1,
      .bo = 63,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DAS_steeringControlCounter",
      .b1 = 20,
      .b2 = 4,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DAS_steeringControlType",
      .b1 = 16,
      .b2 = 2,
      .bo = 46,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DAS_steeringControlChecksum",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "STW_ANGL_STAT",
    .address = 0x3,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_3),
    .sigs = sigs_3,
  },
  {
    .name = "STW_ANGLHP_STAT",
    .address = 0xE,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_14),
    .sigs = sigs_14,
  },
  {
    .name = "STW_ACTN_RQ",
    .address = 0x45,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_69),
    .sigs = sigs_69,
  },
  {
    .name = "SBW_RQ_SCCM",
    .address = 0x6D,
    .size = 4,
    .num_sigs = ARRAYSIZE(sigs_109),
    .sigs = sigs_109,
  },
  {
    .name = "GTW_epasControl",
    .address = 0x101,
    .size = 3,
    .num_sigs = ARRAYSIZE(sigs_257),
    .sigs = sigs_257,
  },
  {
    .name = "DI_torque1",
    .address = 0x108,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_264),
    .sigs = sigs_264,
  },
  {
    .name = "DI_torque2",
    .address = 0x118,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_280),
    .sigs = sigs_280,
  },
  {
    .name = "ESP_135h",
    .address = 0x135,
    .size = 5,
    .num_sigs = ARRAYSIZE(sigs_309),
    .sigs = sigs_309,
  },
  {
    .name = "ESP_B",
    .address = 0x155,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_341),
    .sigs = sigs_341,
  },
  {
    .name = "EPB_epasControl",
    .address = 0x214,
    .size = 3,
    .num_sigs = ARRAYSIZE(sigs_532),
    .sigs = sigs_532,
  },
  {
    .name = "BODY_R1",
    .address = 0x283,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_643),
    .sigs = sigs_643,
  },
  {
    .name = "MCU_gpsVehicleSpeed",
    .address = 0x2F8,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_760),
    .sigs = sigs_760,
  },
  {
    .name = "GTW_carState",
    .address = 0x318,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_792),
    .sigs = sigs_792,
  },
  {
    .name = "GTW_status",
    .address = 0x348,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_840),
    .sigs = sigs_840,
  },
  {
    .name = "DI_state",
    .address = 0x368,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_872),
    .sigs = sigs_872,
  },
  {
    .name = "EPAS_sysStatus",
    .address = 0x370,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_880),
    .sigs = sigs_880,
  },
  {
    .name = "MCU_clusterBacklightRequest",
    .address = 0x388,
    .size = 3,
    .num_sigs = ARRAYSIZE(sigs_904),
    .sigs = sigs_904,
  },
  {
    .name = "MCU_locationStatus",
    .address = 0x3D8,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_984),
    .sigs = sigs_984,
  },
  {
    .name = "DAS_steeringControl",
    .address = 0x488,
    .size = 4,
    .num_sigs = ARRAYSIZE(sigs_1160),
    .sigs = sigs_1160,
  },
};

const Val vals[] = {
    {
      .name = "StW_Angl",
      .address = 0x3,
      .def_val = "16383 SNA",
      .sigs = sigs_3,
    },
    {
      .name = "StW_AnglSens_Id",
      .address = 0x3,
      .def_val = "2 MUST 0 PSBL 1 SELF",
      .sigs = sigs_3,
    },
    {
      .name = "StW_AnglSens_Stat",
      .address = 0x3,
      .def_val = "2 ERR 3 ERR_INI 1 INI 0 OK",
      .sigs = sigs_3,
    },
    {
      .name = "StW_AnglSpd",
      .address = 0x3,
      .def_val = "16383 SNA",
      .sigs = sigs_3,
    },
    {
      .name = "StW_AnglHP",
      .address = 0xE,
      .def_val = "16383 SNA",
      .sigs = sigs_14,
    },
    {
      .name = "StW_AnglHP_Sens_Id",
      .address = 0xE,
      .def_val = "3 SNA 2 KOSTAL 1 DELPHI 0 TEST",
      .sigs = sigs_14,
    },
    {
      .name = "StW_AnglHP_Sens_Stat",
      .address = 0xE,
      .def_val = "3 SNA 2 ERR 1 INI 0 OK",
      .sigs = sigs_14,
    },
    {
      .name = "StW_AnglHP_Spd",
      .address = 0xE,
      .def_val = "16383 SNA",
      .sigs = sigs_14,
    },
    {
      .name = "DTR_Dist_Rq",
      .address = 0x45,
      .def_val = "255 SNA 200 ACC_DIST_7 166 ACC_DIST_6 133 ACC_DIST_5 100 ACC_DIST_4 66 ACC_DIST_3 33 ACC_DIST_2 0 ACC_DIST_1",
      .sigs = sigs_69,
    },
    {
      .name = "HiBmLvr_Stat",
      .address = 0x45,
      .def_val = "3 SNA 2 HIBM_FLSH_ON_PSD 1 HIBM_ON_PSD 0 IDLE",
      .sigs = sigs_69,
    },
    {
      .name = "HrnSw_Psd",
      .address = 0x45,
      .def_val = "3 SNA 2 NDEF2 1 PSD 0 NPSD",
      .sigs = sigs_69,
    },
    {
      .name = "SpdCtrlLvr_Stat",
      .address = 0x45,
      .def_val = "32 DN_1ST 16 UP_1ST 8 DN_2ND 4 UP_2ND 2 RWD 1 FWD 0 IDLE",
      .sigs = sigs_69,
    },
    {
      .name = "StW_Cond_Psd",
      .address = 0x45,
      .def_val = "3 SNA 2 DOWN 1 UP 0 NPSD",
      .sigs = sigs_69,
    },
    {
      .name = "StW_Lvr_Stat",
      .address = 0x45,
      .def_val = "4 STW_BACK 3 STW_FWD 2 STW_DOWN 1 STW_UP 0 NPSD",
      .sigs = sigs_69,
    },
    {
      .name = "StW_Sw00_Psd",
      .address = 0x45,
      .def_val = "1 PRESSED 0 NOT_PRESSED_SNA",
      .sigs = sigs_69,
    },
    {
      .name = "StW_Sw01_Psd",
      .address = 0x45,
      .def_val = "1 PRESSED 0 NOT_PRESSED_SNA",
      .sigs = sigs_69,
    },
    {
      .name = "StW_Sw03_Psd",
      .address = 0x45,
      .def_val = "1 PRESSED 0 NOT_PRESSED_SNA",
      .sigs = sigs_69,
    },
    {
      .name = "StW_Sw04_Psd",
      .address = 0x45,
      .def_val = "1 PRESSED 0 NOT_PRESSED_SNA",
      .sigs = sigs_69,
    },
    {
      .name = "TurnIndLvr_Stat",
      .address = 0x45,
      .def_val = "3 SNA 2 RIGHT 1 LEFT 0 IDLE",
      .sigs = sigs_69,
    },
    {
      .name = "WprSw6Posn",
      .address = 0x45,
      .def_val = "7 SNA 6 STAGE2 5 STAGE1 4 INTERVAL4 3 INTERVAL3 2 INTERVAL2 1 INTERVAL1 0 OFF",
      .sigs = sigs_69,
    },
    {
      .name = "WprWashSw_Psd",
      .address = 0x45,
      .def_val = "3 SNA 2 WASH 1 TIPWIPE 0 NPSD",
      .sigs = sigs_69,
    },
    {
      .name = "WprWash_R_Sw_Posn_V2",
      .address = 0x45,
      .def_val = "3 SNA 2 WASH 1 INTERVAL 0 OFF",
      .sigs = sigs_69,
    },
    {
      .name = "MsgTxmtId",
      .address = 0x6D,
      .def_val = "3 NDEF3 2 NDEF2 1 SCCM 0 EWM",
      .sigs = sigs_109,
    },
    {
      .name = "StW_Sw_Stat3",
      .address = 0x6D,
      .def_val = "7 SNA 6 NDEF6 5 NDEF5 4 NDEF4 3 PLUS_MINUS 2 MINUS 1 PLUS 0 NPSD",
      .sigs = sigs_109,
    },
    {
      .name = "TSL_P_Psd_StW",
      .address = 0x6D,
      .def_val = "3 SNA 2 INI 1 PSD 0 IDLE",
      .sigs = sigs_109,
    },
    {
      .name = "TSL_RND_Posn_StW",
      .address = 0x6D,
      .def_val = "15 SNA 8 D 6 INI 4 N_DOWN 2 N_UP 1 R 0 IDLE",
      .sigs = sigs_109,
    },
    {
      .name = "GTW_epasControlType",
      .address = 0x101,
      .def_val = "0 WITHOUT 1 WITH_ANGLE 3 WITH_BOTH 2 WITH_TORQUE",
      .sigs = sigs_257,
    },
    {
      .name = "GTW_epasEmergencyOn",
      .address = 0x101,
      .def_val = "1 EMERGENCY_POWER 0 NONE",
      .sigs = sigs_257,
    },
    {
      .name = "GTW_epasLDWEnabled",
      .address = 0x101,
      .def_val = "1 ALLOWED 0 INHIBITED",
      .sigs = sigs_257,
    },
    {
      .name = "GTW_epasPowerMode",
      .address = 0x101,
      .def_val = "0 DRIVE_OFF 1 DRIVE_ON 3 LOAD_SHED 2 SHUTTING_DOWN 15 SNA",
      .sigs = sigs_257,
    },
    {
      .name = "GTW_epasTuneRequest",
      .address = 0x101,
      .def_val = "1 DM_COMFORT 3 DM_SPORT 2 DM_STANDARD 0 FAIL_SAFE_DEFAULT 4 RWD_COMFORT 6 RWD_SPORT 5 RWD_STANDARD 7 SNA",
      .sigs = sigs_257,
    },
    {
      .name = "DI_motorRPM",
      .address = 0x108,
      .def_val = "-32768 SNA",
      .sigs = sigs_264,
    },
    {
      .name = "DI_pedalPos",
      .address = 0x108,
      .def_val = "255 SNA",
      .sigs = sigs_264,
    },
    {
      .name = "DI_soptState",
      .address = 0x108,
      .def_val = "7 SOPT_TEST_SNA 4 SOPT_TEST_NOT_RUN 3 SOPT_TEST_PASSED 2 SOPT_TEST_FAILED 1 SOPT_TEST_IN_PROGRESS 0 SOPT_PRE_TEST",
      .sigs = sigs_264,
    },
    {
      .name = "DI_torqueDriver",
      .address = 0x108,
      .def_val = "-4096 SNA",
      .sigs = sigs_264,
    },
    {
      .name = "DI_torqueMotor",
      .address = 0x108,
      .def_val = "-4096 SNA",
      .sigs = sigs_264,
    },
    {
      .name = "DI_brakePedal",
      .address = 0x118,
      .def_val = "1 APPLIED 0 NOT_APPLIED",
      .sigs = sigs_280,
    },
    {
      .name = "DI_brakePedalState",
      .address = 0x118,
      .def_val = "3 SNA 2 INVALID 1 ON 0 OFF",
      .sigs = sigs_280,
    },
    {
      .name = "DI_epbInterfaceReady",
      .address = 0x118,
      .def_val = "1 EPB_INTERFACE_READY 0 EPB_INTERFACE_NOT_READY",
      .sigs = sigs_280,
    },
    {
      .name = "DI_epbParkRequest",
      .address = 0x118,
      .def_val = "1 PARK_REQUESTED 0 NO_REQUEST",
      .sigs = sigs_280,
    },
    {
      .name = "DI_gear",
      .address = 0x118,
      .def_val = "7 DI_GEAR_SNA 4 DI_GEAR_D 3 DI_GEAR_N 2 DI_GEAR_R 1 DI_GEAR_P 0 DI_GEAR_INVALID",
      .sigs = sigs_280,
    },
    {
      .name = "DI_gearRequest",
      .address = 0x118,
      .def_val = "7 DI_GEAR_SNA 4 DI_GEAR_D 3 DI_GEAR_N 2 DI_GEAR_R 1 DI_GEAR_P 0 DI_GEAR_INVALID",
      .sigs = sigs_280,
    },
    {
      .name = "DI_torqueEstimate",
      .address = 0x118,
      .def_val = "-2048 SNA",
      .sigs = sigs_280,
    },
    {
      .name = "DI_torqueInterfaceFailure",
      .address = 0x118,
      .def_val = "1 TORQUE_INTERFACE_FAILED 0 TORQUE_INTERFACE_NORMAL",
      .sigs = sigs_280,
    },
    {
      .name = "DI_vehicleSpeed",
      .address = 0x118,
      .def_val = "4095 SNA",
      .sigs = sigs_280,
    },
    {
      .name = "ESP_absBrakeEvent",
      .address = 0x135,
      .def_val = "1 ACTIVE 0 NOT_ACTIVE",
      .sigs = sigs_309,
    },
    {
      .name = "ESP_absFaultLamp",
      .address = 0x135,
      .def_val = "0 OFF 1 ON",
      .sigs = sigs_309,
    },
    {
      .name = "ESP_brakeDiscWipingActive",
      .address = 0x135,
      .def_val = "1 ACTIVE 0 INACTIVE",
      .sigs = sigs_309,
    },
    {
      .name = "ESP_brakeLamp",
      .address = 0x135,
      .def_val = "0 OFF 1 ON",
      .sigs = sigs_309,
    },
    {
      .name = "ESP_espFaultLamp",
      .address = 0x135,
      .def_val = "0 OFF 1 ON",
      .sigs = sigs_309,
    },
    {
      .name = "ESP_espLampFlash",
      .address = 0x135,
      .def_val = "1 FLASH 0 OFF",
      .sigs = sigs_309,
    },
    {
      .name = "ESP_espOffLamp",
      .address = 0x135,
      .def_val = "0 OFF 1 ON",
      .sigs = sigs_309,
    },
    {
      .name = "ESP_hillStartAssistActive",
      .address = 0x135,
      .def_val = "1 ACTIVE 0 INACTIVE 2 NOT_AVAILABLE 3 SNA",
      .sigs = sigs_309,
    },
    {
      .name = "ESP_stabilityControlSts",
      .address = 0x135,
      .def_val = "2 ENGAGED 3 FAULTED 5 INIT 4 NOT_CONFIGURED 0 OFF 1 ON",
      .sigs = sigs_309,
    },
    {
      .name = "ESP_tcLampFlash",
      .address = 0x135,
      .def_val = "1 FLASH 0 OFF",
      .sigs = sigs_309,
    },
    {
      .name = "AirTemp_Insd",
      .address = 0x283,
      .def_val = "255 SNA",
      .sigs = sigs_643,
    },
    {
      .name = "AirTemp_Outsd",
      .address = 0x283,
      .def_val = "254 INIT 255 SNA",
      .sigs = sigs_643,
    },
    {
      .name = "Bckl_Sw_RL_Stat_SAM_R",
      .address = 0x283,
      .def_val = "2 FLT 1 NOT 0 OK 3 SNA",
      .sigs = sigs_643,
    },
    {
      .name = "Bckl_Sw_RM_Stat_SAM_R",
      .address = 0x283,
      .def_val = "2 FLT 1 NOT 0 OK 3 SNA",
      .sigs = sigs_643,
    },
    {
      .name = "Bckl_Sw_RR_Stat_SAM_R",
      .address = 0x283,
      .def_val = "2 FLT 1 NOT 0 OK 3 SNA",
      .sigs = sigs_643,
    },
    {
      .name = "DL_RLtch_Stat",
      .address = 0x283,
      .def_val = "1 CLS 0 NDEF0 2 OPN 3 SNA",
      .sigs = sigs_643,
    },
    {
      .name = "DrRLtch_FL_Stat",
      .address = 0x283,
      .def_val = "1 CLS 0 NDEF0 2 OPN 3 SNA",
      .sigs = sigs_643,
    },
    {
      .name = "DrRLtch_FR_Stat",
      .address = 0x283,
      .def_val = "1 CLS 0 NDEF0 2 OPN 3 SNA",
      .sigs = sigs_643,
    },
    {
      .name = "DrRLtch_RL_Stat",
      .address = 0x283,
      .def_val = "1 CLS 0 NDEF0 2 OPN 3 SNA",
      .sigs = sigs_643,
    },
    {
      .name = "DrRLtch_RR_Stat",
      .address = 0x283,
      .def_val = "1 CLS 0 NDEF0 2 OPN 3 SNA",
      .sigs = sigs_643,
    },
    {
      .name = "EngHd_Stat",
      .address = 0x283,
      .def_val = "1 CLS 0 NDEF0 2 OPN 3 SNA",
      .sigs = sigs_643,
    },
    {
      .name = "LgtSens_Night",
      .address = 0x283,
      .def_val = "0 DAY 1 NIGHT",
      .sigs = sigs_643,
    },
    {
      .name = "MPkBrk_Stat",
      .address = 0x283,
      .def_val = "1 ENGG 0 RELS",
      .sigs = sigs_643,
    },
    {
      .name = "RevGr_Engg",
      .address = 0x283,
      .def_val = "0 DISENGG 1 ENGG 2 NDEF2 3 SNA",
      .sigs = sigs_643,
    },
    {
      .name = "StW_Cond_Stat",
      .address = 0x283,
      .def_val = "3 BLINK 1 NDEF1 0 OFF 2 ON",
      .sigs = sigs_643,
    },
    {
      .name = "Trlr_Stat",
      .address = 0x283,
      .def_val = "2 NDEF2 0 NONE 1 OK 3 SNA",
      .sigs = sigs_643,
    },
    {
      .name = "MCU_speedLimitUnits",
      .address = 0x2F8,
      .def_val = "1 KPH 0 MPH",
      .sigs = sigs_760,
    },
    {
      .name = "MCU_userSpeedOffsetUnits",
      .address = 0x2F8,
      .def_val = "1 KPH 0 MPH",
      .sigs = sigs_760,
    },
    {
      .name = "BOOT_STATE",
      .address = 0x318,
      .def_val = "2 INIT 3 SNA 0 CLOSED 1 OPEN",
      .sigs = sigs_792,
    },
    {
      .name = "CERRD",
      .address = 0x318,
      .def_val = "1 CAN_ERROR_DETECT 0 NO_CAN_ERROR_DETECTED",
      .sigs = sigs_792,
    },
    {
      .name = "DAY",
      .address = 0x318,
      .def_val = "1 INIT 0 SNA",
      .sigs = sigs_792,
    },
    {
      .name = "DOOR_STATE_FL",
      .address = 0x318,
      .def_val = "2 INIT 3 SNA 0 CLOSED 1 OPEN",
      .sigs = sigs_792,
    },
    {
      .name = "DOOR_STATE_FR",
      .address = 0x318,
      .def_val = "2 INIT 3 SNA 0 CLOSED 1 OPEN",
      .sigs = sigs_792,
    },
    {
      .name = "DOOR_STATE_FrontTrunk",
      .address = 0x318,
      .def_val = "2 INIT 3 SNA 0 CLOSED 1 OPEN",
      .sigs = sigs_792,
    },
    {
      .name = "DOOR_STATE_RL",
      .address = 0x318,
      .def_val = "2 INIT 3 SNA 0 CLOSED 1 OPEN",
      .sigs = sigs_792,
    },
    {
      .name = "DOOR_STATE_RR",
      .address = 0x318,
      .def_val = "2 INIT 3 SNA 0 CLOSED 1 OPEN",
      .sigs = sigs_792,
    },
    {
      .name = "GTW_updateInProgress",
      .address = 0x318,
      .def_val = "1 IN_PROGRESS 2 IN_PROGRESS_NOT_USED 3 IN_PROGRESS_SNA 0 NOT_IN_PROGRESS",
      .sigs = sigs_792,
    },
    {
      .name = "Hour",
      .address = 0x318,
      .def_val = "30 INIT 31 SNA",
      .sigs = sigs_792,
    },
    {
      .name = "MCU_factoryMode",
      .address = 0x318,
      .def_val = "1 FACTORY_MODE 0 NORMAL_MODE",
      .sigs = sigs_792,
    },
    {
      .name = "MCU_transportModeOn",
      .address = 0x318,
      .def_val = "0 NORMAL_MODE",
      .sigs = sigs_792,
    },
    {
      .name = "MINUTE",
      .address = 0x318,
      .def_val = "62 INIT 63 SNA",
      .sigs = sigs_792,
    },
    {
      .name = "MONTH",
      .address = 0x318,
      .def_val = "1 INIT 15 SNA",
      .sigs = sigs_792,
    },
    {
      .name = "SECOND",
      .address = 0x318,
      .def_val = "62 INIT 63 SNA",
      .sigs = sigs_792,
    },
    {
      .name = "YEAR",
      .address = 0x318,
      .def_val = "126 INIT 127 SNA",
      .sigs = sigs_792,
    },
    {
      .name = "DI_aebState",
      .address = 0x368,
      .def_val = "2 ENABLED 4 FAULT 7 SNA 1 STANDBY 3 STANDSTILL 0 UNAVAILABLE",
      .sigs = sigs_872,
    },
    {
      .name = "DI_analogSpeed",
      .address = 0x368,
      .def_val = "4095 SNA",
      .sigs = sigs_872,
    },
    {
      .name = "DI_cruiseState",
      .address = 0x368,
      .def_val = "2 ENABLED 5 FAULT 0 OFF 4 OVERRIDE 7 PRE_CANCEL 6 PRE_FAULT 1 STANDBY 3 STANDSTILL",
      .sigs = sigs_872,
    },
    {
      .name = "DI_digitalSpeed",
      .address = 0x368,
      .def_val = "255 SNA",
      .sigs = sigs_872,
    },
    {
      .name = "DI_immobilizerState",
      .address = 0x368,
      .def_val = "2 AUTHENTICATING 3 DISARMED 6 FAULT 4 IDLE 0 INIT_SNA 1 REQUEST 5 RESET",
      .sigs = sigs_872,
    },
    {
      .name = "DI_speedUnits",
      .address = 0x368,
      .def_val = "1 KPH 0 MPH",
      .sigs = sigs_872,
    },
    {
      .name = "DI_state",
      .address = 0x368,
      .def_val = "3 ABORT 4 ENABLE 2 FAULT 1 STANDBY 0 UNAVAILABLE",
      .sigs = sigs_872,
    },
    {
      .name = "DI_systemState",
      .address = 0x368,
      .def_val = "3 ABORT 4 ENABLE 2 FAULT 1 STANDBY 0 UNAVAILABLE",
      .sigs = sigs_872,
    },
    {
      .name = "DI_vehicleHoldState",
      .address = 0x368,
      .def_val = "2 BLEND_IN 4 BLEND_OUT 6 FAULT 7 INIT 5 PARK 1 STANDBY 3 STANDSTILL 0 UNAVAILABLE",
      .sigs = sigs_872,
    },
    {
      .name = "EPAS_currentTuneMode",
      .address = 0x370,
      .def_val = "1 DM_COMFORT 3 DM_SPORT 2 DM_STANDARD 0 FAIL_SAFE_DEFAULT 4 RWD_COMFORT 6 RWD_SPORT 5 RWD_STANDARD 7 UNAVAILABLE",
      .sigs = sigs_880,
    },
    {
      .name = "EPAS_eacErrorCode",
      .address = 0x370,
      .def_val = "14 EAC_ERROR_EPB_INHIBIT 3 EAC_ERROR_HANDS_ON 7 EAC_ERROR_HIGH_ANGLE_RATE_REQ 9 EAC_ERROR_HIGH_ANGLE_RATE_SAFETY 6 EAC_ERROR_HIGH_ANGLE_REQ 8 EAC_ERROR_HIGH_ANGLE_SAFETY 10 EAC_ERROR_HIGH_MMOT_SAFETY 11 EAC_ERROR_HIGH_TORSION_SAFETY 0 EAC_ERROR_IDLE 12 EAC_ERROR_LOW_ASSIST 2 EAC_ERROR_MAX_SPEED 1 EAC_ERROR_MIN_SPEED 13 EAC_ERROR_PINION_VEL_DIFF 4 EAC_ERROR_TMP_FAULT 5 EAR_ERROR_MAX_STEER_DELTA 15 SNA",
      .sigs = sigs_880,
    },
    {
      .name = "EPAS_eacStatus",
      .address = 0x370,
      .def_val = "2 EAC_ACTIVE 1 EAC_AVAILABLE 3 EAC_FAULT 0 EAC_INHIBITED 4 SNA",
      .sigs = sigs_880,
    },
    {
      .name = "EPAS_handsOnLevel",
      .address = 0x370,
      .def_val = "0 0 1 1 2 2 3 3",
      .sigs = sigs_880,
    },
    {
      .name = "EPAS_steeringFault",
      .address = 0x370,
      .def_val = "1 FAULT 0 NO_FAULT",
      .sigs = sigs_880,
    },
    {
      .name = "EPAS_steeringRackForce",
      .address = 0x370,
      .def_val = "1022 NOT_IN_SPEC 1023 SNA",
      .sigs = sigs_880,
    },
    {
      .name = "EPAS_steeringReduced",
      .address = 0x370,
      .def_val = "0 NORMAL_ASSIST 1 REDUCED_ASSIST",
      .sigs = sigs_880,
    },
    {
      .name = "EPAS_torsionBarTorque",
      .address = 0x370,
      .def_val = "0 SEE_SPECIFICATION 4095 SNA 4094 UNDEFINABLE_DATA",
      .sigs = sigs_880,
    },
    {
      .name = "MCU_clusterReadyForDrive",
      .address = 0x388,
      .def_val = "0 NO_SNA 1 YES",
      .sigs = sigs_904,
    },
    {
      .name = "DAS_steeringAngleRequest",
      .address = 0x488,
      .def_val = "16384 ZERO_ANGLE",
      .sigs = sigs_1160,
    },
    {
      .name = "DAS_steeringControlType",
      .address = 0x488,
      .def_val = "1 ANGLE_CONTROL 3 DISABLED 0 NONE 2 RESERVED",
      .sigs = sigs_1160,
    },
    {
      .name = "DAS_steeringHapticRequest",
      .address = 0x488,
      .def_val = "1 ACTIVE 0 IDLE",
      .sigs = sigs_1160,
    },
};

}

const DBC tesla_can = {
  .name = "tesla_can",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(tesla_can)