#include "common_dbc.h"

namespace {

const Signal sigs_528[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_529[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_530[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_531[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_532[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_533[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_534[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_535[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_536[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_537[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_538[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_539[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_540[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_541[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_542[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_543[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_544[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_545[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_546[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_547[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_548[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_549[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_550[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_551[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_552[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_553[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_554[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_555[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_556[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_557[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_558[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_559[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "TRACK_A_0",
    .address = 0x210,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_528),
    .sigs = sigs_528,
  },
  {
    .name = "TRACK_A_1",
    .address = 0x211,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_529),
    .sigs = sigs_529,
  },
  {
    .name = "TRACK_A_2",
    .address = 0x212,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_530),
    .sigs = sigs_530,
  },
  {
    .name = "TRACK_A_3",
    .address = 0x213,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_531),
    .sigs = sigs_531,
  },
  {
    .name = "TRACK_A_4",
    .address = 0x214,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_532),
    .sigs = sigs_532,
  },
  {
    .name = "TRACK_A_5",
    .address = 0x215,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_533),
    .sigs = sigs_533,
  },
  {
    .name = "TRACK_A_6",
    .address = 0x216,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_534),
    .sigs = sigs_534,
  },
  {
    .name = "TRACK_A_7",
    .address = 0x217,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_535),
    .sigs = sigs_535,
  },
  {
    .name = "TRACK_A_8",
    .address = 0x218,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_536),
    .sigs = sigs_536,
  },
  {
    .name = "TRACK_A_9",
    .address = 0x219,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_537),
    .sigs = sigs_537,
  },
  {
    .name = "TRACK_A_10",
    .address = 0x21A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_538),
    .sigs = sigs_538,
  },
  {
    .name = "TRACK_A_11",
    .address = 0x21B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_539),
    .sigs = sigs_539,
  },
  {
    .name = "TRACK_A_12",
    .address = 0x21C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_540),
    .sigs = sigs_540,
  },
  {
    .name = "TRACK_A_13",
    .address = 0x21D,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_541),
    .sigs = sigs_541,
  },
  {
    .name = "TRACK_A_14",
    .address = 0x21E,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_542),
    .sigs = sigs_542,
  },
  {
    .name = "TRACK_A_15",
    .address = 0x21F,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_543),
    .sigs = sigs_543,
  },
  {
    .name = "TRACK_B_0",
    .address = 0x220,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_544),
    .sigs = sigs_544,
  },
  {
    .name = "TRACK_B_1",
    .address = 0x221,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_545),
    .sigs = sigs_545,
  },
  {
    .name = "TRACK_B_2",
    .address = 0x222,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_546),
    .sigs = sigs_546,
  },
  {
    .name = "TRACK_B_3",
    .address = 0x223,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_547),
    .sigs = sigs_547,
  },
  {
    .name = "TRACK_B_4",
    .address = 0x224,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_548),
    .sigs = sigs_548,
  },
  {
    .name = "TRACK_B_5",
    .address = 0x225,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_549),
    .sigs = sigs_549,
  },
  {
    .name = "TRACK_B_6",
    .address = 0x226,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_550),
    .sigs = sigs_550,
  },
  {
    .name = "TRACK_B_7",
    .address = 0x227,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_551),
    .sigs = sigs_551,
  },
  {
    .name = "TRACK_B_8",
    .address = 0x228,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_552),
    .sigs = sigs_552,
  },
  {
    .name = "TRACK_B_9",
    .address = 0x229,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_553),
    .sigs = sigs_553,
  },
  {
    .name = "TRACK_B_10",
    .address = 0x22A,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_554),
    .sigs = sigs_554,
  },
  {
    .name = "TRACK_B_11",
    .address = 0x22B,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_555),
    .sigs = sigs_555,
  },
  {
    .name = "TRACK_B_12",
    .address = 0x22C,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_556),
    .sigs = sigs_556,
  },
  {
    .name = "TRACK_B_13",
    .address = 0x22D,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_557),
    .sigs = sigs_557,
  },
  {
    .name = "TRACK_B_14",
    .address = 0x22E,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_558),
    .sigs = sigs_558,
  },
  {
    .name = "TRACK_B_15",
    .address = 0x22F,
    .size = 6,
    .num_sigs = ARRAYSIZE(sigs_559),
    .sigs = sigs_559,
  },
};

const Val vals[] = {
};

}

const DBC toyota_adas = {
  .name = "toyota_adas",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(toyota_adas)