#include "common_dbc.h"

namespace {

const Signal sigs_36[] = {
    {
      .name = "ACC_LAT_CLEAN",
      .b1 = 5,
      .b2 = 11,
      .bo = 48,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_FRONT_BACK_1",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_FRONT_BACK_2",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_LATERAL",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_37[] = {
    {
      .name = "STEER_ANGLE",
      .b1 = 5,
      .b2 = 11,
      .bo = 48,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "STEER_DIRECTION",
      .b1 = 4,
      .b2 = 1,
      .bo = 59,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_1",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_4",
      .b1 = 45,
      .b2 = 2,
      .bo = 17,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_2",
      .b1 = 43,
      .b2 = 2,
      .bo = 19,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_3",
      .b1 = 41,
      .b2 = 2,
      .bo = 21,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_170[] = {
    {
      .name = "FRONT_RIGHT_WHEEL_SPEED",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 0.01,
      .offset = -67.67,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "FRONT_LEFT_WHEEL_SPEED",
      .b1 = 16,
      .b2 = 16,
      .bo = 32,
      .is_signed = false,
      .factor = 0.01,
      .offset = -67.67,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REAR_RIGHT_WHEEL_SPEED",
      .b1 = 32,
      .b2 = 16,
      .bo = 16,
      .is_signed = false,
      .factor = 0.01,
      .offset = -67.67,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REAR_LEFT_WHEEL_SPEED",
      .b1 = 48,
      .b2 = 16,
      .bo = 0,
      .is_signed = false,
      .factor = 0.01,
      .offset = -67.67,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_180[] = {
    {
      .name = "WIERD_STUFF",
      .b1 = 8,
      .b2 = 2,
      .bo = 54,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MAYBE_DISTANCE_MOD_256",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VEHICLE_SPEED",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SPEED_MOD_256",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_186[] = {
    {
      .name = "NEW_SIGNAL_2",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_426[] = {
    {
      .name = "CONSTANT",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_452[] = {
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "ENGINE_RPM",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DIFFERENT_EACH_RIDE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "A_DECREASING_VALUE",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_608[] = {
    {
      .name = "VERY_SMALL_SIGNAL1",
      .b1 = 7,
      .b2 = 1,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VERY_SMALL_SIGNAL2",
      .b1 = 63,
      .b2 = 1,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_705[] = {
    {
      .name = "NOT_ACCELERATING_PEDAL",
      .b1 = 3,
      .b2 = 1,
      .bo = 60,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_PEDAL_MEAN",
      .b1 = 8,
      .b2 = 16,
      .bo = 40,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_COMMAND",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEGATIVE_COMMAND_OFFSET",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ACC_PEDAL_SENSOR",
      .b1 = 48,
      .b2 = 16,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_896[] = {
    {
      .name = "NEW_SIGNAL_1",
      .b1 = 48,
      .b2 = 8,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_906[] = {
    {
      .name = "MOVEMENT_START_TRIGGER",
      .b1 = 7,
      .b2 = 1,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_3",
      .b1 = 6,
      .b2 = 1,
      .bo = 57,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_2",
      .b1 = 5,
      .b2 = 1,
      .bo = 58,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_1",
      .b1 = 4,
      .b2 = 1,
      .bo = 59,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MAY_CONTAIN_LIGHTS",
      .b1 = 0,
      .b2 = 4,
      .bo = 60,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_928[] = {
    {
      .name = "NEW_SIGNAL_4",
      .b1 = 2,
      .b2 = 6,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_1",
      .b1 = 10,
      .b2 = 6,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_3",
      .b1 = 41,
      .b2 = 7,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_2",
      .b1 = 59,
      .b2 = 5,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_944[] = {
    {
      .name = "LONG_TERM_SIGN",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_945[] = {
    {
      .name = "BETWEEN_RIDES",
      .b1 = 31,
      .b2 = 1,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_947[] = {
    {
      .name = "LOW_RES_RPM",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LOW_RES_ACC_PEDAL",
      .b1 = 16,
      .b2 = 7,
      .bo = 41,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_955[] = {
    {
      .name = "IS_BRAKING_2",
      .b1 = 7,
      .b2 = 1,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "MAYBE_CLUTCH",
      .b1 = 10,
      .b2 = 1,
      .bo = 53,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ENGINE_TEMPERATURE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_979[] = {
    {
      .name = "VERY_LRES_ACC",
      .b1 = 0,
      .b2 = 16,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1090[] = {
    {
      .name = "NEW_SIGNAL_1",
      .b1 = 10,
      .b2 = 2,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_2",
      .b1 = 16,
      .b2 = 1,
      .bo = 47,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1552[] = {
    {
      .name = "NEW_SIGNAL_1",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SPEED_LOWRES",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1553[] = {
    {
      .name = "TOTAL_DISTANCE",
      .b1 = 48,
      .b2 = 16,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1555[] = {
    {
      .name = "BETWEEN_RIDES",
      .b1 = 16,
      .b2 = 1,
      .bo = 47,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1568[] = {
    {
      .name = "NEW_SIGNAL_1",
      .b1 = 3,
      .b2 = 1,
      .bo = 60,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TRIGGER_BOOL",
      .b1 = 8,
      .b2 = 1,
      .bo = 55,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "KEY_ACC",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "KEY_ON",
      .b1 = 34,
      .b2 = 1,
      .bo = 29,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_TRUNK",
      .b1 = 41,
      .b2 = 1,
      .bo = 22,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = true,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_RIGHT",
      .b1 = 43,
      .b2 = 1,
      .bo = 20,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOOR_LEFT",
      .b1 = 42,
      .b2 = 1,
      .bo = 21,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "KEY_INSERT",
      .b1 = 41,
      .b2 = 1,
      .bo = 22,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "HANDBRAKE",
      .b1 = 59,
      .b2 = 1,
      .bo = 4,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DRIVER_SEATBELT",
      .b1 = 57,
      .b2 = 1,
      .bo = 6,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NOT_ON",
      .b1 = 56,
      .b2 = 1,
      .bo = 7,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1592[] = {
    {
      .name = "DOORS_LOCKED1",
      .b1 = 23,
      .b2 = 1,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "DOORS_LOCKED2",
      .b1 = 19,
      .b2 = 1,
      .bo = 44,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1595[] = {
    {
      .name = "BETWEEN_RIDES",
      .b1 = 0,
      .b2 = 32,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "TIME_ON",
      .b1 = 48,
      .b2 = 16,
      .bo = 0,
      .is_signed = false,
      .factor = 0.1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_1600[] = {
    {
      .name = "CHANGES_EACH_RIDE",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "INCREASING_VALUE_FUEL",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "ACCELERATIONS",
    .address = 0x24,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_36),
    .sigs = sigs_36,
  },
  {
    .name = "STEERING",
    .address = 0x25,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_37),
    .sigs = sigs_37,
  },
  {
    .name = "WHEELS_SPEEDS",
    .address = 0xAA,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_170),
    .sigs = sigs_170,
  },
  {
    .name = "VEHICLE_DYNAMICS",
    .address = 0xB4,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_180),
    .sigs = sigs_180,
  },
  {
    .name = "NEW_MSG_9",
    .address = 0xBA,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_186),
    .sigs = sigs_186,
  },
  {
    .name = "NEW_MSG_5",
    .address = 0x1AA,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_426),
    .sigs = sigs_426,
  },
  {
    .name = "ENGINE",
    .address = 0x1C4,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_452),
    .sigs = sigs_452,
  },
  {
    .name = "NEW_MSG_6",
    .address = 0x260,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_608),
    .sigs = sigs_608,
  },
  {
    .name = "COMMAND",
    .address = 0x2C1,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_705),
    .sigs = sigs_705,
  },
  {
    .name = "LONG_TERM_2",
    .address = 0x380,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_896),
    .sigs = sigs_896,
  },
  {
    .name = "BOOLS",
    .address = 0x38A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_906),
    .sigs = sigs_906,
  },
  {
    .name = "STEER2_MAYBE",
    .address = 0x3A0,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_928),
    .sigs = sigs_928,
  },
  {
    .name = "LONG_TERM_MSG",
    .address = 0x3B0,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_944),
    .sigs = sigs_944,
  },
  {
    .name = "BETWEEN_RIDES_CHANGES_2",
    .address = 0x3B1,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_945),
    .sigs = sigs_945,
  },
  {
    .name = "LOW_RES_INDICATORS",
    .address = 0x3B3,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_947),
    .sigs = sigs_947,
  },
  {
    .name = "BRAKING_PLUS_OTHER",
    .address = 0x3BB,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_955),
    .sigs = sigs_955,
  },
  {
    .name = "LOW_RES_ACCELERATOR",
    .address = 0x3D3,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_979),
    .sigs = sigs_979,
  },
  {
    .name = "ASYNC_MSG_ACK",
    .address = 0x442,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1090),
    .sigs = sigs_1090,
  },
  {
    .name = "CONTAINS_LRES_SPEED",
    .address = 0x610,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1552),
    .sigs = sigs_1552,
  },
  {
    .name = "TOTAL_DIST",
    .address = 0x611,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1553),
    .sigs = sigs_1553,
  },
  {
    .name = "BETWEEN_RIDES_CHANGE_1",
    .address = 0x613,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1555),
    .sigs = sigs_1555,
  },
  {
    .name = "DOORS",
    .address = 0x620,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1568),
    .sigs = sigs_1568,
  },
  {
    .name = "NEW_MSG_14",
    .address = 0x638,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1592),
    .sigs = sigs_1592,
  },
  {
    .name = "CONTAINS_TIME",
    .address = 0x63B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1595),
    .sigs = sigs_1595,
  },
  {
    .name = "SLOW_VARIABLE_INFOS",
    .address = 0x640,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_1600),
    .sigs = sigs_1600,
  },
};

const Val vals[] = {
};

}

const DBC toyota_iQ_2009_can = {
  .name = "toyota_iQ_2009_can",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(toyota_iQ_2009_can)