#include "common_dbc.h"

namespace {

const Signal sigs_384[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_385[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_386[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_387[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_388[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_389[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_390[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_391[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_392[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_393[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_394[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_395[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_396[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_397[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_398[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_399[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "LONG_DIST",
      .b1 = 8,
      .b2 = 13,
      .bo = 43,
      .is_signed = false,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "LAT_DIST",
      .b1 = 24,
      .b2 = 11,
      .bo = 29,
      .is_signed = true,
      .factor = 0.04,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_TRACK",
      .b1 = 35,
      .b2 = 1,
      .bo = 28,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "REL_SPEED",
      .b1 = 40,
      .b2 = 12,
      .bo = 12,
      .is_signed = true,
      .factor = 0.025,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "VALID",
      .b1 = 55,
      .b2 = 1,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_400[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_401[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_402[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_403[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_404[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_405[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_406[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_407[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_408[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_409[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_410[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_411[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_412[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_413[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_414[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_415[] = {
    {
      .name = "COUNTER",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "CHECKSUM",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::TOYOTA_CHECKSUM,
    },
    {
      .name = "REL_ACCEL",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = true,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "SCORE",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_576[] = {
    {
      .name = "NEW_SIGNAL_1",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_2",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};
const Signal sigs_577[] = {
    {
      .name = "NEW_SIGNAL_1",
      .b1 = 8,
      .b2 = 7,
      .bo = 49,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "NEW_SIGNAL_2",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "TRACK_A_0",
    .address = 0x180,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_384),
    .sigs = sigs_384,
  },
  {
    .name = "TRACK_A_1",
    .address = 0x181,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_385),
    .sigs = sigs_385,
  },
  {
    .name = "TRACK_A_2",
    .address = 0x182,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_386),
    .sigs = sigs_386,
  },
  {
    .name = "TRACK_A_3",
    .address = 0x183,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_387),
    .sigs = sigs_387,
  },
  {
    .name = "TRACK_A_4",
    .address = 0x184,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_388),
    .sigs = sigs_388,
  },
  {
    .name = "TRACK_A_5",
    .address = 0x185,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_389),
    .sigs = sigs_389,
  },
  {
    .name = "TRACK_A_6",
    .address = 0x186,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_390),
    .sigs = sigs_390,
  },
  {
    .name = "TRACK_A_7",
    .address = 0x187,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_391),
    .sigs = sigs_391,
  },
  {
    .name = "TRACK_A_8",
    .address = 0x188,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_392),
    .sigs = sigs_392,
  },
  {
    .name = "TRACK_A_9",
    .address = 0x189,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_393),
    .sigs = sigs_393,
  },
  {
    .name = "TRACK_A_10",
    .address = 0x18A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_394),
    .sigs = sigs_394,
  },
  {
    .name = "TRACK_A_11",
    .address = 0x18B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_395),
    .sigs = sigs_395,
  },
  {
    .name = "TRACK_A_12",
    .address = 0x18C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_396),
    .sigs = sigs_396,
  },
  {
    .name = "TRACK_A_13",
    .address = 0x18D,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_397),
    .sigs = sigs_397,
  },
  {
    .name = "TRACK_A_14",
    .address = 0x18E,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_398),
    .sigs = sigs_398,
  },
  {
    .name = "TRACK_A_15",
    .address = 0x18F,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_399),
    .sigs = sigs_399,
  },
  {
    .name = "TRACK_B_0",
    .address = 0x190,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_400),
    .sigs = sigs_400,
  },
  {
    .name = "TRACK_B_1",
    .address = 0x191,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_401),
    .sigs = sigs_401,
  },
  {
    .name = "TRACK_B_2",
    .address = 0x192,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_402),
    .sigs = sigs_402,
  },
  {
    .name = "TRACK_B_3",
    .address = 0x193,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_403),
    .sigs = sigs_403,
  },
  {
    .name = "TRACK_B_4",
    .address = 0x194,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_404),
    .sigs = sigs_404,
  },
  {
    .name = "TRACK_B_5",
    .address = 0x195,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_405),
    .sigs = sigs_405,
  },
  {
    .name = "TRACK_B_6",
    .address = 0x196,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_406),
    .sigs = sigs_406,
  },
  {
    .name = "TRACK_B_7",
    .address = 0x197,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_407),
    .sigs = sigs_407,
  },
  {
    .name = "TRACK_B_8",
    .address = 0x198,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_408),
    .sigs = sigs_408,
  },
  {
    .name = "TRACK_B_9",
    .address = 0x199,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_409),
    .sigs = sigs_409,
  },
  {
    .name = "TRACK_B_10",
    .address = 0x19A,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_410),
    .sigs = sigs_410,
  },
  {
    .name = "TRACK_B_11",
    .address = 0x19B,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_411),
    .sigs = sigs_411,
  },
  {
    .name = "TRACK_B_12",
    .address = 0x19C,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_412),
    .sigs = sigs_412,
  },
  {
    .name = "TRACK_B_13",
    .address = 0x19D,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_413),
    .sigs = sigs_413,
  },
  {
    .name = "TRACK_B_14",
    .address = 0x19E,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_414),
    .sigs = sigs_414,
  },
  {
    .name = "TRACK_B_15",
    .address = 0x19F,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_415),
    .sigs = sigs_415,
  },
  {
    .name = "NEW_MSG_1",
    .address = 0x240,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_576),
    .sigs = sigs_576,
  },
  {
    .name = "NEW_MSG_2",
    .address = 0x241,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_577),
    .sigs = sigs_577,
  },
};

const Val vals[] = {
};

}

const DBC toyota_tss2_adas = {
  .name = "toyota_tss2_adas",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(toyota_tss2_adas)