#pragma once

#include <map>
#include <string>
#include <vector>

#include "cereal/gen/cpp/log.capnp.h"
#include "tools/replay/util.h"

using OldOnroadEventName = cereal::OnroadEventDEPRECATED::EventName;
using NewOnroadEventName = cereal::OnroadEvent::EventName;

#define MAP_ONROAD_EVENT_NAME(name) {OldOnroadEventName::name, NewOnroadEventName::name}

static const std::map<OldOnroadEventName, NewOnroadEventName> ONROAD_EVENT_NAME_MAP = {
  MAP_ONROAD_EVENT_NAME(CAN_ERROR),
  MAP_ONROAD_EVENT_NAME(STEER_UNAVAILABLE),
  MAP_ONROAD_EVENT_NAME(WRONG_GEAR),
  MAP_ONROAD_EVENT_NAME(DOOR_OPEN),
  MAP_ONROAD_EVENT_NAME(SEATBELT_NOT_LATCHED),
  MAP_ONROAD_EVENT_NAME(ESP_DISABLED),
  MAP_ONROAD_EVENT_NAME(WRONG_CAR_MODE),
  MAP_ONROAD_EVENT_NAME(STEER_TEMP_UNAVAILABLE),
  MAP_ONROAD_EVENT_NAME(REVERSE_GEAR),
  MAP_ONROAD_EVENT_NAME(BUTTON_CANCEL),
  MAP_ONROAD_EVENT_NAME(BUTTON_ENABLE),
  MAP_ONROAD_EVENT_NAME(PEDAL_PRESSED),
  MAP_ONROAD_EVENT_NAME(CRUISE_DISABLED),
  MAP_ONROAD_EVENT_NAME(SPEED_TOO_LOW),
  MAP_ONROAD_EVENT_NAME(OUT_OF_SPACE),
  MAP_ONROAD_EVENT_NAME(OVERHEAT),
  MAP_ONROAD_EVENT_NAME(CALIBRATION_INCOMPLETE),
  MAP_ONROAD_EVENT_NAME(CALIBRATION_INVALID),
  MAP_ONROAD_EVENT_NAME(CONTROLS_MISMATCH),
  MAP_ONROAD_EVENT_NAME(PCM_ENABLE),
  MAP_ONROAD_EVENT_NAME(PCM_DISABLE),
  MAP_ONROAD_EVENT_NAME(RADAR_FAULT),
  MAP_ONROAD_EVENT_NAME(BRAKE_HOLD),
  MAP_ONROAD_EVENT_NAME(PARK_BRAKE),
  MAP_ONROAD_EVENT_NAME(MANUAL_RESTART),
  MAP_ONROAD_EVENT_NAME(JOYSTICK_DEBUG),
  MAP_ONROAD_EVENT_NAME(STEER_TEMP_UNAVAILABLE_SILENT),
  MAP_ONROAD_EVENT_NAME(RESUME_REQUIRED),
  MAP_ONROAD_EVENT_NAME(PRE_DRIVER_DISTRACTED),
  MAP_ONROAD_EVENT_NAME(PROMPT_DRIVER_DISTRACTED),
  MAP_ONROAD_EVENT_NAME(DRIVER_DISTRACTED),
  MAP_ONROAD_EVENT_NAME(PRE_DRIVER_UNRESPONSIVE),
  MAP_ONROAD_EVENT_NAME(PROMPT_DRIVER_UNRESPONSIVE),
  MAP_ONROAD_EVENT_NAME(DRIVER_UNRESPONSIVE),
  MAP_ONROAD_EVENT_NAME(BELOW_STEER_SPEED),
  MAP_ONROAD_EVENT_NAME(LOW_BATTERY),
  MAP_ONROAD_EVENT_NAME(PARAMSD_TEMPORARY_ERROR),
  MAP_ONROAD_EVENT_NAME(ACC_FAULTED),
  MAP_ONROAD_EVENT_NAME(SENSOR_DATA_INVALID),
  MAP_ONROAD_EVENT_NAME(COMM_ISSUE),
  MAP_ONROAD_EVENT_NAME(TOO_DISTRACTED),
  MAP_ONROAD_EVENT_NAME(POSENET_INVALID),
  MAP_ONROAD_EVENT_NAME(PRE_LANE_CHANGE_LEFT),
  MAP_ONROAD_EVENT_NAME(PRE_LANE_CHANGE_RIGHT),
  MAP_ONROAD_EVENT_NAME(LANE_CHANGE),
  MAP_ONROAD_EVENT_NAME(LOW_MEMORY),
  MAP_ONROAD_EVENT_NAME(STOCK_AEB),
  MAP_ONROAD_EVENT_NAME(LDW),
  MAP_ONROAD_EVENT_NAME(CAR_UNRECOGNIZED),
  MAP_ONROAD_EVENT_NAME(INVALID_LKAS_SETTING),
  MAP_ONROAD_EVENT_NAME(SPEED_TOO_HIGH),
  MAP_ONROAD_EVENT_NAME(LANE_CHANGE_BLOCKED),
  MAP_ONROAD_EVENT_NAME(RELAY_MALFUNCTION),
  MAP_ONROAD_EVENT_NAME(PRE_ENABLE_STANDSTILL),
  MAP_ONROAD_EVENT_NAME(STOCK_FCW),
  MAP_ONROAD_EVENT_NAME(STARTUP),
  MAP_ONROAD_EVENT_NAME(STARTUP_NO_CAR),
  MAP_ONROAD_EVENT_NAME(STARTUP_NO_CONTROL),
  MAP_ONROAD_EVENT_NAME(STARTUP_MASTER),
  MAP_ONROAD_EVENT_NAME(FCW),
  MAP_ONROAD_EVENT_NAME(STEER_SATURATED),
  MAP_ONROAD_EVENT_NAME(BELOW_ENGAGE_SPEED),
  MAP_ONROAD_EVENT_NAME(NO_GPS),
  MAP_ONROAD_EVENT_NAME(WRONG_CRUISE_MODE),
  MAP_ONROAD_EVENT_NAME(MODELD_LAGGING),
  MAP_ONROAD_EVENT_NAME(DEVICE_FALLING),
  MAP_ONROAD_EVENT_NAME(FAN_MALFUNCTION),
  MAP_ONROAD_EVENT_NAME(CAMERA_MALFUNCTION),
  MAP_ONROAD_EVENT_NAME(PROCESS_NOT_RUNNING),
  MAP_ONROAD_EVENT_NAME(DASHCAM_MODE),
  MAP_ONROAD_EVENT_NAME(SELFDRIVE_INITIALIZING),
  MAP_ONROAD_EVENT_NAME(USB_ERROR),
  MAP_ONROAD_EVENT_NAME(LOCATIOND_TEMPORARY_ERROR),
  MAP_ONROAD_EVENT_NAME(CRUISE_MISMATCH),
  MAP_ONROAD_EVENT_NAME(GAS_PRESSED_OVERRIDE),
  MAP_ONROAD_EVENT_NAME(COMM_ISSUE_AVG_FREQ),
  MAP_ONROAD_EVENT_NAME(CAMERA_FRAME_RATE),
  MAP_ONROAD_EVENT_NAME(CAN_BUS_MISSING),
  MAP_ONROAD_EVENT_NAME(SELFDRIVED_LAGGING),
  MAP_ONROAD_EVENT_NAME(RESUME_BLOCKED),
  MAP_ONROAD_EVENT_NAME(STEER_OVERRIDE),
  MAP_ONROAD_EVENT_NAME(STEER_TIME_LIMIT),
  MAP_ONROAD_EVENT_NAME(VEHICLE_SENSORS_INVALID),
  MAP_ONROAD_EVENT_NAME(CALIBRATION_RECALIBRATING),
  MAP_ONROAD_EVENT_NAME(LOCATIOND_PERMANENT_ERROR),
  MAP_ONROAD_EVENT_NAME(PARAMSD_PERMANENT_ERROR),
  MAP_ONROAD_EVENT_NAME(ACTUATORS_API_UNAVAILABLE),
  MAP_ONROAD_EVENT_NAME(ESP_ACTIVE),
  MAP_ONROAD_EVENT_NAME(PERSONALITY_CHANGED),
  MAP_ONROAD_EVENT_NAME(AEB),
  MAP_ONROAD_EVENT_NAME(LONGITUDINAL_MANEUVER),
  MAP_ONROAD_EVENT_NAME(STARTUP_NO_SEC_OC_KEY),
};

const CameraType ALL_CAMERAS[] = {RoadCam, DriverCam, WideRoadCam};
const int MAX_CAMERAS = std::size(ALL_CAMERAS);

class Event {
public:
  Event(cereal::Event::Which which, uint64_t mono_time, const kj::ArrayPtr<const capnp::word> &data, int eidx_segnum = -1)
    : which(which), mono_time(mono_time), data(data), eidx_segnum(eidx_segnum) {}

  bool operator<(const Event &other) const {
    return mono_time < other.mono_time || (mono_time == other.mono_time && which < other.which);
  }

  uint64_t mono_time;
  cereal::Event::Which which;
  kj::ArrayPtr<const capnp::word> data;
  int32_t eidx_segnum;
};

class LogReader {
public:
  LogReader(const std::vector<bool> &filters = {}) { filters_ = filters; }
  bool load(const std::string &url, std::atomic<bool> *abort = nullptr,
            bool local_cache = false, int chunk_size = -1, int retries = 0);
  bool load(const char *data, size_t size, std::atomic<bool> *abort = nullptr);
  std::vector<Event> events;

private:
  void migrateOldEvents();
  void migrateControlsState(const kj::ArrayPtr<const capnp::word> &event_data);
  void migrateOnroadEvents(const kj::ArrayPtr<const capnp::word> &event_data);

  std::string raw_;
  bool requires_controls_migration = true;
  std::vector<bool> filters_;
  MonotonicBuffer buffer_{1024 * 1024};
};
