#!/bin/sh

if [ -f /EON ]; then
  export LD_LIBRARY_PATH="/system/lib64:$LD_LIBRARY_PATH"
  exec ./android/spinner/spinner "$1"
else
  if [ -f /TICI ] && [ ! -f qt/spinner ]; then
    cp qt/spinner_aarch64 qt/spinner
  fi

  exec ./qt/spinner "$1"
fi
