Import('env', 'common', 'cereal', 'messaging', 'libkf', 'transformations')

loc_libs = [cereal, messaging, 'zmq', common, 'capnp', 'kj', 'pthread']

ekf_sym_cc = env.SharedObject("#rednose/helpers/ekf_sym.cc")
locationd_sources = ["locationd.cc", "models/live_kf.cc", ekf_sym_cc]
lenv = env.Clone()
lenv["_LIBFLAGS"] += f' {libkf[0].get_labspath()}'
locationd = lenv.Program("locationd", locationd_sources, LIBS=loc_libs + transformations)
lenv.Depends(locationd, libkf)