repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-ast
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0
    hooks:
    -   id: mypy
        additional_dependencies: ['numpy']
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
    - id: ruff
