######################################################################
# Automatically generated by qmake (3.0) Thu Oct 31 16:05:48 2019
######################################################################

QT += testlib
TEMPLATE = app
TARGET = test
INCLUDEPATH += . ../

# Input
SOURCES += TestFrameReader.cpp ../../clib/FrameReader.cpp
HEADERS = TestFrameReader.hpp ../../clib/FrameReader.hpp

CONFIG += c++14

LIBS += -lavformat -lavcodec -lavutil -lswscale
