import subprocess
Import('env', 'common', 'cereal', 'messaging', 'cython_dependencies', 'arch')

env.Program('boardd', ['boardd.cc', 'panda.cc', 'pigeon.cc'], LIBS=['usb-1.0', common, cereal, messaging, 'pthread', 'zmq', 'capnp', 'kj'])
env.Library('libcan_list_to_can_capnp', ['can_list_to_can_capnp.cc'])

envB = env.Clone()
added_libs = []
if arch == "Darwin":
  envB["LINKFLAGS"]=["-bundle", "-undefined", "dynamic_lookup"]
elif arch == "aarch64":
  envB["LINKFLAGS"]=["-shared"]

  Import("python_path")
  added_libs.append(python_path.split("/")[-1])
else:
  envB["LINKFLAGS"]=["-pthread", "-shared"]

envB.Cython('boardd_api_impl.cpp', 'boardd_api_impl.pyx')

envB.Program('boardd_api_impl.so', 'boardd_api_impl.cpp', LIBS=["can_list_to_can_capnp", 'capnp', 'kj'] + added_libs)
