Import('env', 'envCython', 'common', 'cereal', 'messaging')

libs = ['usb-1.0', common, cereal, messaging, 'pthread', 'zmq', 'capnp', 'kj']

if GetOption('test'):
  env.Program('tests/panda_flashing_test/flash_panda', ['tests/panda_flashing_test/flash_panda.cc', 'panda.cc', 'panda_dfu.cc', 'panda_flashing.cc'], LIBS=libs)

env.Program('boardd', ['boardd.cc', 'panda.cc', 'panda_dfu.cc', 'panda_flashing.cc', 'pigeon.cc'], LIBS=libs)
env.Library('libcan_list_to_can_capnp', ['can_list_to_can_capnp.cc'])

envCython.Program('boardd_api_impl.so', 'boardd_api_impl.pyx', LIBS=["can_list_to_can_capnp", 'capnp', 'kj'] + envCython["LIBS"])
