Import('env', 'arch', 'common', 'messaging')

sensors = [
  'sensors/i2c_sensor.cc',
  'sensors/lsm6ds3_accel.cc',
  'sensors/lsm6ds3_gyro.cc',
  'sensors/lsm6ds3_temp.cc',
  'sensors/mmc5603nj_magn.cc',
]
libs = [common, messaging, 'pthread']
if arch == "larch64":
  libs.append('i2c')
env.Program('sensord', ['sensors_qcom2.cc'] + sensors, LIBS=libs)
