Import('env', 'envCython')

import numpy as np

transformations = env.Library('transformations', ['orientation.cc', 'coordinates.cc'])

envCython.Append(CPPPATH=[np.get_include()])
transformations_python = envCython.SharedLibrary('transformations', ['transformations_module.cc'],
                                                 LIBS=[transformations],
                                                 SHLIBPREFIX="")
Export('transformations', 'transformations_python')
