#!/bin/bash

set -euo pipefail

source "common.sh"

function lssegs() {
  ls "/data/media/0/realdata" | grep '^[0-9]' | grep -v '.*sh' | grep -v 'hevc' | grep -v mp4
}
function lsroutes() {
  lssegs | sed -E 's/^(.*)--(.*)--(.*)$/\1--\2/g' | uniq
}

ls "/data/media/0/realdata" | get_routes | sort -V
