# distutils: language = c++
# cython: language_level = 3

cdef extern from "selfdrive/common/vision_defs.h":
    cdef int ROAD_CAM_FRAME_WIDTH
    cdef int ROAD_CAM_FRAME_HEIGHT
    cdef int DRIVER_CAM_FRAME_WIDTH
    cdef int DRIVER_CAM_FRAME_HEIGHT
    cdef int SCREEN_WIDTH
    cdef int SCREEN_HEIGHT

    cdef int EON_ROAD_CAM_FRAME_WIDTH 
    cdef int EON_ROAD_CAM_FRAME_HEIGHT
    cdef int EON_DRIVER_CAM_FRAME_WIDTH
    cdef int EON_DRIVER_CAM_FRAME_HEIGHT
    cdef int EON_SCREEN_WIDTH
    cdef int EON_SCREEN_HEIGHT

    cdef int TICI_FRAME_WIDTH
    cdef int TICI_FRAME_HEIGHT
    cdef int TICI_SCREEN_WIDTH
    cdef int TICI_SCREEN_HEIGHT

ROAD_CAM_FRAME_SIZE = (ROAD_CAM_FRAME_WIDTH, ROAD_CAM_FRAME_HEIGHT)
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
EON_ROAD_CAM_FRAME_SIZE = (EON_ROAD_CAM_FRAME_WIDTH, EON_ROAD_CAM_FRAME_HEIGHT)
EON_DRIVER_CAM_FRAME_SIZE = (EON_DRIVER_CAM_FRAME_WIDTH, EON_DRIVER_CAM_FRAME_HEIGHT)
EON_SCREEN_SIZE = (EON_SCREEN_WIDTH, EON_SCREEN_HEIGHT)
TICI_FRAME_SIZE = (TICI_FRAME_WIDTH, TICI_FRAME_HEIGHT)
TICI_SCREEN_SIZE = (TICI_SCREEN_WIDTH, TICI_SCREEN_HEIGHT)

