widgets_src = [
  "../../sunnypilot/selfdrive/ui/ui.cc",
  "../../sunnypilot/selfdrive/ui/qt/window.cc",
  "../../sunnypilot/selfdrive/ui/qt/widgets/controls.cc",
  "../../sunnypilot/selfdrive/ui/qt/widgets/drive_stats.cc",
  "../../sunnypilot/selfdrive/ui/qt/widgets/scrollview.cc",
  "../../sunnypilot/selfdrive/ui/qt/widgets/toggle.cc",
]

qt_src = [
  "../../sunnypilot/selfdrive/ui/qt/home.cc",
  "../../sunnypilot/selfdrive/ui/qt/sidebar.cc",
  "../../sunnypilot/selfdrive/ui/qt/offroad/settings/onboarding.cc",
  "../../sunnypilot/selfdrive/ui/qt/offroad/settings/settings.cc",
  "../../sunnypilot/selfdrive/ui/qt/onroad/onroad_home.cc",
]

sp_widgets_src = widgets_src
sp_qt_src = qt_src

Export('sp_widgets_src', 'sp_qt_src')
