Import('env', 'interface_dir')

qp_files = [
    Glob("SRC/*.cpp"),
    Glob("SRC/EXTRAS/*.cpp"),
]

cpp_path = [
    ".",
    "INCLUDE",
    "INCLUDE/EXTRAS",
    "SRC/",
    interface_dir,
]

env.Library('qpoases', qp_files,  CPPPATH=cpp_path)
