#!/bin/sh
if [ -d /system ]; then
  export LD_LIBRARY_PATH="/data/pythonpath/phonelibs/snpe/aarch64/:$LD_LIBRARY_PATH"
  export ADSP_LIBRARY_PATH="/data/pythonpath/phonelibs/snpe/aarch64/"
else
  export LD_LIBRARY_PATH="/data/pythonpath/phonelibs/snpe/larch64:$HOME/openpilot/phonelibs/snpe/x86_64-linux-clang:$LD_LIBRARY_PATH"
  export ADSP_LIBRARY_PATH="/data/pythonpath/phonelibs/snpe/larch64/"
fi

exec ./_dmonitoringmodeld

