#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
cd "$DIR/../../"

if [ -f "$DIR/libthneed.so" ]; then
  export LD_PRELOAD="$DIR/libthneed.so"
fi

exec "$DIR/modeld.py" "$@"
