#pragma once

#include <string_view>
#include <utility>

inline constexpr std::pair<std::string_view, std::string_view> kCarFingerprintToDbc[] = {
  {"ACURA ILX 2016", "acura_ilx_2016_can_generated"},
  {"ACURA ILX 2016 ACURAWATCH PLUS", "acura_ilx_2016_can_generated"},
  {"ACURA RDX 2018", "acura_rdx_2018_can_generated"},
  {"ACURA RDX 2018 ACURAWATCH PLUS", "acura_rdx_2018_can_generated"},
  {"ACURA RDX 2020", "acura_rdx_2020_can_generated"},
  {"ACURA RDX 2020 TECH", "acura_rdx_2020_can_generated"},
  {"ACURA_ILX", "acura_ilx_2016_can_generated"},
  {"ACURA_MDX_4G_MMR", "honda_common_canfd_generated"},
  {"ACURA_RDX", "acura_rdx_2018_can_generated"},
  {"ACURA_RDX_3G", "acura_rdx_2020_can_generated"},
  {"ACURA_TLX_2G", "honda_civic_hatchback_ex_2017_can_generated"},
  {"ACURA_TLX_2G_MMR", "honda_common_canfd_generated"},
  {"AUDI A3", "vw_mqb"},
  {"AUDI A3 3RD GEN", "vw_mqb"},
  {"AUDI Q2 1ST GEN", "vw_mqb"},
  {"AUDI Q3 2ND GEN", "vw_mqb"},
  {"AUDI_A3_MK3", "vw_mqb"},
  {"AUDI_Q2_MK1", "vw_mqb"},
  {"AUDI_Q3_MK2", "vw_mqb"},
  {"BUICK LACROSSE 2017", "gm_global_a_powertrain_generated"},
  {"BUICK REGAL ESSENCE 2018", "gm_global_a_powertrain_generated"},
  {"BUICK_LACROSSE", "gm_global_a_powertrain_generated"},
  {"BUICK_REGAL", "gm_global_a_powertrain_generated"},
  {"CADILLAC ATS Premium Performance 2018", "gm_global_a_powertrain_generated"},
  {"CADILLAC ESCALADE 2017", "gm_global_a_powertrain_generated"},
  {"CADILLAC ESCALADE ESV 2016", "gm_global_a_powertrain_generated"},
  {"CADILLAC ESCALADE ESV 2019", "gm_global_a_powertrain_generated"},
  {"CADILLAC ESCALADE ESV PLATINUM 2019", "gm_global_a_powertrain_generated"},
  {"CADILLAC_ATS", "gm_global_a_powertrain_generated"},
  {"CADILLAC_ESCALADE", "gm_global_a_powertrain_generated"},
  {"CADILLAC_ESCALADE_ESV", "gm_global_a_powertrain_generated"},
  {"CADILLAC_ESCALADE_ESV_2019", "gm_global_a_powertrain_generated"},
  {"CADILLAC_XT4", "gm_global_a_powertrain_generated"},
  {"CHEVROLET BOLT EUV 2022", "gm_global_a_powertrain_generated"},
  {"CHEVROLET EQUINOX 2019", "gm_global_a_powertrain_generated"},
  {"CHEVROLET MALIBU PREMIER 2017", "gm_global_a_powertrain_generated"},
  {"CHEVROLET SILVERADO 1500 2020", "gm_global_a_powertrain_generated"},
  {"CHEVROLET TRAILBLAZER 2021", "gm_global_a_powertrain_generated"},
  {"CHEVROLET VOLT PREMIER 2017", "gm_global_a_powertrain_generated"},
  {"CHEVROLET_BOLT_EUV", "gm_global_a_powertrain_generated"},
  {"CHEVROLET_EQUINOX", "gm_global_a_powertrain_generated"},
  {"CHEVROLET_MALIBU", "gm_global_a_powertrain_generated"},
  {"CHEVROLET_SILVERADO", "gm_global_a_powertrain_generated"},
  {"CHEVROLET_TRAILBLAZER", "gm_global_a_powertrain_generated"},
  {"CHEVROLET_TRAVERSE", "gm_global_a_powertrain_generated"},
  {"CHEVROLET_VOLT", "gm_global_a_powertrain_generated"},
  {"CHEVROLET_VOLT_2019", "gm_global_a_powertrain_generated"},
  {"CHRYSLER PACIFICA 2018", "chrysler_pacifica_2017_hybrid_generated"},
  {"CHRYSLER PACIFICA 2020", "chrysler_pacifica_2017_hybrid_generated"},
  {"CHRYSLER PACIFICA HYBRID 2017", "chrysler_pacifica_2017_hybrid_generated"},
  {"CHRYSLER PACIFICA HYBRID 2018", "chrysler_pacifica_2017_hybrid_generated"},
  {"CHRYSLER PACIFICA HYBRID 2019", "chrysler_pacifica_2017_hybrid_generated"},
  {"CHRYSLER_PACIFICA_2017_HYBRID", "chrysler_pacifica_2017_hybrid_generated"},
  {"CHRYSLER_PACIFICA_2018", "chrysler_pacifica_2017_hybrid_generated"},
  {"CHRYSLER_PACIFICA_2018_HYBRID", "chrysler_pacifica_2017_hybrid_generated"},
  {"CHRYSLER_PACIFICA_2019_HYBRID", "chrysler_pacifica_2017_hybrid_generated"},
  {"CHRYSLER_PACIFICA_2020", "chrysler_pacifica_2017_hybrid_generated"},
  {"COMMA BODY", "comma_body"},
  {"COMMA_BODY", "comma_body"},
  {"DODGE DURANGO 2021", "chrysler_pacifica_2017_hybrid_generated"},
  {"DODGE_DURANGO", "chrysler_pacifica_2017_hybrid_generated"},
  {"FORD BRONCO SPORT 1ST GEN", "ford_lincoln_base_pt"},
  {"FORD ESCAPE 4TH GEN", "ford_lincoln_base_pt"},
  {"FORD EXPLORER 6TH GEN", "ford_lincoln_base_pt"},
  {"FORD F-150 14TH GEN", "ford_lincoln_base_pt"},
  {"FORD F-150 LIGHTNING 1ST GEN", "ford_lincoln_base_pt"},
  {"FORD FOCUS 4TH GEN", "ford_lincoln_base_pt"},
  {"FORD MAVERICK 1ST GEN", "ford_lincoln_base_pt"},
  {"FORD MUSTANG MACH-E 1ST GEN", "ford_lincoln_base_pt"},
  {"FORD_BRONCO_SPORT_MK1", "ford_lincoln_base_pt"},
  {"FORD_ESCAPE_MK4", "ford_lincoln_base_pt"},
  {"FORD_ESCAPE_MK4_5", "ford_lincoln_base_pt"},
  {"FORD_EXPEDITION_MK4", "ford_lincoln_base_pt"},
  {"FORD_EXPLORER_MK6", "ford_lincoln_base_pt"},
  {"FORD_FOCUS_MK4", "ford_lincoln_base_pt"},
  {"FORD_F_150_LIGHTNING_MK1", "ford_lincoln_base_pt"},
  {"FORD_F_150_MK14", "ford_lincoln_base_pt"},
  {"FORD_MAVERICK_MK1", "ford_lincoln_base_pt"},
  {"FORD_MUSTANG_MACH_E_MK1", "ford_lincoln_base_pt"},
  {"FORD_RANGER_MK2", "ford_lincoln_base_pt"},
  {"GENESIS G70 2018", "hyundai_kia_generic"},
  {"GENESIS G70 2020", "hyundai_kia_generic"},
  {"GENESIS G80 2017", "hyundai_kia_generic"},
  {"GENESIS G90 2017", "hyundai_kia_generic"},
  {"GENESIS GV60 ELECTRIC 1ST GEN", "hyundai_canfd_generated"},
  {"GENESIS GV70 1ST GEN", "hyundai_canfd_generated"},
  {"GENESIS GV80 2023", "hyundai_canfd_generated"},
  {"GENESIS_G70", "hyundai_kia_generic"},
  {"GENESIS_G70_2020", "hyundai_kia_generic"},
  {"GENESIS_G80", "hyundai_kia_generic"},
  {"GENESIS_G80_2ND_GEN_FL", "hyundai_canfd_generated"},
  {"GENESIS_G90", "hyundai_kia_generic"},
  {"GENESIS_GV60_EV_1ST_GEN", "hyundai_canfd_generated"},
  {"GENESIS_GV70_1ST_GEN", "hyundai_canfd_generated"},
  {"GENESIS_GV70_ELECTRIFIED_1ST_GEN", "hyundai_canfd_generated"},
  {"GENESIS_GV80", "hyundai_canfd_generated"},
  {"GMC ACADIA DENALI 2018", "gm_global_a_powertrain_generated"},
  {"GMC_ACADIA", "gm_global_a_powertrain_generated"},
  {"GMC_YUKON", "gm_global_a_powertrain_generated"},
  {"HOLDEN ASTRA RS-V BK 2017", "gm_global_a_powertrain_generated"},
  {"HOLDEN_ASTRA", "gm_global_a_powertrain_generated"},
  {"HONDA ACCORD 1.5T 2018", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA ACCORD 2018", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA ACCORD 2018 HYBRID TOURING", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA ACCORD 2018 LX 1.5T", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA ACCORD 2018 SPORT 2T", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA ACCORD 2T 2018", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA ACCORD HYBRID 2018", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA CIVIC (BOSCH) 2019", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA CIVIC 2016", "honda_civic_touring_2016_can_generated"},
  {"HONDA CIVIC 2016 TOURING", "honda_civic_touring_2016_can_generated"},
  {"HONDA CIVIC 2022", "honda_bosch_radarless_generated"},
  {"HONDA CIVIC HATCHBACK 2017 SEDAN/COUPE 2019", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA CIVIC SEDAN 1.6 DIESEL", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA CIVIC SEDAN 1.6 DIESEL 2019", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA CR-V 2016", "honda_crv_touring_2016_can_generated"},
  {"HONDA CR-V 2016 EXECUTIVE", "honda_crv_touring_2016_can_generated"},
  {"HONDA CR-V 2016 TOURING", "honda_crv_touring_2016_can_generated"},
  {"HONDA CR-V 2017", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA CR-V 2017 EX", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA CR-V 2019 HYBRID", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA CR-V EU 2016", "honda_crv_touring_2016_can_generated"},
  {"HONDA CR-V HYBRID 2019", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA E 2020", "acura_rdx_2020_can_generated"},
  {"HONDA FIT 2018", "acura_ilx_2016_can_generated"},
  {"HONDA FIT 2018 EX", "acura_ilx_2016_can_generated"},
  {"HONDA FREED 2020", "acura_ilx_2016_can_generated"},
  {"HONDA HR-V 2023", "honda_bosch_radarless_generated"},
  {"HONDA HRV 2019", "acura_ilx_2016_can_generated"},
  {"HONDA HRV 2019 TOURING", "acura_ilx_2016_can_generated"},
  {"HONDA INSIGHT 2019", "honda_insight_ex_2019_can_generated"},
  {"HONDA INSIGHT 2019 TOURING", "honda_insight_ex_2019_can_generated"},
  {"HONDA ODYSSEY 2018", "honda_odyssey_exl_2018_generated"},
  {"HONDA ODYSSEY 2018 EX-L", "honda_odyssey_exl_2018_generated"},
  {"HONDA PASSPORT 2021", "acura_ilx_2016_can_generated"},
  {"HONDA PILOT 2017", "acura_ilx_2016_can_generated"},
  {"HONDA PILOT 2017 TOURING", "acura_ilx_2016_can_generated"},
  {"HONDA PILOT 2019", "acura_ilx_2016_can_generated"},
  {"HONDA PILOT 2019 ELITE", "acura_ilx_2016_can_generated"},
  {"HONDA RIDGELINE 2017", "acura_ilx_2016_can_generated"},
  {"HONDA RIDGELINE 2017 BLACK EDITION", "acura_ilx_2016_can_generated"},
  {"HONDA_ACCORD", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA_ACCORD_11G", "honda_common_canfd_generated"},
  {"HONDA_CITY_7G", "honda_bosch_radarless_generated"},
  {"HONDA_CIVIC", "honda_civic_touring_2016_can_generated"},
  {"HONDA_CIVIC_2022", "honda_bosch_radarless_generated"},
  {"HONDA_CIVIC_BOSCH", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA_CIVIC_BOSCH_DIESEL", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA_CRV", "honda_crv_touring_2016_can_generated"},
  {"HONDA_CRV_5G", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA_CRV_6G", "honda_common_canfd_generated"},
  {"HONDA_CRV_EU", "honda_crv_touring_2016_can_generated"},
  {"HONDA_CRV_HYBRID", "honda_civic_hatchback_ex_2017_can_generated"},
  {"HONDA_E", "acura_rdx_2020_can_generated"},
  {"HONDA_FIT", "acura_ilx_2016_can_generated"},
  {"HONDA_FREED", "acura_ilx_2016_can_generated"},
  {"HONDA_HRV", "acura_ilx_2016_can_generated"},
  {"HONDA_HRV_3G", "honda_bosch_radarless_generated"},
  {"HONDA_INSIGHT", "honda_insight_ex_2019_can_generated"},
  {"HONDA_NBOX_2G", "acura_rdx_2020_can_generated"},
  {"HONDA_ODYSSEY", "honda_odyssey_exl_2018_generated"},
  {"HONDA_ODYSSEY_5G_MMR", "acura_rdx_2020_can_generated"},
  {"HONDA_ODYSSEY_TWN", "honda_odyssey_twn_2018_generated"},
  {"HONDA_PASSPORT_4G", "honda_common_canfd_generated"},
  {"HONDA_PILOT", "acura_ilx_2016_can_generated"},
  {"HONDA_PILOT_4G", "honda_common_canfd_generated"},
  {"HONDA_RIDGELINE", "acura_ilx_2016_can_generated"},
  {"HYUNDAI AZERA 6TH GEN", "hyundai_kia_generic"},
  {"HYUNDAI AZERA HYBRID 6TH GEN", "hyundai_kia_generic"},
  {"HYUNDAI CUSTIN 1ST GEN", "hyundai_kia_generic"},
  {"HYUNDAI ELANTRA 2017", "hyundai_kia_generic"},
  {"HYUNDAI ELANTRA 2021", "hyundai_kia_generic"},
  {"HYUNDAI ELANTRA HYBRID 2021", "hyundai_kia_generic"},
  {"HYUNDAI ELANTRA LIMITED ULTIMATE 2017", "hyundai_kia_generic"},
  {"HYUNDAI GENESIS 2015-2016", "hyundai_kia_generic"},
  {"HYUNDAI I30 N LINE 2019 & GT 2018 DCT", "hyundai_kia_generic"},
  {"HYUNDAI IONIQ 5 2022", "hyundai_canfd_generated"},
  {"HYUNDAI IONIQ 6 2023", "hyundai_canfd_generated"},
  {"HYUNDAI IONIQ ELECTRIC 2020", "hyundai_kia_generic"},
  {"HYUNDAI IONIQ ELECTRIC LIMITED 2019", "hyundai_kia_generic"},
  {"HYUNDAI IONIQ HYBRID 2017-2019", "hyundai_kia_generic"},
  {"HYUNDAI IONIQ HYBRID 2020-2022", "hyundai_kia_generic"},
  {"HYUNDAI IONIQ PHEV 2020", "hyundai_kia_generic"},
  {"HYUNDAI IONIQ PLUG-IN HYBRID 2019", "hyundai_kia_generic"},
  {"HYUNDAI KONA 2020", "hyundai_kia_generic"},
  {"HYUNDAI KONA ELECTRIC 2019", "hyundai_kia_generic"},
  {"HYUNDAI KONA ELECTRIC 2022", "hyundai_kia_generic"},
  {"HYUNDAI KONA ELECTRIC 2ND GEN", "hyundai_canfd_generated"},
  {"HYUNDAI KONA HYBRID 2020", "hyundai_kia_generic"},
  {"HYUNDAI PALISADE 2020", "hyundai_kia_generic"},
  {"HYUNDAI SANTA CRUZ 1ST GEN", "hyundai_canfd_generated"},
  {"HYUNDAI SANTA FE 2019", "hyundai_kia_generic"},
  {"HYUNDAI SANTA FE 2022", "hyundai_kia_generic"},
  {"HYUNDAI SANTA FE HYBRID 2022", "hyundai_kia_generic"},
  {"HYUNDAI SANTA FE LIMITED 2019", "hyundai_kia_generic"},
  {"HYUNDAI SANTA FE PlUG-IN HYBRID 2022", "hyundai_kia_generic"},
  {"HYUNDAI SONATA 2019", "hyundai_kia_generic"},
  {"HYUNDAI SONATA 2020", "hyundai_kia_generic"},
  {"HYUNDAI SONATA HYBRID 2021", "hyundai_kia_generic"},
  {"HYUNDAI STARIA 4TH GEN", "hyundai_canfd_generated"},
  {"HYUNDAI TUCSON 2019", "hyundai_kia_generic"},
  {"HYUNDAI TUCSON 4TH GEN", "hyundai_canfd_generated"},
  {"HYUNDAI TUCSON DIESEL 2019", "hyundai_kia_generic"},
  {"HYUNDAI TUCSON HYBRID 4TH GEN", "hyundai_canfd_generated"},
  {"HYUNDAI VELOSTER 2019", "hyundai_kia_generic"},
  {"HYUNDAI_AZERA_6TH_GEN", "hyundai_kia_generic"},
  {"HYUNDAI_AZERA_HEV_6TH_GEN", "hyundai_kia_generic"},
  {"HYUNDAI_CUSTIN_1ST_GEN", "hyundai_kia_generic"},
  {"HYUNDAI_ELANTRA", "hyundai_kia_generic"},
  {"HYUNDAI_ELANTRA_2021", "hyundai_kia_generic"},
  {"HYUNDAI_ELANTRA_GT_I30", "hyundai_kia_generic"},
  {"HYUNDAI_ELANTRA_HEV_2021", "hyundai_kia_generic"},
  {"HYUNDAI_GENESIS", "hyundai_kia_generic"},
  {"HYUNDAI_IONIQ", "hyundai_kia_generic"},
  {"HYUNDAI_IONIQ_5", "hyundai_canfd_generated"},
  {"HYUNDAI_IONIQ_6", "hyundai_canfd_generated"},
  {"HYUNDAI_IONIQ_EV_2020", "hyundai_kia_generic"},
  {"HYUNDAI_IONIQ_EV_LTD", "hyundai_kia_generic"},
  {"HYUNDAI_IONIQ_HEV_2022", "hyundai_kia_generic"},
  {"HYUNDAI_IONIQ_PHEV", "hyundai_kia_generic"},
  {"HYUNDAI_IONIQ_PHEV_2019", "hyundai_kia_generic"},
  {"HYUNDAI_KONA", "hyundai_kia_generic"},
  {"HYUNDAI_KONA_2022", "hyundai_kia_generic"},
  {"HYUNDAI_KONA_EV", "hyundai_kia_generic"},
  {"HYUNDAI_KONA_EV_2022", "hyundai_kia_generic"},
  {"HYUNDAI_KONA_EV_2ND_GEN", "hyundai_canfd_generated"},
  {"HYUNDAI_KONA_HEV", "hyundai_kia_generic"},
  {"HYUNDAI_NEXO_1ST_GEN", "hyundai_kia_generic"},
  {"HYUNDAI_PALISADE", "hyundai_kia_generic"},
  {"HYUNDAI_SANTA_CRUZ_1ST_GEN", "hyundai_canfd_generated"},
  {"HYUNDAI_SANTA_FE", "hyundai_kia_generic"},
  {"HYUNDAI_SANTA_FE_2022", "hyundai_kia_generic"},
  {"HYUNDAI_SANTA_FE_HEV_2022", "hyundai_kia_generic"},
  {"HYUNDAI_SANTA_FE_PHEV_2022", "hyundai_kia_generic"},
  {"HYUNDAI_SONATA", "hyundai_kia_generic"},
  {"HYUNDAI_SONATA_HYBRID", "hyundai_kia_generic"},
  {"HYUNDAI_SONATA_LF", "hyundai_kia_generic"},
  {"HYUNDAI_STARIA_4TH_GEN", "hyundai_canfd_generated"},
  {"HYUNDAI_TUCSON", "hyundai_kia_generic"},
  {"HYUNDAI_TUCSON_4TH_GEN", "hyundai_canfd_generated"},
  {"HYUNDAI_VELOSTER", "hyundai_kia_generic"},
  {"JEEP GRAND CHEROKEE 2019", "chrysler_pacifica_2017_hybrid_generated"},
  {"JEEP GRAND CHEROKEE V6 2018", "chrysler_pacifica_2017_hybrid_generated"},
  {"JEEP_GRAND_CHEROKEE", "chrysler_pacifica_2017_hybrid_generated"},
  {"JEEP_GRAND_CHEROKEE_2019", "chrysler_pacifica_2017_hybrid_generated"},
  {"KIA CARNIVAL 4TH GEN", "hyundai_canfd_generated"},
  {"KIA CEED INTRO ED 2019", "hyundai_kia_generic"},
  {"KIA EV6 2022", "hyundai_canfd_generated"},
  {"KIA FORTE E 2018 & GT 2021", "hyundai_kia_generic"},
  {"KIA K5 2021", "hyundai_kia_generic"},
  {"KIA K5 HYBRID 2020", "hyundai_kia_generic"},
  {"KIA K8 HYBRID 1ST GEN", "hyundai_canfd_generated"},
  {"KIA NIRO EV 2020", "hyundai_kia_generic"},
  {"KIA NIRO EV 2ND GEN", "hyundai_canfd_generated"},
  {"KIA NIRO HYBRID 2019", "hyundai_kia_generic"},
  {"KIA NIRO HYBRID 2021", "hyundai_kia_generic"},
  {"KIA NIRO HYBRID 2ND GEN", "hyundai_canfd_generated"},
  {"KIA NIRO PLUG-IN HYBRID 2022", "hyundai_kia_generic"},
  {"KIA OPTIMA 2016", "hyundai_kia_generic"},
  {"KIA OPTIMA 2019", "hyundai_kia_generic"},
  {"KIA OPTIMA 4TH GEN", "hyundai_kia_generic"},
  {"KIA OPTIMA 4TH GEN FACELIFT", "hyundai_kia_generic"},
  {"KIA OPTIMA HYBRID 2017 & SPORTS 2019", "hyundai_kia_generic"},
  {"KIA OPTIMA HYBRID 4TH GEN FACELIFT", "hyundai_kia_generic"},
  {"KIA OPTIMA SX 2019 & 2016", "hyundai_kia_generic"},
  {"KIA SELTOS 2021", "hyundai_kia_generic"},
  {"KIA SORENTO 4TH GEN", "hyundai_canfd_generated"},
  {"KIA SORENTO GT LINE 2018", "hyundai_kia_generic"},
  {"KIA SORENTO HYBRID 4TH GEN", "hyundai_canfd_generated"},
  {"KIA SORENTO PLUG-IN HYBRID 4TH GEN", "hyundai_canfd_generated"},
  {"KIA SPORTAGE 5TH GEN", "hyundai_canfd_generated"},
  {"KIA SPORTAGE HYBRID 5TH GEN", "hyundai_canfd_generated"},
  {"KIA STINGER 2022", "hyundai_kia_generic"},
  {"KIA STINGER GT2 2018", "hyundai_kia_generic"},
  {"KIA_CARNIVAL_4TH_GEN", "hyundai_canfd_generated"},
  {"KIA_CEED", "hyundai_kia_generic"},
  {"KIA_EV6", "hyundai_canfd_generated"},
  {"KIA_FORTE", "hyundai_kia_generic"},
  {"KIA_K5_2021", "hyundai_kia_generic"},
  {"KIA_K5_HEV_2020", "hyundai_kia_generic"},
  {"KIA_K8_HEV_1ST_GEN", "hyundai_canfd_generated"},
  {"KIA_NIRO_EV", "hyundai_kia_generic"},
  {"KIA_NIRO_EV_2ND_GEN", "hyundai_canfd_generated"},
  {"KIA_NIRO_HEV_2021", "hyundai_kia_generic"},
  {"KIA_NIRO_HEV_2ND_GEN", "hyundai_canfd_generated"},
  {"KIA_NIRO_PHEV", "hyundai_kia_generic"},
  {"KIA_NIRO_PHEV_2022", "hyundai_kia_generic"},
  {"KIA_OPTIMA_G4", "hyundai_kia_generic"},
  {"KIA_OPTIMA_G4_FL", "hyundai_kia_generic"},
  {"KIA_OPTIMA_H", "hyundai_kia_generic"},
  {"KIA_OPTIMA_H_G4_FL", "hyundai_kia_generic"},
  {"KIA_SELTOS", "hyundai_kia_generic"},
  {"KIA_SORENTO", "hyundai_kia_generic"},
  {"KIA_SORENTO_4TH_GEN", "hyundai_canfd_generated"},
  {"KIA_SORENTO_HEV_4TH_GEN", "hyundai_canfd_generated"},
  {"KIA_SPORTAGE_5TH_GEN", "hyundai_canfd_generated"},
  {"KIA_STINGER", "hyundai_kia_generic"},
  {"KIA_STINGER_2022", "hyundai_kia_generic"},
  {"LEXUS CT 200H 2018", "toyota_new_mc_pt_generated"},
  {"LEXUS CT HYBRID 2018", "toyota_new_mc_pt_generated"},
  {"LEXUS ES 2018", "toyota_new_mc_pt_generated"},
  {"LEXUS ES 2019", "toyota_nodsu_pt_generated"},
  {"LEXUS ES 300H 2018", "toyota_new_mc_pt_generated"},
  {"LEXUS ES 300H 2019", "toyota_nodsu_pt_generated"},
  {"LEXUS ES HYBRID 2018", "toyota_new_mc_pt_generated"},
  {"LEXUS ES HYBRID 2019", "toyota_nodsu_pt_generated"},
  {"LEXUS GS F 2016", "toyota_new_mc_pt_generated"},
  {"LEXUS IS 2018", "toyota_tnga_k_pt_generated"},
  {"LEXUS IS 2023", "toyota_nodsu_pt_generated"},
  {"LEXUS IS300 2018", "toyota_tnga_k_pt_generated"},
  {"LEXUS LC 2024", "toyota_nodsu_pt_generated"},
  {"LEXUS NX 2018", "toyota_tnga_k_pt_generated"},
  {"LEXUS NX 2020", "toyota_nodsu_pt_generated"},
  {"LEXUS NX HYBRID 2018", "toyota_tnga_k_pt_generated"},
  {"LEXUS NX HYBRID 2020", "toyota_nodsu_pt_generated"},
  {"LEXUS NX300 2018", "toyota_tnga_k_pt_generated"},
  {"LEXUS NX300H 2018", "toyota_tnga_k_pt_generated"},
  {"LEXUS RC 2020", "toyota_tnga_k_pt_generated"},
  {"LEXUS RX 2016", "toyota_tnga_k_pt_generated"},
  {"LEXUS RX 2020", "toyota_nodsu_pt_generated"},
  {"LEXUS RX 350 2016", "toyota_tnga_k_pt_generated"},
  {"LEXUS RX HYBRID 2017", "toyota_tnga_k_pt_generated"},
  {"LEXUS RX HYBRID 2020", "toyota_nodsu_pt_generated"},
  {"LEXUS RX350 2020", "toyota_nodsu_pt_generated"},
  {"LEXUS RX450 HYBRID 2020", "toyota_nodsu_pt_generated"},
  {"LEXUS_CTH", "toyota_new_mc_pt_generated"},
  {"LEXUS_ES", "toyota_new_mc_pt_generated"},
  {"LEXUS_ES_TSS2", "toyota_nodsu_pt_generated"},
  {"LEXUS_GS_F", "toyota_new_mc_pt_generated"},
  {"LEXUS_IS", "toyota_tnga_k_pt_generated"},
  {"LEXUS_IS_TSS2", "toyota_nodsu_pt_generated"},
  {"LEXUS_LC_TSS2", "toyota_nodsu_pt_generated"},
  {"LEXUS_LS", "toyota_nodsu_pt_generated"},
  {"LEXUS_NX", "toyota_tnga_k_pt_generated"},
  {"LEXUS_NX_TSS2", "toyota_nodsu_pt_generated"},
  {"LEXUS_RC", "toyota_tnga_k_pt_generated"},
  {"LEXUS_RC_TSS2", "toyota_nodsu_pt_generated"},
  {"LEXUS_RX", "toyota_tnga_k_pt_generated"},
  {"LEXUS_RX_TSS2", "toyota_nodsu_pt_generated"},
  {"MAZDA 3", "mazda_2017"},
  {"MAZDA 6", "mazda_2017"},
  {"MAZDA CX-5", "mazda_2017"},
  {"MAZDA CX-5 2022", "mazda_2017"},
  {"MAZDA CX-9", "mazda_2017"},
  {"MAZDA CX-9 2021", "mazda_2017"},
  {"MAZDA_3", "mazda_2017"},
  {"MAZDA_6", "mazda_2017"},
  {"MAZDA_CX5", "mazda_2017"},
  {"MAZDA_CX5_2022", "mazda_2017"},
  {"MAZDA_CX9", "mazda_2017"},
  {"MAZDA_CX9_2021", "mazda_2017"},
  {"NISSAN ALTIMA 2020", "nissan_x_trail_2017_generated"},
  {"NISSAN LEAF 2018", "nissan_leaf_2018_generated"},
  {"NISSAN LEAF 2018 Instrument Cluster", "nissan_leaf_2018_generated"},
  {"NISSAN ROGUE 2019", "nissan_x_trail_2017_generated"},
  {"NISSAN X-TRAIL 2017", "nissan_x_trail_2017_generated"},
  {"NISSAN_ALTIMA", "nissan_x_trail_2017_generated"},
  {"NISSAN_LEAF", "nissan_leaf_2018_generated"},
  {"NISSAN_LEAF_IC", "nissan_leaf_2018_generated"},
  {"NISSAN_ROGUE", "nissan_x_trail_2017_generated"},
  {"NISSAN_XTRAIL", "nissan_x_trail_2017_generated"},
  {"PORSCHE_MACAN_MK1", "vw_mlb"},
  {"PSA_PEUGEOT_208", "psa_aee2010_r3"},
  {"RAM 1500 5TH GEN", "chrysler_ram_dt_generated"},
  {"RAM HD 5TH GEN", "chrysler_ram_hd_generated"},
  {"RAM_1500_5TH_GEN", "chrysler_ram_dt_generated"},
  {"RAM_HD_5TH_GEN", "chrysler_ram_hd_generated"},
  {"RIVIAN_R1_GEN1", "rivian_primary_actuator"},
  {"SEAT ATECA 1ST GEN", "vw_mqb"},
  {"SEAT LEON 3RD GEN", "vw_mqb"},
  {"SEAT_ATECA_MK1", "vw_mqb"},
  {"SEAT_LEON_MK3", "vw_mqb"},
  {"SKODA FABIA 4TH GEN", "vw_mqb"},
  {"SKODA KAMIQ 1ST GEN", "vw_mqb"},
  {"SKODA KAROQ 1ST GEN", "vw_mqb"},
  {"SKODA KODIAQ 1ST GEN", "vw_mqb"},
  {"SKODA OCTAVIA 3RD GEN", "vw_mqb"},
  {"SKODA SCALA 1ST GEN", "vw_mqb"},
  {"SKODA SUPERB 3RD GEN", "vw_mqb"},
  {"SKODA_FABIA_MK4", "vw_mqb"},
  {"SKODA_KAMIQ_MK1", "vw_mqb"},
  {"SKODA_KAROQ_MK1", "vw_mqb"},
  {"SKODA_KODIAQ_MK1", "vw_mqb"},
  {"SKODA_OCTAVIA_MK3", "vw_mqb"},
  {"SKODA_SCALA_MK1", "vw_mqb"},
  {"SKODA_SUPERB_MK3", "vw_mqb"},
  {"SUBARU ASCENT 2023", "subaru_global_2017_generated"},
  {"SUBARU ASCENT LIMITED 2019", "subaru_global_2017_generated"},
  {"SUBARU CROSSTREK HYBRID 2020", "subaru_global_2020_hybrid_generated"},
  {"SUBARU FORESTER 2017 - 2018", "subaru_forester_2017_generated"},
  {"SUBARU FORESTER 2019", "subaru_global_2017_generated"},
  {"SUBARU FORESTER 2022", "subaru_global_2017_generated"},
  {"SUBARU FORESTER HYBRID 2020", "subaru_global_2020_hybrid_generated"},
  {"SUBARU IMPREZA LIMITED 2019", "subaru_global_2017_generated"},
  {"SUBARU IMPREZA SPORT 2020", "subaru_global_2017_generated"},
  {"SUBARU LEGACY 2015 - 2018", "subaru_outback_2015_generated"},
  {"SUBARU LEGACY 7TH GEN", "subaru_global_2017_generated"},
  {"SUBARU OUTBACK 2015 - 2017", "subaru_outback_2015_generated"},
  {"SUBARU OUTBACK 2018 - 2019", "subaru_outback_2019_generated"},
  {"SUBARU OUTBACK 6TH GEN", "subaru_global_2017_generated"},
  {"SUBARU OUTBACK 7TH GEN", "subaru_global_2017_generated"},
  {"SUBARU_ASCENT", "subaru_global_2017_generated"},
  {"SUBARU_ASCENT_2023", "subaru_global_2017_generated"},
  {"SUBARU_CROSSTREK_HYBRID", "subaru_global_2020_hybrid_generated"},
  {"SUBARU_FORESTER", "subaru_global_2017_generated"},
  {"SUBARU_FORESTER_2022", "subaru_global_2017_generated"},
  {"SUBARU_FORESTER_HYBRID", "subaru_global_2020_hybrid_generated"},
  {"SUBARU_FORESTER_PREGLOBAL", "subaru_forester_2017_generated"},
  {"SUBARU_IMPREZA", "subaru_global_2017_generated"},
  {"SUBARU_IMPREZA_2020", "subaru_global_2017_generated"},
  {"SUBARU_LEGACY", "subaru_global_2017_generated"},
  {"SUBARU_LEGACY_PREGLOBAL", "subaru_outback_2015_generated"},
  {"SUBARU_OUTBACK", "subaru_global_2017_generated"},
  {"SUBARU_OUTBACK_2023", "subaru_global_2017_generated"},
  {"SUBARU_OUTBACK_PREGLOBAL", "subaru_outback_2015_generated"},
  {"SUBARU_OUTBACK_PREGLOBAL_2018", "subaru_outback_2019_generated"},
  {"TESLA_MODEL_3", "tesla_model3_party"},
  {"TESLA_MODEL_X", "tesla_model3_party"},
  {"TESLA_MODEL_Y", "tesla_model3_party"},
  {"TOYOTA ALPHARD 2020", "toyota_nodsu_pt_generated"},
  {"TOYOTA ALPHARD HYBRID 2021", "toyota_nodsu_pt_generated"},
  {"TOYOTA AVALON 2016", "toyota_tnga_k_pt_generated"},
  {"TOYOTA AVALON 2019", "toyota_nodsu_pt_generated"},
  {"TOYOTA AVALON 2022", "toyota_nodsu_pt_generated"},
  {"TOYOTA AVALON HYBRID 2019", "toyota_nodsu_pt_generated"},
  {"TOYOTA AVALON HYBRID 2022", "toyota_nodsu_pt_generated"},
  {"TOYOTA C-HR 2018", "toyota_nodsu_pt_generated"},
  {"TOYOTA C-HR 2021", "toyota_nodsu_pt_generated"},
  {"TOYOTA C-HR HYBRID 2018", "toyota_nodsu_pt_generated"},
  {"TOYOTA C-HR HYBRID 2022", "toyota_nodsu_pt_generated"},
  {"TOYOTA CAMRY 2018", "toyota_nodsu_pt_generated"},
  {"TOYOTA CAMRY 2021", "toyota_nodsu_pt_generated"},
  {"TOYOTA CAMRY HYBRID 2018", "toyota_nodsu_pt_generated"},
  {"TOYOTA CAMRY HYBRID 2021", "toyota_nodsu_pt_generated"},
  {"TOYOTA COROLLA 2017", "toyota_new_mc_pt_generated"},
  {"TOYOTA COROLLA HYBRID TSS2 2019", "toyota_nodsu_pt_generated"},
  {"TOYOTA COROLLA TSS2 2019", "toyota_nodsu_pt_generated"},
  {"TOYOTA HIGHLANDER 2017", "toyota_tnga_k_pt_generated"},
  {"TOYOTA HIGHLANDER 2020", "toyota_nodsu_pt_generated"},
  {"TOYOTA HIGHLANDER HYBRID 2018", "toyota_tnga_k_pt_generated"},
  {"TOYOTA HIGHLANDER HYBRID 2020", "toyota_nodsu_pt_generated"},
  {"TOYOTA MIRAI 2021", "toyota_nodsu_pt_generated"},
  {"TOYOTA PRIUS 2017", "toyota_nodsu_pt_generated"},
  {"TOYOTA PRIUS TSS2 2021", "toyota_nodsu_pt_generated"},
  {"TOYOTA PRIUS v 2017", "toyota_new_mc_pt_generated"},
  {"TOYOTA RAV4 2017", "toyota_new_mc_pt_generated"},
  {"TOYOTA RAV4 2019", "toyota_nodsu_pt_generated"},
  {"TOYOTA RAV4 2022", "toyota_nodsu_pt_generated"},
  {"TOYOTA RAV4 2023", "toyota_nodsu_pt_generated"},
  {"TOYOTA RAV4 HYBRID 2017", "toyota_tnga_k_pt_generated"},
  {"TOYOTA RAV4 HYBRID 2019", "toyota_nodsu_pt_generated"},
  {"TOYOTA RAV4 HYBRID 2022", "toyota_nodsu_pt_generated"},
  {"TOYOTA RAV4 HYBRID 2023", "toyota_nodsu_pt_generated"},
  {"TOYOTA SIENNA 2018", "toyota_tnga_k_pt_generated"},
  {"TOYOTA SIENNA XLE 2018", "toyota_tnga_k_pt_generated"},
  {"TOYOTA_ALPHARD_TSS2", "toyota_nodsu_pt_generated"},
  {"TOYOTA_AVALON", "toyota_tnga_k_pt_generated"},
  {"TOYOTA_AVALON_2019", "toyota_nodsu_pt_generated"},
  {"TOYOTA_AVALON_TSS2", "toyota_nodsu_pt_generated"},
  {"TOYOTA_CAMRY", "toyota_nodsu_pt_generated"},
  {"TOYOTA_CAMRY_TSS2", "toyota_nodsu_pt_generated"},
  {"TOYOTA_CHR", "toyota_nodsu_pt_generated"},
  {"TOYOTA_CHR_TSS2", "toyota_nodsu_pt_generated"},
  {"TOYOTA_COROLLA", "toyota_new_mc_pt_generated"},
  {"TOYOTA_COROLLA_TSS2", "toyota_nodsu_pt_generated"},
  {"TOYOTA_HIGHLANDER", "toyota_tnga_k_pt_generated"},
  {"TOYOTA_HIGHLANDER_TSS2", "toyota_nodsu_pt_generated"},
  {"TOYOTA_MIRAI", "toyota_nodsu_pt_generated"},
  {"TOYOTA_PRIUS", "toyota_nodsu_pt_generated"},
  {"TOYOTA_PRIUS_TSS2", "toyota_nodsu_pt_generated"},
  {"TOYOTA_PRIUS_V", "toyota_new_mc_pt_generated"},
  {"TOYOTA_RAV4", "toyota_new_mc_pt_generated"},
  {"TOYOTA_RAV4H", "toyota_tnga_k_pt_generated"},
  {"TOYOTA_RAV4_PRIME", "toyota_secoc_pt_generated"},
  {"TOYOTA_RAV4_TSS2", "toyota_nodsu_pt_generated"},
  {"TOYOTA_RAV4_TSS2_2022", "toyota_nodsu_pt_generated"},
  {"TOYOTA_RAV4_TSS2_2023", "toyota_nodsu_pt_generated"},
  {"TOYOTA_SIENNA", "toyota_tnga_k_pt_generated"},
  {"TOYOTA_SIENNA_4TH_GEN", "toyota_secoc_pt_generated"},
  {"TOYOTA_YARIS", "toyota_secoc_pt_generated"},
  {"VOLKSWAGEN ARTEON 1ST GEN", "vw_mqb"},
  {"VOLKSWAGEN ATLAS 1ST GEN", "vw_mqb"},
  {"VOLKSWAGEN CADDY 3RD GEN", "vw_pq"},
  {"VOLKSWAGEN CRAFTER 2ND GEN", "vw_mqb"},
  {"VOLKSWAGEN GOLF 7TH GEN", "vw_mqb"},
  {"VOLKSWAGEN JETTA 6TH GEN", "vw_pq"},
  {"VOLKSWAGEN JETTA 7TH GEN", "vw_mqb"},
  {"VOLKSWAGEN PASSAT 8TH GEN", "vw_mqb"},
  {"VOLKSWAGEN PASSAT NMS", "vw_pq"},
  {"VOLKSWAGEN POLO 6TH GEN", "vw_mqb"},
  {"VOLKSWAGEN SHARAN 2ND GEN", "vw_pq"},
  {"VOLKSWAGEN T-CROSS 1ST GEN", "vw_mqb"},
  {"VOLKSWAGEN T-ROC 1ST GEN", "vw_mqb"},
  {"VOLKSWAGEN TAOS 1ST GEN", "vw_mqb"},
  {"VOLKSWAGEN TIGUAN 2ND GEN", "vw_mqb"},
  {"VOLKSWAGEN TOURAN 2ND GEN", "vw_mqb"},
  {"VOLKSWAGEN TRANSPORTER T6.1", "vw_mqb"},
  {"VOLKSWAGEN_ARTEON_MK1", "vw_mqb"},
  {"VOLKSWAGEN_ATLAS_MK1", "vw_mqb"},
  {"VOLKSWAGEN_CADDY_MK3", "vw_pq"},
  {"VOLKSWAGEN_CRAFTER_MK2", "vw_mqb"},
  {"VOLKSWAGEN_GOLF_MK7", "vw_mqb"},
  {"VOLKSWAGEN_JETTA_MK6", "vw_pq"},
  {"VOLKSWAGEN_JETTA_MK7", "vw_mqb"},
  {"VOLKSWAGEN_PASSAT_MK8", "vw_mqb"},
  {"VOLKSWAGEN_PASSAT_NMS", "vw_pq"},
  {"VOLKSWAGEN_POLO_MK6", "vw_mqb"},
  {"VOLKSWAGEN_SHARAN_MK2", "vw_pq"},
  {"VOLKSWAGEN_TAOS_MK1", "vw_mqb"},
  {"VOLKSWAGEN_TCROSS_MK1", "vw_mqb"},
  {"VOLKSWAGEN_TIGUAN_MK2", "vw_mqb"},
  {"VOLKSWAGEN_TOURAN_MK2", "vw_mqb"},
  {"VOLKSWAGEN_TRANSPORTER_T61", "vw_mqb"},
  {"VOLKSWAGEN_TROC_MK1", "vw_mqb"}
};

inline std::string_view dbc_for_car_fingerprint(std::string_view fingerprint) {
  for (const auto &[car_fingerprint, dbc] : kCarFingerprintToDbc) {
    if (car_fingerprint == fingerprint) return dbc;
  }
  return {};
}
