######################################################################
# Automatically generated by qmake (3.1) Tue Feb 2 22:20:10 2021
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .
QT += gui widgets network core

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
SOURCES += test.cpp ../../nui/FileReader.cpp
HEADERS = ../../nui/FileReader.hpp 

LIBS += -lcapnp -lbz2

