
#pragma once

// EON
const int EON_ROAD_CAM_FOCAL_LENGTH = 910;
const int EON_DRIVER_CAM_FOCAL_LENGTH = 860;

const int EON_ROAD_CAM_FRAME_WIDTH = 1164;
const int EON_ROAD_CAM_FRAME_HEIGHT = 874;
const int EON_DRIVER_CAM_FRAME_WIDTH = 1152;
const int EON_DRIVER_CAM_FRAME_HEIGHT = 864;

const int EON_SCREEN_WIDTH = 1920;
const int EON_SCREEN_HEIGHT = 1080;

// TICI
const int TICI_ROAD_CAM_FOCAL_LENGTH = 2648;
const int TICI_DRIVER_CAM_FOCAL_LENGTH = 860;

const int TICI_FRAME_WIDTH = 1928;
const int TICI_FRAME_HEIGHT = 1208;
const int TICI_SCREEN_WIDTH = 2160;
const int TICI_SCREEN_HEIGHT = 1080;

#ifdef QCOM2
const int ROAD_CAM_FOCAL_LENGTH = TICI_ROAD_CAM_FOCAL_LENGTH;
const int ROAD_CAM_FRAME_WIDTH = TICI_FRAME_WIDTH;
const int ROAD_CAM_FRAME_HEIGHT = TICI_FRAME_HEIGHT;
const int DRIVER_CAM_FRAME_WIDTH = TICI_FRAME_WIDTH;
const int DRIVER_CAM_FRAME_HEIGHT = TICI_FRAME_HEIGHT;
const int SCREEN_WIDTH = TICI_SCREEN_WIDTH;
const int SCREEN_HEIGHT = TICI_SCREEN_HEIGHT;
#else
const int ROAD_CAM_FOCAL_LENGTH = EON_ROAD_CAM_FOCAL_LENGTH;
const int ROAD_CAM_FRAME_WIDTH = EON_ROAD_CAM_FRAME_WIDTH;
const int ROAD_CAM_FRAME_HEIGHT = EON_ROAD_CAM_FRAME_HEIGHT;
const int DRIVER_CAM_FRAME_WIDTH = EON_DRIVER_CAM_FRAME_WIDTH;
const int DRIVER_CAM_FRAME_HEIGHT = EON_DRIVER_CAM_FRAME_HEIGHT;
const int SCREEN_WIDTH = EON_SCREEN_WIDTH;
const int SCREEN_HEIGHT = EON_SCREEN_HEIGHT;
const int adapt_width_tici = 668;
const int crop_x_offset = 32;
const int crop_y_offset = -196;
#endif
const float driver_view_ratio = 1.333;

