Import('env', 'envCython')

common_libs = [
  'params.cc',
  'swaglog.cc',
  'util.cc',
  'ratekeeper.cc',
  'yuv.cc',
]

_common = env.Library('common', common_libs, LIBS="json11")
Export('_common')

if GetOption('extras'):
  env.Program('tests/swaglog_test', 'tests/swaglog_test.cc', LIBS=[_common, 'json11', 'zmq', 'pthread'])

# Cython bindings
params_python = envCython.Program('params_pyx.so', 'params_pyx.pyx', LIBS=envCython['LIBS'] + [_common, 'zmq', 'json11'])

common_python = [params_python]

Export('common_python')
