Import('env', 'envCython')

common_libs = [
  'params.cc',
  'swaglog.cc',
  'util.cc',
  'ratekeeper.cc',
  'yuv.cc',
]

_common = env.Library('common', common_libs, LIBS="json11")
Export('_common')

if GetOption('extras'):
  env.Program('tests/test_swaglog', 'tests/test_swaglog.cc', LIBS=[_common, 'json11', 'zmq', 'pthread'])

# CFFI loads this small C ABI wrapper around the C++ Params implementation.
params_python = env.SharedLibrary('params_cffi', 'params_cffi.cc', LIBS=[_common, 'zmq', 'json11'])

common_python = [params_python]

Export('common_python')
