Import('env', 'arch', 'common', 'messaging')

import panda as panda_package

if arch != "Darwin":
  env.Append(CXXFLAGS=['-DPANDA_FW_PATH=\\"%s\\"' % panda_package.FW_PATH])
  libs = [common, messaging, 'pthread']
  panda = env.Library('panda', ['panda.cc', 'spi.cc'])

  env.Program('pandad', ['main.cc', 'pandad.cc', 'panda_safety.cc'], LIBS=[panda] + libs)

  if GetOption('extras'):
    env.Program('tests/test_pandad_canprotocol', ['tests/test_pandad_canprotocol.cc'], LIBS=[panda] + libs)
