import libusb

Import('env', 'arch', 'common', 'messaging')

if arch != "Darwin":
  pandad_env = env.Clone()
  pandad_env.Append(CPPPATH=[libusb.INCLUDE_DIR])
  pandad_env.Append(LIBPATH=[libusb.LIB_DIR])

  libs = ['usb-1.0', common, messaging, 'pthread']
  panda = pandad_env.Library('panda', ['panda.cc', 'panda_comms.cc', 'spi.cc'])

  pandad_env.Program('pandad', ['main.cc', 'pandad.cc', 'panda_safety.cc'], LIBS=[panda] + libs)

  if GetOption('extras'):
    pandad_env.Program('tests/test_pandad_canprotocol', ['tests/test_pandad_canprotocol.cc'], LIBS=[panda] + libs)
