name: diff report

on:
  workflow_run:
    workflows: [tests]
    types: [completed]

jobs:
  comment:
    name: comment
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.pull_requests[0]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      actions: read
    steps:
    - name: Download diff
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        run-id: ${{ github.event.workflow_run.id }}
        name: diff_report_${{ github.event.workflow_run.pull_requests[0].number }}
        path: .
    - name: Comment on PR
      uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b
      with:
        file-path: diff_report.txt
        comment-tag: diff_report
        pr-number: ${{ github.event.workflow_run.pull_requests[0].number }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
