/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lead_cost_y_e_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s3[12] = {3, 3, 0, 2, 5, 6, 0, 1, 0, 1, 2, 1};

/* lead_cost_y_e_hess:(i0[3],i1[],i2[3],i3[2])->(o0[3x3,6nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
  a0=2.9999999999999999e-01;
  a1=arg[2]? arg[2][0] : 0;
  a2=1.8000000000000000e+00;
  a3=arg[0]? arg[0][1] : 0;
  a4=(a2*a3);
  a5=arg[3]? arg[3][1] : 0;
  a6=(a5-a3);
  a6=(a2*a6);
  a4=(a4-a6);
  a6=casadi_sq(a3);
  a7=1.9620000000000001e+01;
  a6=(a6/a7);
  a4=(a4+a6);
  a5=casadi_sq(a5);
  a5=(a5/a7);
  a4=(a4-a5);
  a5=4.;
  a7=(a4+a5);
  a6=arg[3]? arg[3][0] : 0;
  a8=arg[0]? arg[0][0] : 0;
  a9=(a6-a8);
  a7=(a7-a9);
  a9=5.0000000000000000e-01;
  a10=(a3+a9);
  a10=sqrt(a10);
  a11=1.0000000000000001e-01;
  a12=(a10+a11);
  a7=(a7/a12);
  a13=(a0*a7);
  a13=exp(a13);
  a14=(a0/a12);
  a14=(a13*a14);
  a14=(a1*a14);
  a14=(a0*a14);
  a15=(a14/a12);
  if (res[0]!=0) res[0][0]=a15;
  a16=5.0000000000000003e-02;
  a17=arg[2]? arg[2][1] : 0;
  a18=(a16*a3);
  a18=(a18+a9);
  a9=(1./a18);
  a9=(a9/a18);
  a9=(a17*a9);
  a9=(a16*a9);
  a19=(a13*a1);
  a19=(a0*a19);
  a20=(1./a12);
  a20=casadi_sq(a20);
  a20=(a19*a20);
  a21=(a7/a12);
  a14=(a21*a14);
  a20=(a20+a14);
  a14=(a10+a10);
  a20=(a20/a14);
  a9=(a9-a20);
  a20=(a3+a3);
  a22=5.0968399592252800e-02;
  a23=(a22*a15);
  a23=(a20*a23);
  a9=(a9+a23);
  a23=(a2*a15);
  a9=(a9+a23);
  a15=(a2*a15);
  a9=(a9+a15);
  if (res[0]!=0) res[0][1]=a9;
  a9=3.6000000000000001e+00;
  a3=(a3+a3);
  a3=(a22*a3);
  a9=(a9+a3);
  a3=(a9/a12);
  a7=(a7/a12);
  a10=(a10+a10);
  a7=(a7/a10);
  a3=(a3-a7);
  a7=(a0*a3);
  a13=(a13*a7);
  a1=(a1*a13);
  a0=(a0*a1);
  a1=(a0/a12);
  a13=(a19/a12);
  a7=(a13/a12);
  a7=(a7/a10);
  a1=(a1-a7);
  a7=(a17/a18);
  a15=(a7/a18);
  a15=(a16*a15);
  a23=(a1+a15);
  if (res[0]!=0) res[0][2]=a23;
  a9=(a9/a18);
  a6=(a6-a8);
  a4=(a4+a5);
  a6=(a6-a4);
  a6=(a6/a18);
  a4=(a6/a18);
  a4=(a16*a4);
  a9=(a9+a4);
  a9=(a9/a18);
  a6=(a6/a18);
  a6=(a6/a18);
  a6=(a16*a6);
  a9=(a9+a6);
  a17=(a17*a9);
  a16=(a16*a17);
  a3=(a3/a12);
  a12=(a21/a12);
  a12=(a12/a10);
  a3=(a3-a12);
  a3=(a19*a3);
  a0=(a21*a0);
  a3=(a3+a0);
  a3=(a3/a14);
  a21=(a21*a19);
  a21=(a21/a14);
  a21=(a21/a14);
  a10=(1./a10);
  a10=(a10+a10);
  a21=(a21*a10);
  a3=(a3-a21);
  a16=(a16-a3);
  a3=2.;
  a13=(a13-a7);
  a13=(a22*a13);
  a3=(a3*a13);
  a1=(a1+a15);
  a22=(a22*a1);
  a20=(a20*a22);
  a3=(a3+a20);
  a16=(a16+a3);
  a3=(a2*a1);
  a16=(a16+a3);
  a2=(a2*a1);
  a16=(a16+a2);
  if (res[0]!=0) res[0][3]=a16;
  a16=arg[2]? arg[2][2] : 0;
  a2=(a11*a16);
  if (res[0]!=0) res[0][4]=a2;
  a11=(a11*a16);
  if (res[0]!=0) res[0][5]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int lead_cost_y_e_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lead_cost_y_e_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lead_cost_y_e_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lead_cost_y_e_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lead_cost_y_e_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lead_cost_y_e_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lead_cost_y_e_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void lead_cost_y_e_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lead_cost_y_e_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int lead_cost_y_e_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real lead_cost_y_e_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lead_cost_y_e_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lead_cost_y_e_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lead_cost_y_e_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lead_cost_y_e_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lead_cost_y_e_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
